"""Generate Chapter Three dissertation diagrams for SERPS POP.

The generator intentionally uses implementation-owned definitions and the
current SQLAlchemy metadata for Figure 3.19. Mermaid source files are retained
as editable diagram sources, while SVG/PNG exports are generated by a small
deterministic renderer so the sprint does not depend on a local Mermaid CLI.
"""

from __future__ import annotations

import hashlib
import json
import math
import os
import re
import shutil
import subprocess
import textwrap
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Iterable
from xml.sax.saxutils import escape

from PIL import Image, ImageDraw, ImageFont

from serps_pop.evidence import models as _evidence_models  # noqa: F401
from serps_pop.identity import models as _identity_models  # noqa: F401
from serps_pop.infrastructure.database import Base


ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / "docs" / "dissertation" / "chapter3"
SUBDIRS = [
    "architecture",
    "uml",
    "erd",
    "flowcharts",
    "api",
    "technology",
    "png",
    "png/colour",
    "png/mono_transparent",
    "png/mono_white_background",
    "svg",
    "svg/colour",
    "svg/mono_transparent",
    "svg/mono_white_background",
    "source",
    "source/authoritative",
    "source/legacy",
]

NAVY = "#073B4C"
DEEP_NAVY = "#042A3A"
TEAL = "#0F8B8D"
TEAL_LIGHT = "#DDF7F5"
WHITE = "#FFFFFF"
GREY = "#EEF3F6"
MUTED = "#60717C"
LINE = "#7FA9B5"
AMBER = "#F2B84B"
AMBER_LIGHT = "#FFF4D6"
GREEN = "#2EAD6B"
RED = "#C94C4C"


@dataclass(frozen=True)
class Box:
    x: float
    y: float
    w: float
    h: float
    text: str
    fill: str = WHITE
    stroke: str = TEAL
    color: str = DEEP_NAVY
    title: bool = False
    dashed: bool = False
    radius: float = 18


@dataclass(frozen=True)
class Ellipse:
    x: float
    y: float
    w: float
    h: float
    text: str
    fill: str = WHITE
    stroke: str = TEAL
    color: str = DEEP_NAVY


@dataclass(frozen=True)
class Actor:
    x: float
    y: float
    text: str


@dataclass(frozen=True)
class Diamond:
    x: float
    y: float
    w: float
    h: float
    text: str
    fill: str = AMBER_LIGHT
    stroke: str = TEAL
    color: str = DEEP_NAVY


@dataclass(frozen=True)
class Arrow:
    x1: float
    y1: float
    x2: float
    y2: float
    label: str = ""
    color: str = LINE
    dashed: bool = False


@dataclass(frozen=True)
class Connector:
    x1: float
    y1: float
    x2: float
    y2: float
    label: str = ""
    dashed: bool = False
    width: int = 4


@dataclass(frozen=True)
class Note:
    x: float
    y: float
    text: str
    color: str = MUTED
    size: int = 22


Shape = Box | Ellipse | Actor | Diamond | Arrow | Connector | Note


@dataclass(frozen=True)
class RenderTheme:
    name: str
    background: str | None
    header_fill: str | None
    title_color: str
    subtitle_color: str
    box_fill: str | None
    box_stroke: str
    text_color: str
    muted_color: str
    line_color: str
    shadow: bool = True


COLOUR_THEME = RenderTheme(
    "colour",
    GREY,
    NAVY,
    WHITE,
    TEAL_LIGHT,
    None,
    TEAL,
    DEEP_NAVY,
    MUTED,
    LINE,
    True,
)

MONO_THEME = RenderTheme(
    "mono_transparent",
    None,
    None,
    "#000000",
    "#000000",
    None,
    "#000000",
    "#000000",
    "#000000",
    "#000000",
    False,
)

MONO_WHITE_THEME = RenderTheme(
    "mono_white_background",
    "#FFFFFF",
    None,
    "#000000",
    "#000000",
    "#FFFFFF",
    "#000000",
    "#000000",
    "#000000",
    "#000000",
    False,
)


@dataclass
class Diagram:
    number: str
    title: str
    category: str
    canvas: tuple[int, int]
    shapes: list[Shape]
    mmd: str
    source: str = "Author's Architecture (2026)"
    notes: list[str] = field(default_factory=list)

    @property
    def safe_name(self) -> str:
        safe_title = re.sub(r"[^A-Za-z0-9]+", "_", self.title).strip("_")
        return f"Figure{self.number.replace('.', '_')}_{safe_title}"


def font(size: int, bold: bool = False) -> ImageFont.FreeTypeFont:
    candidates = [
        "C:/Windows/Fonts/arialbd.ttf" if bold else "C:/Windows/Fonts/arial.ttf",
        "C:/Windows/Fonts/segoeuib.ttf" if bold else "C:/Windows/Fonts/segoeui.ttf",
    ]
    for candidate in candidates:
        if Path(candidate).exists():
            return ImageFont.truetype(candidate, size)
    return ImageFont.load_default()


def wrap_text(text: str, max_chars: int) -> list[str]:
    lines: list[str] = []
    for paragraph in text.split("\n"):
        if not paragraph:
            lines.append("")
        else:
            lines.extend(textwrap.wrap(paragraph, width=max_chars, break_long_words=False))
    return lines


def draw_wrapped(
    draw: ImageDraw.ImageDraw,
    xy: tuple[float, float],
    text: str,
    fill: str,
    fnt: ImageFont.FreeTypeFont,
    max_width: float,
    align: str = "center",
) -> None:
    avg = max(fnt.getlength("ABCDEFGHIJKLMNOPQRSTUVWXYZ") / 26, 8)
    lines = wrap_text(text, max(8, int(max_width / avg)))
    line_h = fnt.size + 7
    x, y = xy
    for line in lines:
        bbox = draw.textbbox((0, 0), line, font=fnt)
        width = bbox[2] - bbox[0]
        tx = x
        if align == "center":
            tx = x - width / 2
        elif align == "right":
            tx = x - width
        draw.text((tx, y), line, fill=fill, font=fnt)
        y += line_h


def arrow_head(x1: float, y1: float, x2: float, y2: float, size: float = 16) -> list[tuple[float, float]]:
    angle = math.atan2(y2 - y1, x2 - x1)
    left = angle + math.pi * 0.82
    right = angle - math.pi * 0.82
    return [
        (x2, y2),
        (x2 + size * math.cos(left), y2 + size * math.sin(left)),
        (x2 + size * math.cos(right), y2 + size * math.sin(right)),
    ]


def draw_arrow(draw: ImageDraw.ImageDraw, arrow: Arrow, scale: int = 1, theme: RenderTheme = COLOUR_THEME) -> None:
    x1, y1, x2, y2 = [v * scale for v in (arrow.x1, arrow.y1, arrow.x2, arrow.y2)]
    color = theme.line_color
    width = 4 * scale
    if arrow.dashed:
        steps = max(8, int(math.hypot(x2 - x1, y2 - y1) / (18 * scale)))
        for i in range(steps):
            if i % 2 == 0:
                sx = x1 + (x2 - x1) * i / steps
                sy = y1 + (y2 - y1) * i / steps
                ex = x1 + (x2 - x1) * (i + 1) / steps
                ey = y1 + (y2 - y1) * (i + 1) / steps
                draw.line((sx, sy, ex, ey), fill=color, width=width)
    else:
        draw.line((x1, y1, x2, y2), fill=color, width=width)
    draw.polygon([(x * scale, y * scale) for x, y in arrow_head(arrow.x1, arrow.y1, arrow.x2, arrow.y2)], fill=color)
    if arrow.label:
        mid = ((x1 + x2) / 2, (y1 + y2) / 2 - 18 * scale)
        draw.text(mid, arrow.label, fill=theme.text_color, font=font(18 * scale), anchor="mm")


def draw_connector(draw: ImageDraw.ImageDraw, connector: Connector, scale: int = 1, theme: RenderTheme = COLOUR_THEME) -> None:
    x1, y1, x2, y2 = [v * scale for v in (connector.x1, connector.y1, connector.x2, connector.y2)]
    color = theme.line_color
    width = connector.width * scale
    if connector.dashed:
        steps = max(8, int(math.hypot(x2 - x1, y2 - y1) / (18 * scale)))
        for i in range(steps):
            if i % 2 == 0:
                sx = x1 + (x2 - x1) * i / steps
                sy = y1 + (y2 - y1) * i / steps
                ex = x1 + (x2 - x1) * (i + 1) / steps
                ey = y1 + (y2 - y1) * (i + 1) / steps
                draw.line((sx, sy, ex, ey), fill=color, width=width)
    else:
        draw.line((x1, y1, x2, y2), fill=color, width=width)
    if connector.label:
        mid = ((x1 + x2) / 2, (y1 + y2) / 2 - 18 * scale)
        draw.text(mid, connector.label, fill=theme.text_color, font=font(18 * scale), anchor="mm")


def mermaid_type(column_type: object) -> str:
    raw = column_type.__class__.__name__.lower()
    if "integer" in raw:
        return "int"
    if "float" in raw or "numeric" in raw:
        return "float"
    if "boolean" in raw:
        return "boolean"
    if "date" in raw or "time" in raw:
        return "datetime"
    return "string"


def erd_mermaid_from_metadata(full: bool = False) -> str:
    lines = ["erDiagram"]
    for table in Base.metadata.sorted_tables:
        lines.append(f"  {table.name} {{")
        selected_columns = list(table.columns) if full else [
            column
            for column in table.columns
            if column.primary_key
            or column.foreign_keys
            or column.name in {"email", "name", "title", "status", "role_name", "event_type", "confidence", "monitoring_mode", "risk_level", "created_at"}
        ][:8]
        for column in selected_columns:
            markers = []
            if column.primary_key:
                markers.append("PK")
            if column.foreign_keys:
                markers.append("FK")
            marker_text = f" {' '.join(markers)}" if markers else ""
            lines.append(f"    {mermaid_type(column.type)} {column.name}{marker_text}")
        lines.append("  }")
    for table in Base.metadata.sorted_tables:
        for foreign_key in table.foreign_keys:
            referred = foreign_key.column.table.name
            lines.append(f"  {referred} ||--o{{ {table.name} : references")
    return "\n".join(lines)


def render_png(diagram: Diagram, path: Path, theme: RenderTheme = COLOUR_THEME) -> None:
    w, h = diagram.canvas
    scale = 2
    if theme.background is None:
        img = Image.new("RGBA", (w * scale, h * scale), (255, 255, 255, 0))
    else:
        img = Image.new("RGB", (w * scale, h * scale), theme.background)
    draw = ImageDraw.Draw(img)
    if theme.header_fill:
        draw.rounded_rectangle((50 * scale, 45 * scale, (w - 50) * scale, 145 * scale), radius=26 * scale, fill=theme.header_fill)
    draw.text((75 * scale, 72 * scale), f"Figure {diagram.number}", fill=theme.subtitle_color, font=font(28 * scale, True))
    draw.text((75 * scale, 105 * scale), diagram.title, fill=theme.title_color, font=font(25 * scale, True))

    for shape in diagram.shapes:
        if isinstance(shape, Box):
            rect = tuple(v * scale for v in (shape.x, shape.y, shape.x + shape.w, shape.y + shape.h))
            if theme.shadow:
                shadow = (rect[0] + 5 * scale, rect[1] + 6 * scale, rect[2] + 5 * scale, rect[3] + 6 * scale)
                draw.rounded_rectangle(shadow, radius=shape.radius * scale, fill="#D9E4EA")
            fill = shape.fill if theme.name == "colour" else ((255, 255, 255, 255) if theme.background else (255, 255, 255, 0))
            stroke = shape.stroke if theme.name == "colour" else theme.box_stroke
            text_color = shape.color if theme.name == "colour" else theme.text_color
            draw.rounded_rectangle(rect, radius=shape.radius * scale, fill=fill, outline=stroke, width=3 * scale)
            fnt = font((24 if shape.title else 21) * scale, shape.title)
            lines = wrap_text(shape.text, max(10, int(shape.w / 14)))
            text_h = len(lines) * (fnt.size + 7)
            draw_wrapped(
                draw,
                ((shape.x + shape.w / 2) * scale, (shape.y + shape.h / 2 - text_h / (2 * scale)) * scale),
                shape.text,
                text_color,
                fnt,
                shape.w * scale - 35 * scale,
            )
        elif isinstance(shape, Ellipse):
            rect = tuple(v * scale for v in (shape.x, shape.y, shape.x + shape.w, shape.y + shape.h))
            fill = shape.fill if theme.name == "colour" else ((255, 255, 255, 255) if theme.background else (255, 255, 255, 0))
            stroke = shape.stroke if theme.name == "colour" else theme.box_stroke
            text_color = shape.color if theme.name == "colour" else theme.text_color
            draw.ellipse(rect, fill=fill, outline=stroke, width=3 * scale)
            draw_wrapped(
                draw,
                ((shape.x + shape.w / 2) * scale, (shape.y + shape.h / 2 - 22) * scale),
                shape.text,
                text_color,
                font(20 * scale, True),
                shape.w * scale - 25 * scale,
            )
        elif isinstance(shape, Actor):
            x, y = shape.x * scale, shape.y * scale
            draw.ellipse((x - 18 * scale, y, x + 18 * scale, y + 36 * scale), outline=theme.text_color, width=4 * scale)
            draw.line((x, y + 36 * scale, x, y + 95 * scale), fill=theme.text_color, width=4 * scale)
            draw.line((x - 42 * scale, y + 60 * scale, x + 42 * scale, y + 60 * scale), fill=theme.text_color, width=4 * scale)
            draw.line((x, y + 95 * scale, x - 38 * scale, y + 145 * scale), fill=theme.text_color, width=4 * scale)
            draw.line((x, y + 95 * scale, x + 38 * scale, y + 145 * scale), fill=theme.text_color, width=4 * scale)
            draw_wrapped(draw, (x, y + 155 * scale), shape.text, theme.text_color, font(20 * scale, True), 150 * scale)
        elif isinstance(shape, Diamond):
            points = [
                ((shape.x + shape.w / 2) * scale, shape.y * scale),
                ((shape.x + shape.w) * scale, (shape.y + shape.h / 2) * scale),
                ((shape.x + shape.w / 2) * scale, (shape.y + shape.h) * scale),
                (shape.x * scale, (shape.y + shape.h / 2) * scale),
            ]
            fill = shape.fill if theme.name == "colour" else ((255, 255, 255, 255) if theme.background else (255, 255, 255, 0))
            stroke = shape.stroke if theme.name == "colour" else theme.box_stroke
            text_color = shape.color if theme.name == "colour" else theme.text_color
            draw.polygon(points, fill=fill, outline=stroke)
            draw.line(points + [points[0]], fill=stroke, width=3 * scale)
            draw_wrapped(
                draw,
                ((shape.x + shape.w / 2) * scale, (shape.y + shape.h / 2 - 20) * scale),
                shape.text,
                text_color,
                font(18 * scale, True),
                shape.w * scale - 45 * scale,
            )
        elif isinstance(shape, Arrow):
            draw_arrow(draw, shape, scale, theme)
        elif isinstance(shape, Connector):
            draw_connector(draw, shape, scale, theme)
        elif isinstance(shape, Note):
            color = shape.color if theme.name == "colour" else theme.text_color
            draw_wrapped(draw, (shape.x * scale, shape.y * scale), shape.text, color, font(shape.size * scale), 420 * scale)

    draw.text((w * scale - 70 * scale, h * scale - 45 * scale), "SERPS Architecture", fill=theme.muted_color, font=font(18 * scale), anchor="ra")
    img.save(path, dpi=(300, 300))


def svg_text(x: float, y: float, text: str, size: int, color: str, weight: str = "400", anchor: str = "middle") -> str:
    spans = []
    for i, line in enumerate(wrap_text(text, 32)):
        spans.append(
            f'<text x="{x:.1f}" y="{y + i * (size + 7):.1f}" text-anchor="{anchor}" '
            f'font-family="Segoe UI, Arial, sans-serif" font-size="{size}" font-weight="{weight}" fill="{color}">{escape(line)}</text>'
        )
    return "\n".join(spans)


def render_svg(diagram: Diagram, path: Path, theme: RenderTheme = COLOUR_THEME) -> None:
    w, h = diagram.canvas
    arrow_colour = theme.line_color
    out = [
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{w}" height="{h}" viewBox="0 0 {w} {h}">',
        "<defs>",
        f'<marker id="arrow" markerWidth="12" markerHeight="12" refX="10" refY="6" orient="auto" markerUnits="strokeWidth"><path d="M2,2 L10,6 L2,10 z" fill="{arrow_colour}"/></marker>',
        '<filter id="shadow" x="-20%" y="-20%" width="140%" height="140%"><feDropShadow dx="3" dy="5" stdDeviation="4" flood-color="#9AB2BD" flood-opacity="0.45"/></filter>',
        "</defs>",
    ]
    if theme.background:
        out.append(f'<rect width="{w}" height="{h}" fill="{theme.background}"/>')
    if theme.header_fill:
        out.append(f'<rect x="50" y="45" width="{w-100}" height="100" rx="26" fill="{theme.header_fill}"/>')
    out.append(svg_text(75, 84, f"Figure {diagram.number}", 28, theme.subtitle_color, "700", "start"))
    out.append(svg_text(75, 118, diagram.title, 25, theme.title_color, "700", "start"))
    for shape in diagram.shapes:
        if isinstance(shape, Box):
            dash = ' stroke-dasharray="8 7"' if shape.dashed else ""
            fill = shape.fill if theme.name == "colour" else ("#FFFFFF" if theme.background else "none")
            stroke = shape.stroke if theme.name == "colour" else theme.box_stroke
            text_color = shape.color if theme.name == "colour" else theme.text_color
            filter_attr = ' filter="url(#shadow)"' if theme.shadow else ""
            out.append(
                f'<rect x="{shape.x}" y="{shape.y}" width="{shape.w}" height="{shape.h}" rx="{shape.radius}" '
                f'fill="{fill}" stroke="{stroke}" stroke-width="3"{dash}{filter_attr}/>'
            )
            lines = wrap_text(shape.text, max(10, int(shape.w / 12)))
            size = 24 if shape.title else 21
            out.append(svg_text(shape.x + shape.w / 2, shape.y + shape.h / 2 - (len(lines) * (size + 7)) / 2 + size, shape.text, size, text_color, "700" if shape.title else "500"))
        elif isinstance(shape, Ellipse):
            fill = shape.fill if theme.name == "colour" else ("#FFFFFF" if theme.background else "none")
            stroke = shape.stroke if theme.name == "colour" else theme.box_stroke
            text_color = shape.color if theme.name == "colour" else theme.text_color
            out.append(
                f'<ellipse cx="{shape.x + shape.w/2}" cy="{shape.y + shape.h/2}" rx="{shape.w/2}" ry="{shape.h/2}" fill="{fill}" stroke="{stroke}" stroke-width="3"/>'
            )
            out.append(svg_text(shape.x + shape.w / 2, shape.y + shape.h / 2, shape.text, 20, text_color, "700"))
        elif isinstance(shape, Actor):
            x, y = shape.x, shape.y
            out.append(f'<circle cx="{x}" cy="{y+18}" r="18" fill="none" stroke="{theme.text_color}" stroke-width="4"/>')
            out.append(f'<path d="M{x},{y+36} L{x},{y+95} M{x-42},{y+60} L{x+42},{y+60} M{x},{y+95} L{x-38},{y+145} M{x},{y+95} L{x+38},{y+145}" stroke="{theme.text_color}" stroke-width="4" fill="none"/>')
            out.append(svg_text(x, y + 170, shape.text, 20, theme.text_color, "700"))
        elif isinstance(shape, Diamond):
            fill = shape.fill if theme.name == "colour" else ("#FFFFFF" if theme.background else "none")
            stroke = shape.stroke if theme.name == "colour" else theme.box_stroke
            text_color = shape.color if theme.name == "colour" else theme.text_color
            points = [
                (shape.x + shape.w / 2, shape.y),
                (shape.x + shape.w, shape.y + shape.h / 2),
                (shape.x + shape.w / 2, shape.y + shape.h),
                (shape.x, shape.y + shape.h / 2),
            ]
            point_text = " ".join(f"{x:.1f},{y:.1f}" for x, y in points)
            out.append(f'<polygon points="{point_text}" fill="{fill}" stroke="{stroke}" stroke-width="3"/>')
            out.append(svg_text(shape.x + shape.w / 2, shape.y + shape.h / 2, shape.text, 18, text_color, "700"))
        elif isinstance(shape, Arrow):
            dash = ' stroke-dasharray="8 7"' if shape.dashed else ""
            out.append(
                f'<line x1="{shape.x1}" y1="{shape.y1}" x2="{shape.x2}" y2="{shape.y2}" stroke="{theme.line_color}" stroke-width="4"{dash} marker-end="url(#arrow)"/>'
            )
            if shape.label:
                out.append(svg_text((shape.x1 + shape.x2) / 2, (shape.y1 + shape.y2) / 2 - 14, shape.label, 18, theme.text_color, "600"))
        elif isinstance(shape, Connector):
            dash = ' stroke-dasharray="8 7"' if shape.dashed else ""
            out.append(
                f'<line x1="{shape.x1}" y1="{shape.y1}" x2="{shape.x2}" y2="{shape.y2}" stroke="{theme.line_color}" stroke-width="{shape.width}"{dash}/>'
            )
            if shape.label:
                out.append(svg_text((shape.x1 + shape.x2) / 2, (shape.y1 + shape.y2) / 2 - 14, shape.label, 18, theme.text_color, "600"))
        elif isinstance(shape, Note):
            color = shape.color if theme.name == "colour" else theme.text_color
            out.append(svg_text(shape.x, shape.y, shape.text, shape.size, color, "500"))
    out.append(svg_text(w - 70, h - 45, "SERPS Architecture", 18, theme.muted_color, "500", "end"))
    out.append("</svg>")
    path.write_text("\n".join(out), encoding="utf-8")


def write_mmd(diagram: Diagram, path: Path) -> None:
    init = "%%{init: {'theme': 'base', 'themeVariables': {'primaryColor': '#DDF7F5', 'primaryBorderColor': '#0F8B8D', 'lineColor': '#7FA9B5', 'fontFamily': 'Segoe UI, Arial'}}}%%\n"
    path.write_text(init + diagram.mmd.strip() + "\n", encoding="utf-8")


def pipeline_shapes(items: list[str], x: int = 650, y: int = 190, w: int = 500, h: int = 70, gap: int = 25) -> list[Shape]:
    shapes: list[Shape] = []
    for i, item in enumerate(items):
        yy = y + i * (h + gap)
        fill = TEAL_LIGHT if i in {0, len(items) - 1} else WHITE
        shapes.append(Box(x, yy, w, h, item, fill=fill, title=i == 0))
        if i:
            shapes.append(Arrow(x + w / 2, yy - gap + 3, x + w / 2, yy - 4))
    return shapes


def grid_boxes(items: list[str], x: int, y: int, cols: int, box_w: int, box_h: int, gap_x: int, gap_y: int, fill: str = WHITE) -> list[Shape]:
    shapes: list[Shape] = []
    for i, item in enumerate(items):
        row, col = divmod(i, cols)
        shapes.append(Box(x + col * (box_w + gap_x), y + row * (box_h + gap_y), box_w, box_h, item, fill=fill))
    return shapes


def mmd_flow(title: str, items: Iterable[str]) -> str:
    nodes = list(items)
    lines = ["flowchart TD"]
    for i, item in enumerate(nodes):
        lines.append(f'  N{i}["{item}"]')
        if i:
            lines.append(f"  N{i-1} --> N{i}")
    return "\n".join(lines)


def build_diagrams() -> list[Diagram]:
    diagrams: list[Diagram] = []

    # 3.1
    dsr = ["Problem Identification", "Literature Review", "Requirements Analysis", "System Architecture", "Prototype Design"]
    shapes = pipeline_shapes(dsr, 115, 210, 430, 78, 28)
    agile = ["Sprint Planning", "Implementation", "Testing", "Sprint Review", "Refinement"]
    agile_positions = [(820, 225), (1180, 225), (1180, 455), (820, 455), (640, 340)]
    for label, (x, y) in zip(agile, agile_positions, strict=True):
        shapes.append(Box(x, y, 270, 86, label, fill=TEAL_LIGHT if label == "Sprint Planning" else WHITE))
    shapes.extend(
        [
            Arrow(545, 634, 820, 268, "prototype to sprint"),
            Arrow(1090, 268, 1180, 268),
            Arrow(1315, 311, 1315, 455),
            Arrow(1180, 498, 1090, 498),
            Arrow(820, 498, 910, 383),
            Arrow(775, 340, 820, 268),
            Box(760, 760, 620, 86, "Final Evaluation", fill=AMBER_LIGHT, title=True),
            Box(760, 900, 620, 86, "Documentation and Dissertation Evidence", fill=TEAL_LIGHT, title=True),
            Arrow(955, 541, 955, 760, "completed agile cycle"),
            Arrow(1070, 846, 1070, 900),
            Note(220, 980, "DSR establishes the research artefact; Agile controls iterative prototype implementation.", size=22),
        ]
    )
    diagrams.append(Diagram("3.1", "Hybrid Design Science Research and Agile Development Process Adopted for SERPS", "flowcharts", (1700, 1120), shapes, mmd_flow("3.1", dsr + agile + ["Final Evaluation", "Documentation and Dissertation Evidence"])))

    # 3.2
    trace = ["Stakeholder Requirements", "Functional Requirements", "Non-functional Requirements", "System Modules", "Implementation", "Testing", "Objective Verification"]
    diagrams.append(Diagram("3.2", "Requirements Traceability Model for SERPS", "architecture", (1500, 980), pipeline_shapes(trace, 500, 190, 500, 72, 28), mmd_flow("3.2", trace)))

    # 3.3 layered system architecture
    shapes = [
        Box(120, 170, 1660, 62, "Actors and Browsers: Candidate | Reviewer/Proctor | Administrator | System Administrator", fill=TEAL_LIGHT, title=True),
        Box(120, 275, 1660, 58, "Presentation Layer: candidate UI, reviewer console and administrator dashboard", fill=WHITE),
        Box(250, 385, 300, 58, "REST API", fill=AMBER_LIGHT),
        Box(800, 385, 300, 58, "WebSocket / SSE", fill=AMBER_LIGHT),
        Box(1350, 385, 300, 58, "WebRTC Boundary", fill=AMBER_LIGHT),
        Box(120, 495, 1660, 62, "FastAPI Application Services", fill=TEAL_LIGHT, title=True),
        Box(135, 615, 285, 62, "Camera Manager", fill=WHITE),
        Box(455, 615, 285, 62, "Authentication", fill=WHITE),
        Box(775, 615, 285, 62, "Candidate / Exam", fill=WHITE),
        Box(1095, 615, 285, 62, "Session Control", fill=WHITE),
        Box(1415, 615, 285, 62, "Reports / Audit", fill=WHITE),
        Box(135, 755, 285, 70, "Detection\nModules", fill=WHITE),
        Box(775, 755, 285, 70, "Evidence Service", fill=WHITE),
        Box(500, 910, 285, 78, "Structured\nEvidenceEvent", fill=AMBER_LIGHT, title=True),
        Box(850, 910, 160, 78, "CIE", fill=TEAL_LIGHT, title=True),
        Box(1070, 910, 245, 78, "Agentic Decision\nSupport", fill=TEAL_LIGHT, title=True),
        Box(1380, 910, 170, 78, "IPIME", fill=TEAL_LIGHT, title=True),
        Box(1610, 910, 220, 78, "Human\nReviewer", fill=WHITE),
        Box(1610, 1045, 220, 80, "Final Institutional\nDecision", fill=WHITE),
        Box(180, 1135, 330, 112, "PostgreSQL\nRelational persistence", fill=GREY, title=True),
        Box(650, 1135, 330, 112, "Evidence Storage\nSnapshots and artefacts", fill=GREY, title=True),
        Box(1280, 1135, 360, 112, "Documentation / Reports\nTraceable exports", fill=GREY, title=True),
    ]
    shapes.extend([
        Arrow(950, 232, 950, 275),
        Arrow(950, 333, 400, 385), Arrow(950, 333, 950, 385), Arrow(950, 333, 1500, 385),
        Arrow(400, 443, 950, 495), Arrow(950, 443, 950, 495), Arrow(1500, 443, 950, 495),
        Arrow(277, 557, 277, 615), Arrow(597, 557, 597, 615), Arrow(917, 557, 917, 615), Arrow(1237, 557, 1237, 615), Arrow(1557, 557, 1557, 615),
        Arrow(277, 677, 277, 755, "frames / health"),
        Arrow(917, 677, 917, 755),
        Arrow(277, 825, 500, 949),
        Arrow(917, 825, 642, 910, "stored event"),
        Arrow(785, 949, 850, 949), Arrow(1010, 949, 1070, 949),
        Arrow(1315, 949, 1380, 949), Arrow(1550, 949, 1610, 949),
        Arrow(1720, 988, 1720, 1045),
        Arrow(642, 988, 345, 1135, "persist", dashed=True),
        Arrow(642, 988, 815, 1135, "snapshots", dashed=True),
    ])
    diagrams.append(Diagram("3.3", "Overall System Architecture of SERPS", "architecture", (1920, 1320), shapes, "flowchart TB\n  Actors[Actors and Browsers] --> Frontend[Presentation Layer]\n  Frontend --> REST[REST API]\n  Frontend --> Realtime[WebSocket / SSE]\n  Frontend --> WebRTC[WebRTC Boundary]\n  REST --> API[FastAPI Application Services]\n  Realtime --> API\n  WebRTC --> API\n  API --> Camera[Camera Manager]\n  API --> Auth[Authentication]\n  API --> Candidate[Candidate / Exam]\n  API --> Session[Session Control]\n  API --> Reports[Reports / Audit]\n  Camera --> Detection[Detection Modules]\n  Candidate --> EvidenceService[Evidence Service]\n  EvidenceService --> Evidence[Structured EvidenceEvent]\n  Detection --> Evidence\n  Evidence --> CIE[Contextual Intelligence Engine]\n  CIE --> Agentic[Agentic Decision Support]\n  Agentic --> IPIME\n  IPIME --> Reviewer[Human Reviewer]\n  Reviewer --> Final[Final Institutional Decision]\n  Evidence -. persist .-> DB[(PostgreSQL)]\n  Evidence -. snapshots .-> Storage[Evidence Storage]\n  Reports -. exports .-> Docs[Documentation / Reports]"))

# 3.4
    stages = ["Registration", "Consent", "Device Check", "Camera Permission", "Guided Multi-angle Capture", "Image Quality Assessment", "Liveness Detection", "Embedding Generation", "Biometric Profile", "Continuous Identity Assurance"]
    shapes = pipeline_shapes(stages, 170, 180, 430, 65, 18)
    poses = ["Front", "Left", "Right", "Slight Up", "Slight Down", "Centre"]
    shapes.extend(grid_boxes(poses, 760, 420, 3, 210, 75, 30, 30, TEAL_LIGHT))
    shapes.append(Arrow(600, 544, 760, 465, "pose targets"))
    shapes.append(Box(720, 755, 790, 120, "Continuous verification compares live identity evidence with enrolled biometric profile and emits structured identity events.", fill=AMBER_LIGHT))
    diagrams.append(Diagram("3.4", "Candidate Registration, Guided Multi-angle Facial Enrolment and Continuous Identity Assurance Architecture", "architecture", (1600, 1100), shapes, mmd_flow("3.4", stages)))

    # 3.5
    shapes = [Box(575, 190, 450, 80, "Camera Manager", fill=TEAL_LIGHT, title=True)]
    controls = ["Permissions", "Discovery", "Mode Selection", "Health Monitoring", "Device Status", "EvidenceEvent Generation"]
    shapes.extend(grid_boxes(controls, 120, 330, 3, 390, 75, 45, 35))
    shapes.extend([Box(270, 620, 350, 90, "Primary Camera\nCandidate View", fill=WHITE), Box(980, 620, 350, 90, "Secondary Camera\nEnvironment View", fill=WHITE), Box(270, 790, 350, 80, "Face / Identity / Gaze", fill=TEAL_LIGHT), Box(980, 790, 350, 80, "Room / Object Context", fill=TEAL_LIGHT), Box(575, 900, 450, 80, "Structured EvidenceEvent", fill=AMBER_LIGHT)])
    for x in [315, 750, 1185]:
        shapes.append(Arrow(800, 270, x, 330))
    for x in [315, 750, 1185]:
        shapes.append(Arrow(800, 270, x, 440))
    shapes.extend([Arrow(750, 405, 445, 620), Arrow(750, 405, 1155, 620), Arrow(445, 710, 445, 790), Arrow(1155, 710, 1155, 790), Arrow(445, 870, 710, 900), Arrow(1155, 870, 890, 900)])
    diagrams.append(Diagram("3.5", "Camera and Sensor Management Architecture", "architecture", (1550, 1060), shapes, "flowchart TB\n  Manager[Camera Manager] --> Permissions\n  Manager --> Discovery\n  Manager --> Modes[Mode Selection]\n  Manager --> Health[Health Monitoring]\n  Manager --> Primary[Primary Camera]\n  Manager --> Secondary[Secondary Camera]\n  Primary --> Evidence[EvidenceEvent]\n  Secondary --> Evidence"))

    # 3.6
    sources = ["Face", "Gaze", "Head Pose", "Audio", "Browser", "Object Detection", "Room Monitoring", "System Health"]
    shapes = grid_boxes(sources, 120, 210, 4, 300, 78, 45, 40, WHITE)
    shapes.append(Box(475, 560, 600, 90, "Evidence Standardisation", fill=TEAL_LIGHT, title=True))
    shapes.append(Box(540, 760, 470, 85, "Structured EvidenceEvent", fill=AMBER_LIGHT, title=True))
    for i in range(8):
        row, col = divmod(i, 4)
        shapes.append(Arrow(270 + col * 345, 288 + row * 118, 775, 560))
    shapes.append(Arrow(775, 650, 775, 760))
    diagrams.append(Diagram("3.6", "Multimodal Evidence Acquisition Architecture", "architecture", (1550, 950), shapes, "flowchart TB\n  Face --> Std[Evidence Standardisation]\n  Gaze --> Std\n  HeadPose --> Std\n  Audio --> Std\n  Browser --> Std\n  Objects --> Std\n  Room --> Std\n  Health --> Std\n  Std --> EvidenceEvent"))

    # 3.7 hero CIE
    shapes = [
        Box(120, 250, 300, 85, "EvidenceEvent", fill=AMBER_LIGHT, title=True),
        Box(520, 250, 360, 85, "Event Fusion Module", fill=TEAL_LIGHT, title=True),
        Box(980, 250, 360, 85, "Temporal Behaviour Memory", fill=WHITE, title=True),
        Box(520, 480, 360, 85, "Contextual Reasoning Module", fill=TEAL_LIGHT, title=True),
        Box(150, 690, 360, 85, "Risk Scoring Engine", fill=WHITE, title=True),
        Box(610, 690, 360, 85, "Explainability Interface", fill=WHITE, title=True),
        Box(1070, 690, 360, 85, "Contextual Assessment", fill=AMBER_LIGHT, title=True),
    ]
    shapes.extend([Arrow(420, 292, 520, 292), Arrow(880, 292, 980, 292), Arrow(1160, 335, 720, 480), Arrow(700, 335, 700, 480), Arrow(700, 565, 330, 690), Arrow(700, 565, 790, 690), Arrow(970, 732, 1070, 732), Arrow(510, 732, 610, 732)])
    diagrams.append(Diagram("3.7", "Internal Architecture of the Contextual Intelligence Engine", "architecture", (1550, 900), shapes, "flowchart LR\n  EvidenceEvent --> Fusion[Event Fusion Module]\n  Fusion --> Memory[Temporal Behaviour Memory]\n  Memory --> Reasoning[Contextual Reasoning Module]\n  Reasoning --> Risk[Risk Scoring Engine]\n  Reasoning --> Explain[Explainability Interface]\n  Risk <--> Explain\n  Explain --> Assessment[Contextual Assessment]\n  Risk --> Assessment"))

    # 3.8
    shapes = [Box(560, 170, 440, 80, "Contextual Assessment", fill=AMBER_LIGHT, title=True), Box(560, 310, 440, 80, "Agentic Reasoning", fill=TEAL_LIGHT, title=True), Box(560, 455, 440, 70, "Recommendation Selection", fill=TEAL_LIGHT, title=True)]
    rec = ["Continue Monitoring", "Request Re-authentication", "Notify Reviewer", "Escalate Incident"]
    shapes.extend(grid_boxes(rec, 150, 610, 4, 290, 85, 45, 20, WHITE))
    shapes.append(Box(560, 780, 440, 80, "Advisory Recommendation\nNot a final decision", fill=AMBER_LIGHT, title=True))
    shapes.extend([Arrow(780, 250, 780, 310), Arrow(780, 390, 780, 455), Arrow(780, 525, 780, 560)])
    shapes.append(Connector(295, 560, 1295, 560))
    for i in range(4):
        x = 295 + i * 335
        shapes.append(Arrow(x, 560, x, 610))
    for i in range(4):
        shapes.append(Arrow(295 + i * 335, 695, 780, 780))
    diagrams.append(Diagram("3.8", "Agentic Decision Support Architecture", "architecture", (1500, 960), shapes, "flowchart TB\n  Assessment --> Agentic[Agentic Reasoning]\n  Agentic --> Selection[Recommendation Selection]\n  Selection --> Continue[Continue Monitoring]\n  Selection --> Reauth[Request Re-authentication]\n  Selection --> Notify[Notify Reviewer]\n  Selection --> Escalate[Escalate Incident]\n  Continue --> Recommendation[Advisory Recommendation: not final]\n  Reauth --> Recommendation\n  Notify --> Recommendation\n  Escalate --> Recommendation"))

    # 3.9
    shapes = [
        Box(90, 190, 330, 90, "Agentic Recommendation", fill=AMBER_LIGHT, title=True),
        Box(520, 190, 330, 90, "Policy Evaluation", fill=TEAL_LIGHT, title=True),
        Box(950, 190, 330, 90, "Institutional Rules", fill=WHITE, title=True),
        Box(520, 335, 330, 90, "Policy Action Selection", fill=TEAL_LIGHT, title=True),
        Box(520, 650, 330, 78, "Policy Actions Executed", fill=TEAL_LIGHT, title=True),
    ]
    actions = ["Warning", "Pause Examination", "Screen Shield", "Candidate Acknowledgement", "Reviewer Notification", "Escalation"]
    shapes.extend(grid_boxes(actions, 70, 470, 6, 190, 75, 35, 0, WHITE))
    shapes.extend(
        [
            Box(150, 805, 330, 82, "Incident Record", fill=AMBER_LIGHT, title=True),
            Box(575, 805, 330, 82, "Audit Log", fill=AMBER_LIGHT, title=True),
            Box(1000, 805, 330, 82, "Reviewer Workflow", fill=AMBER_LIGHT, title=True),
        ]
    )
    shapes.extend([Arrow(420, 235, 520, 235), Arrow(850, 235, 950, 235), Arrow(685, 280, 685, 335), Arrow(1115, 280, 850, 380)])
    for i in range(6):
        sx = 165 + i * 225
        shapes.append(Arrow(685, 425, sx, 470))
        shapes.append(Arrow(sx, 545, 685, 650))
    shapes.extend([Arrow(685, 728, 315, 805), Arrow(685, 728, 740, 805), Arrow(685, 728, 1165, 805)])
    diagrams.append(Diagram("3.9", "Institutional Policy and Incident Management Engine", "architecture", (1480, 940), shapes, "flowchart TB\n  Recommendation --> Evaluation[Policy Evaluation]\n  Rules[Institutional Rules] --> Evaluation\n  Evaluation --> Selection[Policy Action Selection]\n  Selection --> Warning\n  Selection --> Pause[Pause Examination]\n  Selection --> Shield[Screen Shield]\n  Selection --> Ack[Candidate Acknowledgement]\n  Selection --> Notify[Reviewer Notification]\n  Selection --> Escalation\n  Warning --> Incident[Incident Record]\n  Pause --> Incident\n  Shield --> Incident\n  Ack --> Incident\n  Notify --> Audit[Audit Log]\n  Escalation --> Reviewer[Reviewer Workflow]\n  Incident --> Reviewer\n  Audit --> Reviewer"))

    # 3.10
    pipeline = ["Detection", "Structured EvidenceEvent", "Contextual Intelligence Engine", "Agentic Recommendation", "Institutional Policy", "Candidate Acknowledgement\n(where required)", "Human Reviewer", "Final Institutional Decision", "Audit"]
    shapes = pipeline_shapes(pipeline, 515, 180, 520, 70, 20)
    shapes.append(Box(1060, 650, 390, 190, "Human Governance Boundary:\nSERPS supports review but does not make automatic misconduct decisions.", fill=AMBER_LIGHT))
    shapes.append(Arrow(1035, 740, 1060, 745, dashed=True))
    diagrams.append(Diagram("3.10", "Governance-aware Decision Pipeline", "flowcharts", (1500, 1100), shapes, mmd_flow("3.10", pipeline)))

    # 3.11
    shapes = [
        Box(100, 250, 400, 430, "Mode A\nSingle-camera CBT mode\n\nPrimary camera required\nSecondary camera not required\nSuitable for controlled CBT centres", fill=TEAL_LIGHT, title=True),
        Box(575, 250, 400, 430, "Mode B\nDual-camera full proctoring mode\n\nPrimary camera required\nSecondary camera required\nProvides candidate and room coverage", fill=WHITE, title=True),
        Box(1050, 250, 400, 430, "Mode C\nMirror-assisted low-resource mode\n\nPrimary camera required\nMirror or reflective aid required\nSecondary camera not required", fill=TEAL_LIGHT, title=True),
    ]
    diagrams.append(Diagram("3.11", "Deployment Modes Supported by SERPS", "architecture", (1550, 820), shapes, "flowchart LR\n  A[Mode A: Primary Camera] --- B[Mode B: Primary + Secondary]\n  B --- C[Mode C: Primary + Mirror]"))

    # 3.12
    shapes = [Box(100, 250, 280, 75, "Camera / Audio / Browser", fill=WHITE), Box(470, 250, 280, 75, "Detection Modules", fill=WHITE), Box(840, 250, 280, 75, "EvidenceEvent", fill=AMBER_LIGHT, title=True), Box(1220, 220, 280, 75, "Contextual Intelligence", fill=TEAL_LIGHT), Box(1220, 390, 280, 75, "PostgreSQL\nPersistence", fill=GREY), Box(840, 585, 280, 75, "Reports and Audit", fill=WHITE), Box(1220, 585, 280, 75, "Reviewer Console", fill=WHITE)]
    shapes.extend([Arrow(380, 287, 470, 287), Arrow(750, 287, 840, 287), Arrow(1120, 270, 1220, 257), Arrow(1120, 305, 1220, 427), Arrow(1360, 465, 980, 585, "read", dashed=True), Arrow(1120, 625, 1220, 625)])
    diagrams.append(Diagram("3.12", "High-Level Data Flow within SERPS", "flowcharts", (1600, 780), shapes, "flowchart LR\n  Sources --> Detection --> EvidenceEvent\n  EvidenceEvent --> CIE\n  EvidenceEvent -. persists .-> DB[(PostgreSQL)]\n  DB -. read .-> Reports\n  Reports --> Reviewer"))

    # 3.13 use case
    shapes = [
        Box(330, 180, 1570, 1220, "", fill="#F8FBFC", stroke=LINE, dashed=True),
        Actor(150, 600, "Candidate"),
        Actor(150, 1110, "Administrator"),
        Actor(2070, 565, "Reviewer/Proctor"),
        Actor(2070, 1130, "System\nAdministrator"),
        Box(430, 245, 350, 805, "", fill=WHITE),
        Box(790, 780, 350, 520, "", fill=WHITE),
        Box(1220, 245, 360, 555, "", fill=WHITE),
        Box(1220, 910, 360, 395, "", fill=WHITE),
        Note(475, 270, "Candidate and Examination", size=26, color=DEEP_NAVY),
        Note(875, 805, "Administration", size=26, color=DEEP_NAVY),
        Note(1260, 270, "Review and Incident", size=26, color=DEEP_NAVY),
        Note(1265, 935, "System Administration", size=26, color=DEEP_NAVY),
    ]
    use_cases = [
        (500, 350, "Register"), (500, 440, "Give\nConsent"), (500, 530, "Enrol\nBiometrics"), (500, 620, "Authenticate"),
        (500, 710, "Perform\nDevice Check"), (500, 800, "Take\nExamination"), (500, 890, "Receive\nWarning"), (500, 980, "Submit\nAcknowledgement"),
        (860, 875, "Manage\nCandidates"), (860, 965, "Assign\nCandidates"), (860, 1055, "Manage\nExams"), (860, 1145, "Configure\nPolicies"), (860, 1235, "Generate\nReports"),
        (1295, 350, "Monitor\nAssigned\nSessions"), (1295, 455, "View\nEvidence"), (1295, 560, "Review\nIncident"), (1295, 665, "Record\nReviewer\nDecision"), (1295, 745, "Request\nRe-authentication"),
        (1295, 995, "Manage Users\nand Roles"), (1295, 1085, "Manage\nInstitutions"), (1295, 1175, "Monitor\nSystem Health"), (1295, 1265, "Inspect\nAudit Logs"),
    ]
    for x, y, label in use_cases:
        shapes.append(Ellipse(x, y, 220, 82, label, fill=AMBER_LIGHT if label in {"Take\nExamination", "Review\nIncident"} else WHITE))
    shapes.extend([
        Connector(260, 600, 500, 391, width=2), Connector(260, 600, 500, 481, width=2), Connector(260, 600, 500, 571, width=2), Connector(260, 600, 500, 661, width=2),
        Connector(260, 600, 500, 751, width=2), Connector(260, 600, 500, 841, width=2), Connector(260, 600, 500, 931, width=2), Connector(260, 600, 500, 1021, width=2),
        Connector(260, 1110, 860, 916, width=2), Connector(260, 1110, 860, 1006, width=2), Connector(260, 1110, 860, 1096, width=2), Connector(260, 1110, 860, 1186, width=2), Connector(260, 1110, 860, 1276, width=2),
        Connector(2070, 565, 1515, 391, width=2), Connector(2070, 565, 1515, 496, width=2), Connector(2070, 565, 1515, 601, width=2), Connector(2070, 565, 1515, 706, width=2), Connector(2070, 565, 1515, 786, width=2),
        Connector(2070, 1130, 1515, 1036, width=2), Connector(2070, 1130, 1515, 1126, width=2), Connector(2070, 1130, 1515, 1216, width=2), Connector(2070, 1130, 1515, 1306, width=2),
    ])
    shapes.append(Note(470, 1440, "Use cases describe user goals and responsibilities. Institutional policy and reviewer decisions remain human-governed; SERPS does not issue automatic misconduct decisions.", size=22, color=MUTED))
    diagrams.append(Diagram("3.13", "Use Case Diagram of SERPS", "uml", (2200, 1530), shapes, "flowchart LR\n  Candidate((Candidate)) --- Register((Register))\n  Candidate --- Consent((Give Consent))\n  Candidate --- Biometrics((Enrol Biometrics))\n  Candidate --- Authenticate((Authenticate))\n  Candidate --- Device((Perform Device Check))\n  Candidate --- Exam((Take Examination))\n  Candidate --- Warning((Receive Warning))\n  Candidate --- Ack((Submit Acknowledgement))\n  Administrator((Administrator)) --- ManageCandidates((Manage Candidates))\n  Administrator --- AssignCandidates((Assign Candidates))\n  Administrator --- ManageExams((Manage Examinations))\n  Administrator --- ConfigurePolicies((Configure Policies))\n  Administrator --- Reports((Generate Reports))\n  Reviewer((Reviewer/Proctor)) --- Monitor((Monitor Assigned Sessions))\n  Reviewer --- Evidence((View Evidence))\n  Reviewer --- ReviewIncident((Review Incident))\n  Reviewer --- RecordDecision((Record Reviewer Decision))\n  Reviewer --- Reauth((Request Re-authentication))\n  SysAdmin((System Administrator)) --- Users((Manage Users and Roles))\n  SysAdmin --- Institutions((Manage Institutions))\n  SysAdmin --- Health((Monitor System Health))\n  SysAdmin --- Audit((Inspect Audit Logs))"))

# 3.14 activity
    shapes = [
        Ellipse(685, 180, 190, 60, "Start", fill=DEEP_NAVY, stroke=DEEP_NAVY, color=WHITE),
        Box(535, 275, 490, 64, "Register / Authenticate Candidate", fill=WHITE),
        Box(535, 370, 490, 64, "Select Monitoring Mode and Run Device Checks", fill=WHITE),
        Box(535, 465, 490, 64, "Start Examination Session", fill=TEAL_LIGHT),
        Box(535, 560, 490, 64, "Generate Structured Evidence Events", fill=WHITE),
        Box(535, 655, 490, 64, "CIE Contextual Assessment", fill=TEAL_LIGHT),
        Box(535, 750, 490, 64, "Agentic Recommendation", fill=WHITE),
        Box(535, 845, 490, 64, "IPIME Policy Evaluation", fill=TEAL_LIGHT),
        Diamond(620, 955, 320, 130, "Acknowledgement Required?"),
        Box(125, 990, 380, 70, "No: Continue Monitoring / Examination Flow", fill=TEAL_LIGHT),
        Box(1065, 990, 380, 70, "Yes: Candidate Incident Acknowledgement", fill=AMBER_LIGHT),
        Box(1065, 1110, 380, 70, "Human Reviewer Inspects Evidence", fill=WHITE),
        Box(535, 1230, 490, 64, "Final Institutional Decision and Audit Report", fill=AMBER_LIGHT),
        Ellipse(685, 1335, 190, 60, "End", fill=DEEP_NAVY, stroke=DEEP_NAVY, color=WHITE),
    ]
    for y1, y2 in [(240, 275), (339, 370), (434, 465), (529, 560), (624, 655), (719, 750), (814, 845), (909, 955)]:
        shapes.append(Arrow(780, y1, 780, y2))
    shapes.extend(
        [
            Arrow(620, 1020, 505, 1025, "No"),
            Arrow(940, 1020, 1065, 1025, "Yes"),
            Arrow(1255, 1060, 1255, 1110),
            Arrow(1255, 1180, 780, 1230),
            Arrow(315, 1060, 780, 1230),
            Arrow(780, 1294, 780, 1335),
        ]
    )
    diagrams.append(Diagram("3.14", "Activity Diagram of SERPS", "uml", (1560, 1440), shapes, "flowchart TD\n  Start((Start)) --> Auth[Register / Authenticate Candidate]\n  Auth --> Device[Select Monitoring Mode and Run Device Checks]\n  Device --> Exam[Start Examination Session]\n  Exam --> Evidence[Generate Structured Evidence Events]\n  Evidence --> CIE[CIE Contextual Assessment]\n  CIE --> Agentic[Agentic Recommendation]\n  Agentic --> IPIME[IPIME Policy Evaluation]\n  IPIME --> Decision{Acknowledgement Required?}\n  Decision -- No --> Continue[Continue Monitoring / Examination Flow]\n  Decision -- Yes --> Ack[Candidate Incident Acknowledgement]\n  Ack --> Review[Human Reviewer Inspects Evidence]\n  Continue --> Final[Final Institutional Decision and Audit Report]\n  Review --> Final\n  Final --> End((End))"))

    # 3.15 sequence
    participants = ["Candidate", "React\nFrontend", "FastAPI", "Authentication", "Camera\nManager", "Evidence\nServices", "CIE", "Agentic", "IPIME", "Reviewer", "PostgreSQL"]
    x_positions = [165 + i * 300 for i in range(len(participants))]
    shapes = []
    top_y = 195
    bottom_y = 1950
    for p, x in zip(participants, x_positions, strict=True):
        shapes.append(Box(x - 95, top_y, 190, 72, p, fill=TEAL_LIGHT if p in {"CIE", "IPIME"} else WHITE))
        shapes.append(Connector(x, top_y + 72, x, bottom_y, dashed=True, width=3))
    activations = {
        1: (330, 705), 2: (420, 1650), 3: (510, 680), 4: (880, 1040), 5: (960, 1260),
        6: (1210, 1460), 7: (1290, 1500), 8: (1370, 1550), 9: (1450, 1630), 10: (565, 1660),
    }
    for idx, (y1, y2) in activations.items():
        x = x_positions[idx]
        shapes.append(Box(x - 8, y1, 16, y2 - y1, "", fill=TEAL_LIGHT if participants[idx] in {"CIE", "IPIME"} else WHITE, radius=4))
    messages = [
        (0, 1, 320, "Submit credentials"),
        (1, 2, 410, "POST /auth/login"),
        (2, 3, 500, "Validate credentials"),
        (3, 10, 590, "Read user and roles"),
        (10, 3, 680, "User and role data"),
        (3, 2, 770, "Issue access / refresh tokens"),
        (2, 1, 860, "Authentication response"),
        (0, 1, 980, "Start examination"),
        (1, 2, 1070, "Create examination session"),
        (2, 4, 1160, "Initialise authorised devices"),
        (4, 5, 1250, "Stream-health EvidenceEvent"),
        (5, 10, 1340, "Persist raw EvidenceEvent"),
        (5, 6, 1430, "Submit structured event"),
        (6, 7, 1520, "Contextual assessment"),
        (7, 8, 1610, "Advisory recommendation"),
        (8, 9, 1700, "Policy response and notification"),
        (9, 2, 1790, "Record reviewer action"),
        (2, 10, 1880, "Persist decision and audit trail"),
    ]
    for a, b, y, label in messages:
        if b > a:
            shapes.append(Arrow(x_positions[a] + 18, y, x_positions[b] - 18, y, label))
        else:
            shapes.append(Arrow(x_positions[a] - 18, y, x_positions[b] + 18, y, label))
    shapes.append(Box(1865, 1490, 760, 270, "opt Contextual concern detected\nCIE assesses evidence in a temporal window.\nAgentic support recommends action.\nIPIME applies institutional workflow.\nHuman reviewer remains responsible for final decision.", fill="#F8FBFC", stroke=LINE, dashed=True))
    diagrams.append(Diagram("3.15", "Sequence Diagram of SERPS", "uml", (3460, 2060), shapes, "sequenceDiagram\n  participant Candidate\n  participant React as React Frontend\n  participant FastAPI\n  participant Auth as Authentication\n  participant Camera as Camera Manager\n  participant Evidence as Evidence Services\n  participant CIE\n  participant Agentic as Agentic Support\n  participant IPIME\n  participant Reviewer\n  participant PostgreSQL\n  Candidate->>React: Submit credentials\n  React->>FastAPI: POST /auth/login\n  FastAPI->>Auth: Validate credentials\n  Auth->>PostgreSQL: Read user and roles\n  PostgreSQL-->>Auth: User and role data\n  Auth-->>FastAPI: Issue access/refresh tokens\n  FastAPI-->>React: Authentication response\n  Candidate->>React: Start examination\n  React->>FastAPI: Create examination session\n  FastAPI->>Camera: Initialise authorised devices\n  Camera->>Evidence: Stream-health EvidenceEvent\n  Evidence->>PostgreSQL: Persist raw EvidenceEvent\n  Evidence->>CIE: Submit structured event\n  opt Incident detected\n    CIE->>Agentic: Contextual assessment\n    Agentic->>IPIME: Advisory recommendation\n    IPIME->>Reviewer: Policy response and notification\n    Reviewer->>FastAPI: Record human action\n    FastAPI->>PostgreSQL: Persist decision and audit trail\n  end"))

    # 3.16 class
    class_boxes = {
        "Institution": Box(95, 190, 310, 140, "Institution\ninstitution_id\nname\ncreated_at", fill=TEAL_LIGHT, title=True),
        "StaffUser": Box(575, 190, 310, 140, "StaffUser\nuser_id\ninstitution_id\nemail\nstatus", fill=WHITE, title=True),
        "UserRole": Box(1055, 190, 310, 140, "UserRole\nuser_id\nrole_id", fill=WHITE, title=True),
        "Role": Box(1535, 190, 310, 140, "Role\nrole_id\nname", fill=WHITE, title=True),
        "Candidate": Box(95, 470, 310, 150, "Candidate\ncandidate_id\ninstitution_id\nstudent/candidate_ref\nemail", fill=WHITE, title=True),
        "Assignment": Box(575, 470, 310, 150, "CandidateExam\nAssignment\nassignment_id\ncandidate_id\nexamination_id\nstatus", fill=WHITE, title=True),
        "Examination": Box(1055, 470, 310, 150, "Examination\nexamination_id\ninstitution_id\ntitle\nstatus", fill=WHITE, title=True),
        "Session": Box(1535, 470, 310, 150, "ExaminationSession\nsession_id\nassignment_id\nstatus\nmonitoring_mode", fill=WHITE, title=True),
        "Evidence": Box(95, 760, 310, 150, "EvidenceEvent\nevent_id\nsession_id\nevent_type\nconfidence", fill=AMBER_LIGHT, title=True),
        "Assessment": Box(575, 760, 310, 150, "ContextualAssessment\nassessment_id\nrisk_score\nrisk_level\nexplanation", fill=TEAL_LIGHT, title=True),
        "Recommendation": Box(1055, 760, 310, 150, "Recommendation\nrecommendation_id\naction\nrationale", fill=TEAL_LIGHT, title=True),
        "PolicyRule": Box(1535, 760, 310, 150, "PolicyRule\npolicy_id\ncondition\naction", fill=WHITE, title=True),
        "Incident": Box(95, 1050, 310, 150, "Incident\nincident_id\nalert_id\npolicy_response\nstatus", fill=AMBER_LIGHT, title=True),
        "Acknowledgement": Box(575, 1050, 310, 150, "Acknowledgement\nack_id\nincident_id\ncandidate_statement\nsigned_at", fill=WHITE, title=True),
        "ReviewerAction": Box(1055, 1050, 310, 150, "ReviewerAction\naction_id\nincident_id\ndecision\nrationale", fill=WHITE, title=True),
        "AuditLog": Box(1535, 1050, 310, 150, "AuditLog\naudit_id\naction\ntimestamp", fill=WHITE, title=True),
    }
    shapes = list(class_boxes.values())
    def edge(name: str, side: str) -> tuple[float, float]:
        box = class_boxes[name]
        if side == "r":
            return box.x + box.w, box.y + box.h / 2
        if side == "l":
            return box.x, box.y + box.h / 2
        if side == "b":
            return box.x + box.w / 2, box.y + box.h
        return box.x + box.w / 2, box.y
    rels = [
        ("Institution", "r", "StaffUser", "l", "1 to many"),
        ("StaffUser", "r", "UserRole", "l", "1 to many"),
        ("UserRole", "r", "Role", "l", "many to 1"),
        ("Institution", "b", "Candidate", "t", "1 to many"),
        ("Candidate", "r", "Assignment", "l", "1 to many"),
        ("Assignment", "r", "Examination", "l", "many to 1"),
        ("Assignment", "r", "Session", "l", "1 to many"),
        ("Session", "b", "Evidence", "t", "records"),
        ("Session", "b", "Assessment", "t", "assessed by"),
        ("Assessment", "r", "Recommendation", "l", "1 to many"),
        ("Recommendation", "r", "Incident", "l", "0 to 1"),
        ("PolicyRule", "b", "Incident", "t", "governs"),
        ("Incident", "r", "Acknowledgement", "l", "0 to 1"),
        ("Incident", "r", "ReviewerAction", "l", "1 to many"),
        ("ReviewerAction", "r", "AuditLog", "l", "records"),
    ]
    for a, aside, b, bside, label in rels:
        shapes.append(Connector(*edge(a, aside), *edge(b, bside), label=label))
    shapes.append(Note(95, 1255, "The class diagram summarises implementation and governance domain classes. Detection modules emit EvidenceEvents; CIE/IPIME support human review rather than final misconduct decisions.", size=22, color=MUTED))
    diagrams.append(Diagram("3.16", "Class Diagram of SERPS", "uml", (1940, 1360), shapes, "classDiagram\n  class Institution {+institution_id +name +created_at}\n  class StaffUser {+user_id +email +status}\n  class Role {+role_id +name}\n  class UserRole {+user_id +role_id}\n  class Candidate {+candidate_id +institution_reference +email}\n  class Examination {+examination_id +title +status}\n  class CandidateExaminationAssignment {+assignment_id +status}\n  class ExaminationSession {+session_id +status +monitoring_mode}\n  class EvidenceEvent {+event_id +event_type +confidence}\n  class ContextualAssessment {+risk_score +risk_level +explanation}\n  class Recommendation {+action +rationale}\n  class PolicyRule {+condition +action}\n  class Incident {+policy_response +status}\n  class Acknowledgement {+candidate_statement +signed_at}\n  class ReviewerAction {+decision +rationale}\n  class AuditLog {+action +timestamp}\n  Institution \"1\" -- \"0..*\" StaffUser\n  StaffUser \"1\" -- \"0..*\" UserRole\n  Role \"1\" -- \"0..*\" UserRole\n  Institution \"1\" -- \"0..*\" Candidate\n  Candidate \"1\" -- \"0..*\" CandidateExaminationAssignment\n  Examination \"1\" -- \"0..*\" CandidateExaminationAssignment\n  CandidateExaminationAssignment \"1\" -- \"0..*\" ExaminationSession\n  ExaminationSession \"1\" -- \"0..*\" EvidenceEvent\n  EvidenceEvent \"0..*\" -- \"0..*\" ContextualAssessment\n  ContextualAssessment \"1\" -- \"0..*\" Recommendation\n  PolicyRule \"0..*\" -- \"0..*\" Incident\n  Incident \"1\" -- \"0..1\" Acknowledgement\n  Incident \"1\" -- \"0..*\" ReviewerAction\n  ReviewerAction \"1\" -- \"0..*\" AuditLog"))

    # 3.17 component
    shapes = [
        Box(585, 80, 430, 72, 'Next.js Frontend', fill=TEAL_LIGHT, title=True),
        Box(585, 190, 430, 72, 'FastAPI API Boundary', fill=AMBER_LIGHT, title=True),
        Note(120, 330, 'Application Services', size=22, color=DEEP_NAVY),
        Box(95, 375, 240, 64, 'Authentication', fill=WHITE),
        Box(385, 375, 240, 64, 'Candidate', fill=WHITE),
        Box(675, 375, 240, 64, 'Examination', fill=WHITE),
        Box(965, 375, 240, 64, 'Session', fill=WHITE),
        Box(1255, 375, 240, 64, 'Camera', fill=WHITE),
        Note(120, 520, 'Detection and Evidence Services', size=22, color=DEEP_NAVY),
        Box(95, 570, 300, 70, 'Vision Detection', fill=WHITE),
        Box(455, 570, 300, 70, 'Audio Detection', fill=WHITE),
        Box(815, 570, 300, 70, 'Identity Signals', fill=WHITE),
        Box(1175, 570, 300, 70, 'Evidence Service', fill=AMBER_LIGHT),
        Note(120, 725, 'Reasoning and Governance', size=22, color=DEEP_NAVY),
        Box(160, 775, 390, 120, 'Contextual Intelligence\nEngine (CIE)', fill=TEAL_LIGHT, title=True),
        Box(605, 775, 390, 120, 'Agentic Decision\nSupport', fill=TEAL_LIGHT, title=True),
        Box(1050, 775, 390, 120, 'IPIME', fill=TEAL_LIGHT, title=True),
        Note(120, 970, 'Persistence and Outputs', size=22, color=DEEP_NAVY),
        Box(100, 1020, 290, 66, 'PostgreSQL', fill=GREY),
        Box(450, 1020, 290, 66, 'Evidence Storage', fill=GREY),
        Box(800, 1020, 290, 66, 'Reporting', fill=GREY),
        Box(1150, 1020, 290, 66, 'Audit', fill=GREY),
        Note(650, 1135, 'Detection emits structured evidence; CIE reasons; Agentic and IPIME remain advisory before human review.', size=18, color=MUTED),
    ]
    shapes.extend([
        Arrow(800, 152, 800, 190),
        Arrow(800, 262, 800, 350),
        Arrow(800, 262, 215, 375), Arrow(800, 262, 505, 375), Arrow(800, 262, 795, 375), Arrow(800, 262, 1085, 375), Arrow(800, 262, 1375, 375),
        Arrow(1375, 439, 245, 570), Arrow(1375, 439, 605, 570), Arrow(1375, 439, 965, 570),
        Arrow(245, 640, 1325, 570), Arrow(605, 640, 1325, 570), Arrow(965, 640, 1325, 570),
        Arrow(1325, 640, 355, 775),
        Arrow(550, 835, 605, 835),
        Arrow(995, 835, 1050, 835),
        Arrow(1325, 640, 245, 1020, dashed=True),
        Arrow(1325, 640, 595, 1020, dashed=True),
        Arrow(1245, 895, 945, 1020),
        Arrow(1245, 895, 1295, 1020),
    ])
    diagrams.append(Diagram('3.17', 'Component Diagram of SERPS', 'uml', (1600, 1260), shapes, 'flowchart TB\n  Web[Next.js Frontend] --> API[FastAPI API Boundary]\n  API --> Auth[Authentication]\n  API --> Candidate[Candidate]\n  API --> Exam[Examination]\n  API --> Session[Session]\n  API --> Camera[Camera]\n  Camera --> Vision[Vision Detection]\n  Camera --> Audio[Audio Detection]\n  Camera --> Identity[Identity Signals]\n  Vision --> Evidence[Evidence Service]\n  Audio --> Evidence\n  Identity --> Evidence\n  Evidence --> CIE[Contextual Intelligence Engine]\n  CIE --> Agentic[Agentic Decision Support]\n  Agentic --> IPIME[IPIME]\n  IPIME --> Reporting\n  IPIME --> Audit\n  Evidence -.-> PostgreSQL\n  Evidence -.-> Storage[Evidence Storage]'))

    # 3.18 deployment
    shapes = [
        Box(560, 150, 1120, 760, "SERPS Containerised Deployment Environment", fill="#F8FBFC", stroke=LINE, dashed=True),
        Box(85, 250, 370, 130, "<<device>>\nCandidate Device\nBrowser + Camera / Mic", fill=WHITE, title=True),
        Box(85, 485, 370, 120, "<<device>>\nReviewer Device\nBrowser Console", fill=WHITE, title=True),
        Box(85, 700, 370, 120, "<<device>>\nAdministrator Device\nDashboard", fill=WHITE, title=True),
        Box(640, 265, 365, 125, "<<container>>\nNext.js Web App\nCandidate / Reviewer UI", fill=TEAL_LIGHT, title=True),
        Box(1210, 265, 365, 125, "<<container>>\nFastAPI API\nService Boundary", fill=AMBER_LIGHT, title=True),
        Box(1210, 520, 365, 145, "<<service>>\nAI Monitoring Services\nOpenCV / MediaPipe / YOLO", fill=WHITE, title=True),
        Box(640, 720, 365, 120, "<<database>>\nPostgreSQL\nRelational Persistence", fill=GREY, title=True),
        Box(1210, 720, 365, 120, "<<storage>>\nEvidence Storage\nSnapshots", fill=GREY, title=True),
        Box(690, 930, 480, 58, "Optional edge/cloud execution boundary for production hardening", fill=WHITE, stroke=LINE, dashed=True),
    ]
    shapes.extend([
        Arrow(455, 315, 640, 315, "HTTPS"),
        Arrow(455, 545, 640, 335, "HTTPS"),
        Arrow(455, 760, 640, 355, "HTTPS"),
        Arrow(1005, 327, 1210, 327, "REST"),
        Arrow(825, 390, 1210, 575, "WebRTC media", dashed=True),
        Arrow(1392, 390, 1392, 520, "WebSocket / SSE"),
        Arrow(1392, 390, 825, 720, "SQL"),
        Arrow(1320, 665, 900, 720, "event metadata", dashed=True),
        Arrow(1392, 665, 1392, 720, "snapshots"),
    ])
    diagrams.append(Diagram("3.18", "Deployment Diagram of SERPS", "uml", (1760, 1010), shapes, "flowchart LR\n  CandidateDevice[<<device>> Candidate Device Browser + Camera/Mic] -->|HTTPS| Web[<<container>> Next.js Web App]\n  ReviewerDevice[<<device>> Reviewer Device Browser Console] -->|HTTPS| Web\n  AdminDevice[<<device>> Administrator Device Dashboard] -->|HTTPS| Web\n  Web -->|REST| API[<<container>> FastAPI API]\n  Web -. WebRTC media .-> AI[<<service>> AI Monitoring Services]\n  API <--> |WebSocket / SSE| AI\n  API -->|SQL| DB[(<<database>> PostgreSQL)]\n  AI -->|snapshots| Storage[<<storage>> Evidence Storage]\n  AI -. event metadata .-> DB"))

    # 3.19 logical ERD for dissertation presentation. The full SQLAlchemy schema is exported separately.
    shapes = [
        Box(660, 190, 380, 125, "Institution\ninstitution_id (PK)\nname\ncreated_at", fill=TEAL_LIGHT, title=True),
        Box(90, 405, 330, 150, "Candidate\ncandidate_id (PK)\ninstitution_id (FK)\nemail\nstatus", fill=WHITE, title=True),
        Box(490, 405, 330, 150, "Examination\nexamination_id (PK)\ninstitution_id (FK)\ntitle\nstatus", fill=WHITE, title=True),
        Box(890, 405, 330, 150, "StaffUser\nuser_id (PK)\ninstitution_id (FK)\nemail\nstatus", fill=WHITE, title=True),
        Box(1290, 405, 330, 150, "Role\nrole_id (PK)\nname", fill=WHITE, title=True),
        Box(90, 675, 350, 165, "CandidateExam\nAssignment\nassignment_id (PK)\ncandidate_id (FK)\nexamination_id (FK)\nstatus", fill=WHITE, title=True),
        Box(490, 675, 350, 155, "ExaminationSession\nsession_id (PK)\nassignment_id (FK)\nmonitoring_mode\nstatus", fill=TEAL_LIGHT, title=True),
        Box(890, 675, 350, 155, "EvidenceEvent\nevent_id (PK)\nsession_id (FK)\nevent_type\nconfidence", fill=AMBER_LIGHT, title=True),
        Box(1290, 675, 350, 155, "UserRole\nuser_role_id (PK)\nuser_id (FK)\nrole_id (FK)", fill=WHITE, title=True),
        Box(490, 980, 350, 150, "ContextualAlert\nalert_id (PK)\nsession_id (FK)\nrisk_score\nrisk_level", fill=TEAL_LIGHT, title=True),
        Box(890, 980, 350, 150, "Incident\nincident_id (PK)\nalert_id (FK)\npolicy_response\nstatus", fill=WHITE, title=True),
        Box(1290, 980, 350, 150, "AuditLog\naudit_id (PK)\nactor_user_id (FK)\naction\ntimestamp", fill=WHITE, title=True),
        Note(90, 150, "Logical ERD derived from the implemented SERPS domain schema", size=24, color=DEEP_NAVY),
        Note(220, 1235, "Logical ERD highlights the dissertation-level persistence model. Raw evidence remains immutable; contextual alerts, incidents, and audit logs support human-governed decisions.", size=21, color=MUTED),
    ]
    shapes.extend([
        Connector(720, 315, 255, 405, "1..*"),
        Connector(805, 315, 655, 405, "1..*"),
        Connector(895, 315, 1055, 405, "1..*"),
        Connector(990, 315, 1455, 405, "1..*"),
        Connector(255, 555, 265, 675, "1..*"),
        Connector(655, 555, 265, 675, "1..*"),
        Connector(440, 757, 490, 757, "1..*"),
        Connector(840, 757, 890, 757, "1..*"),
        Connector(1065, 830, 665, 980, "correlates"),
        Connector(840, 1055, 890, 1055, "triggers"),
        Connector(1220, 1055, 1290, 1055, "records"),
        Connector(1055, 555, 1465, 980, "audits", dashed=True),
        Connector(1455, 555, 1465, 675, "1..*"),
    ])
    diagrams.append(Diagram("3.19", "Logical Entity Relationship Diagram of SERPS Database", "erd", (1760, 1400), shapes, "erDiagram\n  INSTITUTION ||--o{ CANDIDATE : owns\n  INSTITUTION ||--o{ EXAMINATION : offers\n  INSTITUTION ||--o{ STAFF_USER : employs\n  INSTITUTION ||--o{ ROLE : defines\n  STAFF_USER ||--o{ USER_ROLE : assigned\n  ROLE ||--o{ USER_ROLE : grants\n  CANDIDATE ||--o{ CANDIDATE_EXAM_ASSIGNMENT : assigned\n  EXAMINATION ||--o{ CANDIDATE_EXAM_ASSIGNMENT : includes\n  CANDIDATE_EXAM_ASSIGNMENT ||--o{ EXAMINATION_SESSION : creates\n  EXAMINATION_SESSION ||--o{ EVIDENCE_EVENT : records\n  EVIDENCE_EVENT ||--o{ CONTEXTUAL_ALERT : contextualises\n  CONTEXTUAL_ALERT ||--o{ INCIDENT : triggers\n  INCIDENT ||--o{ AUDIT_LOG : records\n  STAFF_USER ||--o{ AUDIT_LOG : performs"))

    # 3.20 API hub
    shapes = [Box(575, 180, 400, 80, "React / Next.js", fill=TEAL_LIGHT, title=True), Box(575, 330, 400, 80, "REST API / WebSocket", fill=AMBER_LIGHT), Box(575, 480, 400, 80, "FastAPI Hub", fill=TEAL_LIGHT, title=True)]
    services = ["Authentication", "Candidates", "Examinations", "Camera", "Identity", "Evidence", "CIE", "Agentic", "IPIME", "Reporting", "Audit"]
    shapes.extend(grid_boxes(services, 80, 680, 4, 315, 70, 45, 40, WHITE))
    shapes.extend([Box(1120, 470, 320, 90, "PostgreSQL", fill=GREY), Box(1120, 580, 320, 90, "Evidence Storage", fill=GREY)])
    shapes.extend([Arrow(775, 260, 775, 330), Arrow(775, 410, 775, 480), Arrow(975, 520, 1120, 515), Arrow(975, 540, 1120, 625)])
    for i in range(len(services)):
        row, col = divmod(i, 4)
        shapes.append(Arrow(775, 560, 237 + col * 360, 680 + row * 110))
    diagrams.append(Diagram("3.20", "API Interaction Diagram of SERPS", "api", (1550, 1050), shapes, "flowchart TB\n  React --> Boundary[REST API / WebSocket]\n  Boundary --> FastAPI[FastAPI Hub]\n  FastAPI --> Authentication\n  FastAPI --> Candidates\n  FastAPI --> Examinations\n  FastAPI --> Camera\n  FastAPI --> Identity\n  FastAPI --> Evidence\n  FastAPI --> CIE\n  FastAPI --> Agentic\n  FastAPI --> IPIME\n  FastAPI --> Reporting\n  FastAPI --> Audit\n  FastAPI -.-> PostgreSQL\n  FastAPI -.-> Storage[Evidence Storage]"))

    # 3.21 technology stack
    layers = [
        "Presentation\nNext.js / React / TypeScript\nImplemented foundation",
        "API / Application\nFastAPI, Pydantic\nImplemented foundation",
        "Real-time Communication\nWebSocket / SSE / WebRTC\nPlanned interfaces",
        "AI / ML\nOpenCV, MediaPipe, YOLO\nPlanned POP migration",
        "Intelligence / Governance\nCIE, Agentic, IPIME\nPOC implemented; POP migration pending",
        "Persistence\nSQLAlchemy, Alembic, PostgreSQL\nConfigured and migration-verified",
        "Infrastructure / DevOps\nDocker Compose, GitHub Actions\nImplemented foundation",
    ]
    diagrams.append(Diagram("3.21", "Technology Stack of SERPS", "technology", (1500, 1050), pipeline_shapes(layers, 440, 185, 620, 95, 25), mmd_flow("3.21", layers)))

    return diagrams


def checksum(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()[:16]


def rel(path: Path) -> str:
    return str(path.relative_to(ROOT)).replace("\\", "/")


def git_commit_hash() -> str:
    result = subprocess.run(
        ["git", "rev-parse", "HEAD"],
        cwd=ROOT,
        capture_output=True,
        text=True,
        check=False,
    )
    return result.stdout.strip() if result.returncode == 0 else "unknown"


def tool_version(command: list[str]) -> str:
    result = subprocess.run(command, cwd=ROOT, capture_output=True, text=True, check=False)
    if result.returncode != 0:
        return "unavailable"
    return (result.stdout or result.stderr).strip().splitlines()[0]


def figure_orientation(diagram: Diagram) -> str:
    width, height = diagram.canvas
    if width / max(height, 1) >= 1.35:
        return "Landscape"
    if height / max(width, 1) >= 1.2:
        return "Portrait"
    return "Square / flexible"


def visual_status(diagram: Diagram) -> str:
    if diagram.number in {"3.16", "3.19"}:
        return "PASS WITH MINOR LIMITATION"
    return "PASS"


def wrap_identifier(value: str, width: int = 22) -> str:
    if len(value) <= width:
        return value
    parts = value.split("_")
    lines: list[str] = []
    current = ""
    for part in parts:
        candidate = part if not current else f"{current}_{part}"
        if len(candidate) <= width:
            current = candidate
        else:
            if current:
                lines.append(current)
            current = part
    if current:
        lines.append(current)
    return "\n".join(lines)


def validate_mono_png(path: Path) -> tuple[bool, str]:
    with Image.open(path) as image:
        rgba = image.convert("RGBA")
        has_transparency = False
        coloured_pixels = 0
        sampled_pixels = 0
        for r, g, b, a in rgba.getdata():
            if a == 0:
                has_transparency = True
                continue
            if a < 255:
                has_transparency = True
            sampled_pixels += 1
            if max(r, g, b) - min(r, g, b) > 8:
                coloured_pixels += 1
        if not has_transparency:
            return False, "No transparent pixels detected"
        if sampled_pixels and coloured_pixels / sampled_pixels > 0.002:
            return False, "Detected non-monochrome coloured pixels"
    return True, "Transparent monochrome PNG"


def validate_mono_white_png(path: Path) -> tuple[bool, str]:
    with Image.open(path) as image:
        rgba = image.convert("RGBA")
        sampled_pixels = 0
        coloured_pixels = 0
        transparent_pixels = 0
        step = max(1, rgba.width * rgba.height // 6000)
        for index, (r, g, b, a) in enumerate(rgba.getdata()):
            if index % step:
                continue
            if a < 255:
                transparent_pixels += 1
            if a == 0:
                continue
            sampled_pixels += 1
            if max(r, g, b) - min(r, g, b) > 8:
                coloured_pixels += 1
        if transparent_pixels:
            return False, "Transparent pixels detected in white-background variant"
        if sampled_pixels and coloured_pixels / sampled_pixels > 0.002:
            return False, "Detected non-monochrome coloured pixels"
    return True, "White-background monochrome PNG"


def write_full_schema_technical_erd() -> dict[str, str]:
    safe_name = "Figure3_19_full_schema_technical"
    mmd_path = OUT / "source" / "authoritative" / f"{safe_name}.mmd"
    svg_path = OUT / "svg" / f"{safe_name}.svg"
    mmd_path.write_text(erd_mermaid_from_metadata(full=True), encoding="utf-8")

    tables = list(Base.metadata.sorted_tables)
    columns = 3
    box_w = 520
    row_h = 320
    width = columns * box_w + 120
    rows = max(1, math.ceil(max(len(tables), 1) / columns))
    height = 180 + rows * row_h
    svg = [
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{height}" viewBox="0 0 {width} {height}">',
        '<style>text{font-family:Arial, sans-serif;fill:#042A3A}.title{font-weight:bold;font-size:26px}.table{font-weight:bold;font-size:18px}.col{font-size:13px}.box{fill:#FFFFFF;stroke:#0F8B8D;stroke-width:2}.header{fill:#DDF7F5;stroke:#0F8B8D;stroke-width:2}</style>',
        f'<text x="60" y="55" class="title">Figure 3.19A: Full Technical Schema ERD</text>',
        '<text x="60" y="88" class="col">Generated from SQLAlchemy metadata. This technical artefact preserves all columns for implementation traceability.</text>',
    ]
    if not tables:
        svg.append('<rect x="60" y="130" width="700" height="100" rx="14" class="box"/>')
        svg.append('<text x="90" y="185" class="table">No SQLAlchemy tables detected</text>')
    for i, table in enumerate(tables):
        row, col_idx = divmod(i, columns)
        x = 60 + col_idx * box_w
        y = 130 + row * row_h
        svg.append(f'<rect x="{x}" y="{y}" width="470" height="285" rx="12" class="box"/>')
        svg.append(f'<rect x="{x}" y="{y}" width="470" height="42" rx="12" class="header"/>')
        for line_no, table_name_line in enumerate(wrap_identifier(table.name, 32).splitlines()):
            svg.append(f'<text x="{x + 18}" y="{y + 25 + line_no * 18}" class="table">{escape(table_name_line)}</text>')
        for j, column in enumerate(table.columns):
            markers = []
            if column.primary_key:
                markers.append("PK")
            if column.foreign_keys:
                markers.append("FK")
            suffix = f" ({'/'.join(markers)})" if markers else ""
            label = f"{column.name}: {column.type}{suffix}"
            if len(label) > 56:
                label = label[:53] + "..."
            svg.append(f'<text x="{x + 18}" y="{y + 70 + j * 17}" class="col">{escape(label)}</text>')
            if j >= 11 and len(table.columns) > 13:
                svg.append(f'<text x="{x + 18}" y="{y + 70 + (j + 1) * 17}" class="col">... {len(table.columns) - j - 1} more columns</text>')
                break
    svg.append("</svg>")
    svg_path.write_text("\n".join(svg), encoding="utf-8")
    return {
        "source": rel(mmd_path),
        "svg": rel(svg_path),
        "source_sha256": checksum(mmd_path),
        "svg_sha256": checksum(svg_path),
        "purpose": "Full schema technical reference; not the primary dissertation figure.",
    }


def write_visual_review(diagrams: list[Diagram], artefacts: dict[str, dict[str, str]]) -> None:
    lines = [
        "# Chapter Three Diagram Visual Review",
        "",
        f"Generated at: {datetime.now(timezone.utc).isoformat()}",
        "",
        "This review records the visual-readiness status of the official Chapter Three figure variants. Colour, monochrome-transparent and monochrome-white-background variants are generated from the same authoritative source for dissertation traceability.",
        "",
        "## Review Summary",
        "",
        "- Official colour SVG/PNG variants are generated for all 21 figures.",
        "- Official monochrome transparent SVG/PNG variants are generated for all 21 figures.",
        "- Official monochrome white-background SVG/PNG variants are generated for all 21 figures.",
        "- Final correction pass applied locally to Figures 3.1, 3.3, 3.4, 3.5, 3.8, 3.9, 3.10, 3.11, 3.12, 3.13, 3.15, 3.16, 3.17, 3.18 and 3.19.",
        "- Existing legacy outputs remain available in the original `png/`, `svg/` and `source/` folders.",
        "- Figure 3.19 has a readable dissertation ERD plus a separate full technical schema artefact.",
        "",
        "## Figure Status",
        "",
    ]
    for d in diagrams:
        status = visual_status(d)
        orientation = figure_orientation(d)
        mono_ok = artefacts[d.number].get("mono_png_valid", "unknown")
        mono_white_ok = artefacts[d.number].get("mono_white_png_valid", "unknown")
        lines.append(f"- Figure {d.number}: **{status}**")
        lines.append(f"  - Title: {d.title}")
        lines.append(f"  - Recommended Word orientation: {orientation}")
        lines.append(f"  - Monochrome transparency check: {mono_ok}")
        lines.append(f"  - Monochrome white-background check: {mono_white_ok}")
        if d.notes:
            for note in d.notes:
                lines.append(f"  - Note: {note}")
        if status == "PASS WITH MINOR LIMITATION":
            lines.append("  - Limitation: The figure is technically dense; use landscape placement or appendix zoom if the dissertation template constrains width.")
    lines.extend(
        [
            "",
            "## Sprint 2 Hardening Tasks",
            "",
            "- Keep the Sprint 2 authentication/session milestone untagged until the user explicitly approves the milestone.",
            "- Maintain generated dissertation figures as implementation-derived artefacts rather than manually edited images.",
            "- Re-run this generator after schema or architecture changes before using Chapter Three figures in Word.",
        ]
    )
    (OUT / "diagram_visual_review.md").write_text("\n".join(lines) + "\n", encoding="utf-8")


def write_index(diagrams: list[Diagram], artefacts: dict[str, dict[str, str]]) -> None:
    lines = ["# Chapter Three Figure Index", ""]
    for d in diagrams:
        files = artefacts[d.number]
        lines.append(f"- Figure {d.number}: {d.title}")
        lines.append(f"  - Source: `source/{d.safe_name}.mmd`")
        lines.append(f"  - SVG: `svg/{d.safe_name}.svg`")
        lines.append(f"  - PNG: `png/{d.safe_name}.png`")
        lines.append(f"  - Authoritative source: `{files['authoritative_source']}`")
        lines.append(f"  - Official colour SVG: `{files['colour_svg']}`")
        lines.append(f"  - Official colour PNG: `{files['colour_png']}`")
        lines.append(f"  - Official monochrome transparent SVG: `{files['mono_svg']}`")
        lines.append(f"  - Official monochrome transparent PNG: `{files['mono_png']}`")
        lines.append(f"  - Official monochrome white-background SVG: `{files['mono_white_svg']}`")
        lines.append(f"  - Official monochrome white-background PNG: `{files['mono_white_png']}`")
        lines.append(f"  - Recommended Word orientation: {files['recommended_orientation']}")
    (OUT / "figure_index.md").write_text("\n".join(lines) + "\n", encoding="utf-8")

    captions = ["# Chapter Three Captions", ""]
    for d in diagrams:
        captions.append(f"**Figure {d.number}: {d.title}.**")
        captions.append(f"Source: {d.source}.")
        captions.append("")
    (OUT / "captions.md").write_text("\n".join(captions), encoding="utf-8")

    manifest = {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "generator": "scripts/docs/generate_chapter3_diagrams.py",
        "serps_version": "chapter-three-diagram-remediation",
        "git_commit": git_commit_hash(),
        "tool_versions": {
            "python": tool_version(["python", "--version"]),
            "pillow": Image.__version__,
        },
        "figures": artefacts,
    }
    (OUT / "manifest.json").write_text(json.dumps(manifest, indent=2), encoding="utf-8")


def validate(diagrams: list[Diagram], artefacts: dict[str, dict[str, str]]) -> None:
    colour_png_count = len(list((OUT / "png" / "colour").glob("Figure3_*_colour.png")))
    colour_svg_count = len(list((OUT / "svg" / "colour").glob("Figure3_*_colour.svg")))
    mono_png_count = len(list((OUT / "png" / "mono_transparent").glob("Figure3_*_mono_transparent.png")))
    mono_svg_count = len(list((OUT / "svg" / "mono_transparent").glob("Figure3_*_mono_transparent.svg")))
    mono_white_png_count = len(list((OUT / "png" / "mono_white_background").glob("Figure3_*_mono_white_background.png")))
    mono_white_svg_count = len(list((OUT / "svg" / "mono_white_background").glob("Figure3_*_mono_white_background.svg")))
    lines = [
        "# Chapter Three Diagram Validation Report",
        "",
        f"Generated at: {datetime.now(timezone.utc).isoformat()}",
        "",
        "## Summary",
        "",
        f"- Figures requested: 21",
        f"- Figures generated: {len(diagrams)}",
        "- Editable Mermaid sources generated for every figure.",
        "- SVG exports generated for every figure.",
        "- High-resolution PNG exports generated for every figure with 300 DPI metadata.",
        f"- Official colour PNG variants: {colour_png_count}",
        f"- Official colour SVG variants: {colour_svg_count}",
        f"- Official monochrome transparent PNG variants: {mono_png_count}",
        f"- Official monochrome transparent SVG variants: {mono_svg_count}",
        f"- Official monochrome white-background PNG variants: {mono_white_png_count}",
        f"- Official monochrome white-background SVG variants: {mono_white_svg_count}",
        "- Draw.io exports were not generated in this urgent sprint; Mermaid sources remain editable and SVG is the publication authority.",
        "",
        "## Validation Results",
        "",
    ]
    for d in diagrams:
        files = artefacts[d.number]
        ok = all((ROOT / files[key]).exists() for key in ("source", "category_source", "svg", "png", "authoritative_source", "colour_svg", "colour_png", "mono_svg", "mono_png", "mono_white_svg", "mono_white_png"))
        lines.append(f"- Figure {d.number}: {'PASS' if ok else 'NEEDS REVIEW'} - {d.title}")
        lines.append(f"  - Visual status: {files['visual_review_status']}")
        lines.append(f"  - Recommended Word orientation: {files['recommended_orientation']}")
        lines.append(f"  - Monochrome check: {files['mono_png_valid']}")
        lines.append(f"  - Monochrome white-background check: {files['mono_white_png_valid']}")
        for note in d.notes:
            lines.append(f"  - Note: {note}")
    lines.extend(
        [
            "",
            "## Figure 3.19 Schema Status",
            "",
            "Figure 3.19 was generated from the current SQLAlchemy metadata. The present POP schema includes EvidenceEvent persistence plus Sprint 2 institution, user, role, candidate, examination, assignment, session, authentication, refresh-token and audit-log tables.",
            "",
            "## Architecture Consistency Checks",
            "",
            "- Detection modules are shown as evidence producers only.",
            "- CIE is shown as the central reasoning layer.",
            "- Agentic Decision Support is shown as advisory only.",
            "- IPIME is shown as institutional workflow/policy handling, not final decision-making.",
            "- Human Reviewer and final institutional decision boundaries are explicit.",
            "- PostgreSQL is represented as shared persistence, not a reasoning component.",
            "- React/Next.js is represented as presentation/control surface, not as CIE or AI business logic.",
            "",
            "## Sprint 2 Tagging Note",
            "",
            "- The `v0.2.0-auth-session-foundation` tag was intentionally not created in this remediation sprint.",
        ]
    )
    (OUT / "diagram_validation_report.md").write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    for subdir in SUBDIRS:
        (OUT / subdir).mkdir(parents=True, exist_ok=True)
    diagrams = build_diagrams()
    artefacts: dict[str, dict[str, str]] = {}
    for d in diagrams:
        mmd_path = OUT / "source" / f"{d.safe_name}.mmd"
        svg_path = OUT / "svg" / f"{d.safe_name}.svg"
        png_path = OUT / "png" / f"{d.safe_name}.png"
        legacy_mmd = OUT / "source" / "legacy" / f"{d.safe_name}.mmd"
        authoritative_mmd = OUT / "source" / "authoritative" / f"{d.safe_name}.mmd"
        colour_svg = OUT / "svg" / "colour" / f"{d.safe_name}_colour.svg"
        colour_png = OUT / "png" / "colour" / f"{d.safe_name}_colour.png"
        mono_svg = OUT / "svg" / "mono_transparent" / f"{d.safe_name}_mono_transparent.svg"
        mono_png = OUT / "png" / "mono_transparent" / f"{d.safe_name}_mono_transparent.png"
        mono_white_svg = OUT / "svg" / "mono_white_background" / f"{d.safe_name}_mono_white_background.svg"
        mono_white_png = OUT / "png" / "mono_white_background" / f"{d.safe_name}_mono_white_background.png"
        category_mmd = OUT / d.category / f"{d.safe_name}.mmd"
        if mmd_path.exists() and not legacy_mmd.exists():
            shutil.copyfile(mmd_path, legacy_mmd)
        write_mmd(d, mmd_path)
        write_mmd(d, category_mmd)
        write_mmd(d, authoritative_mmd)
        render_svg(d, svg_path)
        render_png(d, png_path)
        render_svg(d, colour_svg, COLOUR_THEME)
        render_png(d, colour_png, COLOUR_THEME)
        render_svg(d, mono_svg, MONO_THEME)
        render_png(d, mono_png, MONO_THEME)
        render_svg(d, mono_white_svg, MONO_WHITE_THEME)
        render_png(d, mono_white_png, MONO_WHITE_THEME)
        mono_ok, mono_message = validate_mono_png(mono_png)
        mono_white_ok, mono_white_message = validate_mono_white_png(mono_white_png)
        artefacts[d.number] = {
            "source": rel(mmd_path),
            "legacy_source": rel(legacy_mmd) if legacy_mmd.exists() else "",
            "category_source": rel(category_mmd),
            "authoritative_source": rel(authoritative_mmd),
            "svg": rel(svg_path),
            "png": rel(png_path),
            "colour_svg": rel(colour_svg),
            "colour_png": rel(colour_png),
            "mono_svg": rel(mono_svg),
            "mono_png": rel(mono_png),
            "mono_white_svg": rel(mono_white_svg),
            "mono_white_png": rel(mono_white_png),
            "source_sha256": checksum(mmd_path),
            "authoritative_source_sha256": checksum(authoritative_mmd),
            "svg_sha256": checksum(svg_path),
            "png_sha256": checksum(png_path),
            "colour_svg_sha256": checksum(colour_svg),
            "colour_png_sha256": checksum(colour_png),
            "mono_svg_sha256": checksum(mono_svg),
            "mono_png_sha256": checksum(mono_png),
            "mono_white_svg_sha256": checksum(mono_white_svg),
            "mono_white_png_sha256": checksum(mono_white_png),
            "mono_png_valid": "PASS" if mono_ok else f"NEEDS REVIEW - {mono_message}",
            "mono_white_png_valid": "PASS" if mono_white_ok else f"NEEDS REVIEW - {mono_white_message}",
            "recommended_orientation": figure_orientation(d),
            "visual_review_status": visual_status(d),
        }
    artefacts["3.19A"] = write_full_schema_technical_erd()
    write_index(diagrams, artefacts)
    write_visual_review(diagrams, artefacts)
    validate(diagrams, artefacts)
    print(f"Generated {len(diagrams)} Chapter Three figures in {OUT}")


if __name__ == "__main__":
    main()
