"""Generate Chapter Three dissertation diagrams for SERPS POP.

The generator intentionally uses implementation-owned definitions and the
current SQLAlchemy metadata for Figure 3.19. Mermaid source files are retained
as editable diagram sources, while SVG/PNG exports are generated by a small
deterministic renderer so the sprint does not depend on a local Mermaid CLI.
"""

from __future__ import annotations

import hashlib
import json
import math
import os
import re
import shutil
import subprocess
import textwrap
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Iterable
from xml.sax.saxutils import escape

from PIL import Image, ImageDraw, ImageFont

from serps_pop.evidence import models as _evidence_models  # noqa: F401
from serps_pop.identity import models as _identity_models  # noqa: F401
from serps_pop.infrastructure.database import Base


ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / "docs" / "dissertation" / "chapter3"
SUBDIRS = [
    "architecture",
    "uml",
    "flowcharts",
    "api",
    "technology",
    "png",
    "png/colour",
    "png/mono_transparent",
    "svg",
    "svg/colour",
    "svg/mono_transparent",
    "source",
    "source/authoritative",
    "source/legacy",
]

NAVY = "#073B4C"
DEEP_NAVY = "#042A3A"
TEAL = "#0F8B8D"
TEAL_LIGHT = "#DDF7F5"
WHITE = "#FFFFFF"
GREY = "#EEF3F6"
MUTED = "#60717C"
LINE = "#7FA9B5"
AMBER = "#F2B84B"
AMBER_LIGHT = "#FFF4D6"
GREEN = "#2EAD6B"
RED = "#C94C4C"


@dataclass(frozen=True)
class Box:
    x: float
    y: float
    w: float
    h: float
    text: str
    fill: str = WHITE
    stroke: str = TEAL
    color: str = DEEP_NAVY
    title: bool = False
    dashed: bool = False
    radius: float = 18


@dataclass(frozen=True)
class Ellipse:
    x: float
    y: float
    w: float
    h: float
    text: str
    fill: str = WHITE
    stroke: str = TEAL
    color: str = DEEP_NAVY


@dataclass(frozen=True)
class Actor:
    x: float
    y: float
    text: str


@dataclass(frozen=True)
class Diamond:
    x: float
    y: float
    w: float
    h: float
    text: str
    fill: str = AMBER_LIGHT
    stroke: str = TEAL
    color: str = DEEP_NAVY


@dataclass(frozen=True)
class Arrow:
    x1: float
    y1: float
    x2: float
    y2: float
    label: str = ""
    color: str = LINE
    dashed: bool = False


@dataclass(frozen=True)
class Note:
    x: float
    y: float
    text: str
    color: str = MUTED
    size: int = 22


Shape = Box | Ellipse | Actor | Diamond | Arrow | Note


@dataclass(frozen=True)
class RenderTheme:
    name: str
    background: str | None
    header_fill: str | None
    title_color: str
    subtitle_color: str
    box_fill: str | None
    box_stroke: str
    text_color: str
    muted_color: str
    line_color: str
    shadow: bool = True


COLOUR_THEME = RenderTheme(
    "colour",
    GREY,
    NAVY,
    WHITE,
    TEAL_LIGHT,
    None,
    TEAL,
    DEEP_NAVY,
    MUTED,
    LINE,
    True,
)

MONO_THEME = RenderTheme(
    "mono_transparent",
    None,
    None,
    "#000000",
    "#000000",
    None,
    "#000000",
    "#000000",
    "#000000",
    "#000000",
    False,
)


@dataclass
class Diagram:
    number: str
    title: str
    category: str
    canvas: tuple[int, int]
    shapes: list[Shape]
    mmd: str
    source: str = "Author's Architecture (2026)"
    notes: list[str] = field(default_factory=list)

    @property
    def safe_name(self) -> str:
        safe_title = re.sub(r"[^A-Za-z0-9]+", "_", self.title).strip("_")
        return f"Figure{self.number.replace('.', '_')}_{safe_title}"


def font(size: int, bold: bool = False) -> ImageFont.FreeTypeFont:
    candidates = [
        "C:/Windows/Fonts/arialbd.ttf" if bold else "C:/Windows/Fonts/arial.ttf",
        "C:/Windows/Fonts/segoeuib.ttf" if bold else "C:/Windows/Fonts/segoeui.ttf",
    ]
    for candidate in candidates:
        if Path(candidate).exists():
            return ImageFont.truetype(candidate, size)
    return ImageFont.load_default()


def wrap_text(text: str, max_chars: int) -> list[str]:
    lines: list[str] = []
    for paragraph in text.split("\n"):
        if not paragraph:
            lines.append("")
        else:
            lines.extend(textwrap.wrap(paragraph, width=max_chars, break_long_words=False))
    return lines


def draw_wrapped(
    draw: ImageDraw.ImageDraw,
    xy: tuple[float, float],
    text: str,
    fill: str,
    fnt: ImageFont.FreeTypeFont,
    max_width: float,
    align: str = "center",
) -> None:
    avg = max(fnt.getlength("ABCDEFGHIJKLMNOPQRSTUVWXYZ") / 26, 8)
    lines = wrap_text(text, max(8, int(max_width / avg)))
    line_h = fnt.size + 7
    x, y = xy
    for line in lines:
        bbox = draw.textbbox((0, 0), line, font=fnt)
        width = bbox[2] - bbox[0]
        tx = x
        if align == "center":
            tx = x - width / 2
        elif align == "right":
            tx = x - width
        draw.text((tx, y), line, fill=fill, font=fnt)
        y += line_h


def arrow_head(x1: float, y1: float, x2: float, y2: float, size: float = 16) -> list[tuple[float, float]]:
    angle = math.atan2(y2 - y1, x2 - x1)
    left = angle + math.pi * 0.82
    right = angle - math.pi * 0.82
    return [
        (x2, y2),
        (x2 + size * math.cos(left), y2 + size * math.sin(left)),
        (x2 + size * math.cos(right), y2 + size * math.sin(right)),
    ]


def draw_arrow(draw: ImageDraw.ImageDraw, arrow: Arrow, scale: int = 1, theme: RenderTheme = COLOUR_THEME) -> None:
    x1, y1, x2, y2 = [v * scale for v in (arrow.x1, arrow.y1, arrow.x2, arrow.y2)]
    color = theme.line_color
    width = 4 * scale
    if arrow.dashed:
        steps = max(8, int(math.hypot(x2 - x1, y2 - y1) / (18 * scale)))
        for i in range(steps):
            if i % 2 == 0:
                sx = x1 + (x2 - x1) * i / steps
                sy = y1 + (y2 - y1) * i / steps
                ex = x1 + (x2 - x1) * (i + 1) / steps
                ey = y1 + (y2 - y1) * (i + 1) / steps
                draw.line((sx, sy, ex, ey), fill=color, width=width)
    else:
        draw.line((x1, y1, x2, y2), fill=color, width=width)
    draw.polygon([(x * scale, y * scale) for x, y in arrow_head(arrow.x1, arrow.y1, arrow.x2, arrow.y2)], fill=color)
    if arrow.label:
        mid = ((x1 + x2) / 2, (y1 + y2) / 2 - 18 * scale)
        draw.text(mid, arrow.label, fill=theme.text_color, font=font(18 * scale), anchor="mm")


def mermaid_type(column_type: object) -> str:
    raw = column_type.__class__.__name__.lower()
    if "integer" in raw:
        return "int"
    if "float" in raw or "numeric" in raw:
        return "float"
    if "boolean" in raw:
        return "boolean"
    if "date" in raw or "time" in raw:
        return "datetime"
    return "string"


def erd_mermaid_from_metadata(full: bool = False) -> str:
    lines = ["erDiagram"]
    for table in Base.metadata.sorted_tables:
        lines.append(f"  {table.name} {{")
        selected_columns = list(table.columns) if full else [
            column
            for column in table.columns
            if column.primary_key
            or column.foreign_keys
            or column.name in {"email", "name", "title", "status", "role_name", "event_type", "confidence", "monitoring_mode", "risk_level", "created_at"}
        ][:8]
        for column in selected_columns:
            markers = []
            if column.primary_key:
                markers.append("PK")
            if column.foreign_keys:
                markers.append("FK")
            marker_text = f" {' '.join(markers)}" if markers else ""
            lines.append(f"    {mermaid_type(column.type)} {column.name}{marker_text}")
        lines.append("  }")
    for table in Base.metadata.sorted_tables:
        for foreign_key in table.foreign_keys:
            referred = foreign_key.column.table.name
            lines.append(f"  {referred} ||--o{{ {table.name} : references")
    return "\n".join(lines)


def render_png(diagram: Diagram, path: Path, theme: RenderTheme = COLOUR_THEME) -> None:
    w, h = diagram.canvas
    scale = 2
    if theme.background is None:
        img = Image.new("RGBA", (w * scale, h * scale), (255, 255, 255, 0))
    else:
        img = Image.new("RGB", (w * scale, h * scale), theme.background)
    draw = ImageDraw.Draw(img)
    if theme.header_fill:
        draw.rounded_rectangle((50 * scale, 45 * scale, (w - 50) * scale, 145 * scale), radius=26 * scale, fill=theme.header_fill)
    draw.text((75 * scale, 72 * scale), f"Figure {diagram.number}", fill=theme.subtitle_color, font=font(28 * scale, True))
    draw.text((75 * scale, 105 * scale), diagram.title, fill=theme.title_color, font=font(25 * scale, True))

    for shape in diagram.shapes:
        if isinstance(shape, Box):
            rect = tuple(v * scale for v in (shape.x, shape.y, shape.x + shape.w, shape.y + shape.h))
            if theme.shadow:
                shadow = (rect[0] + 5 * scale, rect[1] + 6 * scale, rect[2] + 5 * scale, rect[3] + 6 * scale)
                draw.rounded_rectangle(shadow, radius=shape.radius * scale, fill="#D9E4EA")
            fill = shape.fill if theme.name == "colour" else (255, 255, 255, 0)
            stroke = shape.stroke if theme.name == "colour" else theme.box_stroke
            text_color = shape.color if theme.name == "colour" else theme.text_color
            draw.rounded_rectangle(rect, radius=shape.radius * scale, fill=fill, outline=stroke, width=3 * scale)
            fnt = font((24 if shape.title else 21) * scale, shape.title)
            lines = wrap_text(shape.text, max(10, int(shape.w / 14)))
            text_h = len(lines) * (fnt.size + 7)
            draw_wrapped(
                draw,
                ((shape.x + shape.w / 2) * scale, (shape.y + shape.h / 2 - text_h / (2 * scale)) * scale),
                shape.text,
                text_color,
                fnt,
                shape.w * scale - 35 * scale,
            )
        elif isinstance(shape, Ellipse):
            rect = tuple(v * scale for v in (shape.x, shape.y, shape.x + shape.w, shape.y + shape.h))
            fill = shape.fill if theme.name == "colour" else (255, 255, 255, 0)
            stroke = shape.stroke if theme.name == "colour" else theme.box_stroke
            text_color = shape.color if theme.name == "colour" else theme.text_color
            draw.ellipse(rect, fill=fill, outline=stroke, width=3 * scale)
            draw_wrapped(
                draw,
                ((shape.x + shape.w / 2) * scale, (shape.y + shape.h / 2 - 22) * scale),
                shape.text,
                text_color,
                font(20 * scale, True),
                shape.w * scale - 25 * scale,
            )
        elif isinstance(shape, Actor):
            x, y = shape.x * scale, shape.y * scale
            draw.ellipse((x - 18 * scale, y, x + 18 * scale, y + 36 * scale), outline=theme.text_color, width=4 * scale)
            draw.line((x, y + 36 * scale, x, y + 95 * scale), fill=theme.text_color, width=4 * scale)
            draw.line((x - 42 * scale, y + 60 * scale, x + 42 * scale, y + 60 * scale), fill=theme.text_color, width=4 * scale)
            draw.line((x, y + 95 * scale, x - 38 * scale, y + 145 * scale), fill=theme.text_color, width=4 * scale)
            draw.line((x, y + 95 * scale, x + 38 * scale, y + 145 * scale), fill=theme.text_color, width=4 * scale)
            draw_wrapped(draw, (x, y + 155 * scale), shape.text, theme.text_color, font(20 * scale, True), 150 * scale)
        elif isinstance(shape, Diamond):
            points = [
                ((shape.x + shape.w / 2) * scale, shape.y * scale),
                ((shape.x + shape.w) * scale, (shape.y + shape.h / 2) * scale),
                ((shape.x + shape.w / 2) * scale, (shape.y + shape.h) * scale),
                (shape.x * scale, (shape.y + shape.h / 2) * scale),
            ]
            fill = shape.fill if theme.name == "colour" else (255, 255, 255, 0)
            stroke = shape.stroke if theme.name == "colour" else theme.box_stroke
            text_color = shape.color if theme.name == "colour" else theme.text_color
            draw.polygon(points, fill=fill, outline=stroke)
            draw.line(points + [points[0]], fill=stroke, width=3 * scale)
            draw_wrapped(
                draw,
                ((shape.x + shape.w / 2) * scale, (shape.y + shape.h / 2 - 20) * scale),
                shape.text,
                text_color,
                font(18 * scale, True),
                shape.w * scale - 45 * scale,
            )
        elif isinstance(shape, Arrow):
            draw_arrow(draw, shape, scale, theme)
        elif isinstance(shape, Note):
            color = shape.color if theme.name == "colour" else theme.text_color
            draw_wrapped(draw, (shape.x * scale, shape.y * scale), shape.text, color, font(shape.size * scale), 420 * scale)

    draw.text((w * scale - 70 * scale, h * scale - 45 * scale), "SERPS Architecture", fill=theme.muted_color, font=font(18 * scale), anchor="ra")
    img.save(path, dpi=(300, 300))


def svg_text(x: float, y: float, text: str, size: int, color: str, weight: str = "400", anchor: str = "middle") -> str:
    spans = []
    for i, line in enumerate(wrap_text(text, 32)):
        spans.append(
            f'<text x="{x:.1f}" y="{y + i * (size + 7):.1f}" text-anchor="{anchor}" '
            f'font-family="Segoe UI, Arial, sans-serif" font-size="{size}" font-weight="{weight}" fill="{color}">{escape(line)}</text>'
        )
    return "\n".join(spans)


def render_svg(diagram: Diagram, path: Path, theme: RenderTheme = COLOUR_THEME) -> None:
    w, h = diagram.canvas
    arrow_colour = theme.line_color
    out = [
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{w}" height="{h}" viewBox="0 0 {w} {h}">',
        "<defs>",
        f'<marker id="arrow" markerWidth="12" markerHeight="12" refX="10" refY="6" orient="auto" markerUnits="strokeWidth"><path d="M2,2 L10,6 L2,10 z" fill="{arrow_colour}"/></marker>',
        '<filter id="shadow" x="-20%" y="-20%" width="140%" height="140%"><feDropShadow dx="3" dy="5" stdDeviation="4" flood-color="#9AB2BD" flood-opacity="0.45"/></filter>',
        "</defs>",
    ]
    if theme.background:
        out.append(f'<rect width="{w}" height="{h}" fill="{theme.background}"/>')
    if theme.header_fill:
        out.append(f'<rect x="50" y="45" width="{w-100}" height="100" rx="26" fill="{theme.header_fill}"/>')
    out.append(svg_text(75, 84, f"Figure {diagram.number}", 28, theme.subtitle_color, "700", "start"))
    out.append(svg_text(75, 118, diagram.title, 25, theme.title_color, "700", "start"))
    for shape in diagram.shapes:
        if isinstance(shape, Box):
            dash = ' stroke-dasharray="8 7"' if shape.dashed else ""
            fill = shape.fill if theme.name == "colour" else "none"
            stroke = shape.stroke if theme.name == "colour" else theme.box_stroke
            text_color = shape.color if theme.name == "colour" else theme.text_color
            filter_attr = ' filter="url(#shadow)"' if theme.shadow else ""
            out.append(
                f'<rect x="{shape.x}" y="{shape.y}" width="{shape.w}" height="{shape.h}" rx="{shape.radius}" '
                f'fill="{fill}" stroke="{stroke}" stroke-width="3"{dash}{filter_attr}/>'
            )
            lines = wrap_text(shape.text, max(10, int(shape.w / 12)))
            size = 24 if shape.title else 21
            out.append(svg_text(shape.x + shape.w / 2, shape.y + shape.h / 2 - (len(lines) * (size + 7)) / 2 + size, shape.text, size, text_color, "700" if shape.title else "500"))
        elif isinstance(shape, Ellipse):
            fill = shape.fill if theme.name == "colour" else "none"
            stroke = shape.stroke if theme.name == "colour" else theme.box_stroke
            text_color = shape.color if theme.name == "colour" else theme.text_color
            out.append(
                f'<ellipse cx="{shape.x + shape.w/2}" cy="{shape.y + shape.h/2}" rx="{shape.w/2}" ry="{shape.h/2}" fill="{fill}" stroke="{stroke}" stroke-width="3"/>'
            )
            out.append(svg_text(shape.x + shape.w / 2, shape.y + shape.h / 2, shape.text, 20, text_color, "700"))
        elif isinstance(shape, Actor):
            x, y = shape.x, shape.y
            out.append(f'<circle cx="{x}" cy="{y+18}" r="18" fill="none" stroke="{theme.text_color}" stroke-width="4"/>')
            out.append(f'<path d="M{x},{y+36} L{x},{y+95} M{x-42},{y+60} L{x+42},{y+60} M{x},{y+95} L{x-38},{y+145} M{x},{y+95} L{x+38},{y+145}" stroke="{theme.text_color}" stroke-width="4" fill="none"/>')
            out.append(svg_text(x, y + 170, shape.text, 20, theme.text_color, "700"))
        elif isinstance(shape, Diamond):
            fill = shape.fill if theme.name == "colour" else "none"
            stroke = shape.stroke if theme.name == "colour" else theme.box_stroke
            text_color = shape.color if theme.name == "colour" else theme.text_color
            points = [
                (shape.x + shape.w / 2, shape.y),
                (shape.x + shape.w, shape.y + shape.h / 2),
                (shape.x + shape.w / 2, shape.y + shape.h),
                (shape.x, shape.y + shape.h / 2),
            ]
            point_text = " ".join(f"{x:.1f},{y:.1f}" for x, y in points)
            out.append(f'<polygon points="{point_text}" fill="{fill}" stroke="{stroke}" stroke-width="3"/>')
            out.append(svg_text(shape.x + shape.w / 2, shape.y + shape.h / 2, shape.text, 18, text_color, "700"))
        elif isinstance(shape, Arrow):
            dash = ' stroke-dasharray="8 7"' if shape.dashed else ""
            out.append(
                f'<line x1="{shape.x1}" y1="{shape.y1}" x2="{shape.x2}" y2="{shape.y2}" stroke="{theme.line_color}" stroke-width="4"{dash} marker-end="url(#arrow)"/>'
            )
            if shape.label:
                out.append(svg_text((shape.x1 + shape.x2) / 2, (shape.y1 + shape.y2) / 2 - 14, shape.label, 18, theme.text_color, "600"))
        elif isinstance(shape, Note):
            color = shape.color if theme.name == "colour" else theme.text_color
            out.append(svg_text(shape.x, shape.y, shape.text, shape.size, color, "500"))
    out.append(svg_text(w - 70, h - 45, "SERPS Architecture", 18, theme.muted_color, "500", "end"))
    out.append("</svg>")
    path.write_text("\n".join(out), encoding="utf-8")


def write_mmd(diagram: Diagram, path: Path) -> None:
    init = "%%{init: {'theme': 'base', 'themeVariables': {'primaryColor': '#DDF7F5', 'primaryBorderColor': '#0F8B8D', 'lineColor': '#7FA9B5', 'fontFamily': 'Segoe UI, Arial'}}}%%\n"
    path.write_text(init + diagram.mmd.strip() + "\n", encoding="utf-8")


def pipeline_shapes(items: list[str], x: int = 650, y: int = 190, w: int = 500, h: int = 70, gap: int = 25) -> list[Shape]:
    shapes: list[Shape] = []
    for i, item in enumerate(items):
        yy = y + i * (h + gap)
        fill = TEAL_LIGHT if i in {0, len(items) - 1} else WHITE
        shapes.append(Box(x, yy, w, h, item, fill=fill, title=i == 0))
        if i:
            shapes.append(Arrow(x + w / 2, yy - gap + 3, x + w / 2, yy - 4))
    return shapes


def grid_boxes(items: list[str], x: int, y: int, cols: int, box_w: int, box_h: int, gap_x: int, gap_y: int, fill: str = WHITE) -> list[Shape]:
    shapes: list[Shape] = []
    for i, item in enumerate(items):
        row, col = divmod(i, cols)
        shapes.append(Box(x + col * (box_w + gap_x), y + row * (box_h + gap_y), box_w, box_h, item, fill=fill))
    return shapes


def mmd_flow(title: str, items: Iterable[str]) -> str:
    nodes = list(items)
    lines = ["flowchart TD"]
    for i, item in enumerate(nodes):
        lines.append(f'  N{i}["{item}"]')
        if i:
            lines.append(f"  N{i-1} --> N{i}")
    return "\n".join(lines)


def build_diagrams() -> list[Diagram]:
    diagrams: list[Diagram] = []

    # 3.1
    dsr = ["Problem Identification", "Literature Review", "Requirements Analysis", "System Architecture", "Prototype Design"]
    shapes = pipeline_shapes(dsr, 115, 210, 430, 78, 28)
    agile = ["Sprint Planning", "Implementation", "Testing", "Sprint Review", "Refinement"]
    agile_positions = [(880, 230), (1220, 230), (1220, 485), (880, 485), (710, 358)]
    for label, (x, y) in zip(agile, agile_positions, strict=True):
        shapes.append(Box(x, y, 270, 86, label, fill=TEAL_LIGHT if label == "Sprint Planning" else WHITE))
    loop_points = [(1015, 273), (1220, 273), (1355, 316), (1355, 485), (1220, 528), (1015, 528), (880, 528), (845, 444), (845, 401), (880, 316)]
    for (x1, y1), (x2, y2) in zip(loop_points, loop_points[1:] + [loop_points[0]], strict=True):
        shapes.append(Arrow(x1, y1, x2, y2))
    shapes.extend(
        [
            Arrow(545, 634, 710, 401, "prototype to sprint"),
            Arrow(845, 444, 880, 273, "return"),
            Box(760, 760, 620, 86, "Final Evaluation", fill=AMBER_LIGHT, title=True),
            Box(760, 900, 620, 86, "Documentation and Dissertation Evidence", fill=TEAL_LIGHT, title=True),
            Arrow(1035, 571, 1035, 760),
            Arrow(1070, 846, 1070, 900),
            Note(220, 980, "DSR establishes the research artefact; Agile controls iterative prototype implementation.", size=22),
        ]
    )
    diagrams.append(Diagram("3.1", "Hybrid Design Science Research and Agile Development Process Adopted for SERPS", "flowcharts", (1700, 1120), shapes, mmd_flow("3.1", dsr + agile + ["Final Evaluation", "Documentation and Dissertation Evidence"])))

    # 3.2
    trace = ["Stakeholder Requirements", "Functional Requirements", "Non-functional Requirements", "System Modules", "Implementation", "Testing", "Objective Verification"]
    diagrams.append(Diagram("3.2", "Requirements Traceability Model for SERPS", "architecture", (1500, 980), pipeline_shapes(trace, 500, 190, 500, 72, 28), mmd_flow("3.2", trace)))

    # 3.3 layered system architecture
    shapes = [
        Box(100, 180, 1400, 64, "Actors and Browsers: Candidate | Reviewer/Proctor | Administrator | System Administrator", fill=TEAL_LIGHT, title=True),
        Box(100, 275, 1400, 64, "Presentation Layer: Next.js candidate UI, reviewer console and admin dashboard", fill=WHITE),
        Box(100, 370, 420, 64, "REST API", fill=AMBER_LIGHT),
        Box(590, 370, 420, 64, "WebSocket / SSE", fill=AMBER_LIGHT),
        Box(1080, 370, 420, 64, "WebRTC Boundary", fill=AMBER_LIGHT),
        Box(100, 465, 1400, 64, "FastAPI Application Services", fill=TEAL_LIGHT, title=True),
    ]
    svc = ["Authentication", "Candidate / Exam", "Session Control", "Camera Manager", "Evidence Service", "Reports / Audit"]
    shapes.extend(grid_boxes(svc, 115, 560, 3, 420, 66, 55, 34))
    intel = ["EvidenceEvent", "CIE", "Agentic Decision Support", "IPIME", "Human Reviewer", "Final Institutional Decision"]
    shapes.extend(grid_boxes(intel, 100, 760, 6, 205, 72, 28, 20, TEAL_LIGHT))
    shapes.extend(
        [
            Box(100, 920, 420, 105, "PostgreSQL\nShared relational persistence", fill=GREY, title=True),
            Box(590, 920, 420, 105, "Evidence Storage\nSnapshots and artefacts", fill=GREY, title=True),
            Box(1080, 920, 420, 105, "Documentation / Reports\nTraceable exports", fill=GREY, title=True),
        ]
    )
    for x in [310, 800, 1290]:
        shapes.append(Arrow(x, 244, x, 275))
        shapes.append(Arrow(x, 339, x, 370))
        shapes.append(Arrow(x, 434, x, 465))
    shapes.append(Arrow(800, 529, 800, 560))
    shapes.append(Arrow(800, 694, 800, 760))
    for i in range(len(intel) - 1):
        x = 100 + i * (205 + 28)
        shapes.append(Arrow(x + 205, 796, x + 233, 796))
    shapes.extend([Arrow(305, 832, 310, 920, "persist", dashed=True), Arrow(800, 832, 800, 920, "evidence", dashed=True), Arrow(1265, 832, 1290, 920, "reports", dashed=True)])
    diagrams.append(Diagram("3.3", "Overall System Architecture of SERPS", "architecture", (1600, 1080), shapes, "flowchart TB\n  Actors[Actors and Browsers] --> Frontend[Presentation Layer]\n  Frontend --> Communication[REST / SSE / WebRTC]\n  Communication --> API[FastAPI Application Services]\n  API --> Evidence[EvidenceEvent]\n  Evidence --> CIE[Contextual Intelligence Engine]\n  CIE --> Agentic[Agentic Decision Support]\n  Agentic --> IPIME\n  IPIME --> Reviewer[Human Reviewer]\n  Reviewer --> Final[Final Institutional Decision]\n  API -. shared persistence .-> DB[(PostgreSQL)]\n  Evidence -. artefacts .-> Storage[Evidence Storage]"))

    # 3.4
    stages = ["Registration", "Consent", "Device Check", "Camera Permission", "Guided Multi-angle Capture", "Image Quality Assessment", "Liveness Detection", "Embedding Generation", "Biometric Profile", "Continuous Identity Assurance"]
    shapes = pipeline_shapes(stages, 170, 180, 430, 65, 18)
    poses = ["Front", "Left", "Right", "Slight Up", "Slight Down", "Centre"]
    shapes.extend(grid_boxes(poses, 760, 420, 3, 210, 75, 30, 30, TEAL_LIGHT))
    shapes.append(Arrow(600, 470, 760, 465, "pose targets"))
    shapes.append(Box(720, 755, 790, 120, "Continuous verification compares live identity evidence with enrolled biometric profile and emits structured identity events.", fill=AMBER_LIGHT))
    diagrams.append(Diagram("3.4", "Candidate Registration, Guided Multi-angle Facial Enrolment and Continuous Identity Assurance Architecture", "architecture", (1600, 1030), shapes, mmd_flow("3.4", stages)))

    # 3.5
    shapes = [Box(575, 190, 450, 80, "Camera Manager", fill=TEAL_LIGHT, title=True)]
    controls = ["Permissions", "Discovery", "Mode Selection", "Health Monitoring", "Device Status", "EvidenceEvent Generation"]
    shapes.extend(grid_boxes(controls, 120, 330, 3, 390, 75, 45, 35))
    shapes.extend([Box(270, 620, 350, 90, "Primary Camera\nCandidate View", fill=WHITE), Box(980, 620, 350, 90, "Secondary Camera\nEnvironment View", fill=WHITE), Box(270, 790, 350, 80, "Face / Identity / Gaze", fill=TEAL_LIGHT), Box(980, 790, 350, 80, "Room / Object Context", fill=TEAL_LIGHT), Box(575, 900, 450, 80, "Structured EvidenceEvent", fill=AMBER_LIGHT)])
    for x in [315, 750, 1185]:
        shapes.append(Arrow(800, 270, x, 330))
    shapes.extend([Arrow(445, 710, 445, 790), Arrow(1155, 710, 1155, 790), Arrow(445, 870, 710, 900), Arrow(1155, 870, 890, 900)])
    diagrams.append(Diagram("3.5", "Camera and Sensor Management Architecture", "architecture", (1550, 1060), shapes, "flowchart TB\n  Manager[Camera Manager] --> Permissions\n  Manager --> Discovery\n  Manager --> Modes[Mode Selection]\n  Manager --> Health[Health Monitoring]\n  Manager --> Primary[Primary Camera]\n  Manager --> Secondary[Secondary Camera]\n  Primary --> Evidence[EvidenceEvent]\n  Secondary --> Evidence"))

    # 3.6
    sources = ["Face", "Gaze", "Head Pose", "Audio", "Browser", "Object Detection", "Room Monitoring", "System Health"]
    shapes = grid_boxes(sources, 120, 210, 4, 300, 78, 45, 40, WHITE)
    shapes.append(Box(475, 560, 600, 90, "Evidence Standardisation", fill=TEAL_LIGHT, title=True))
    shapes.append(Box(540, 760, 470, 85, "Structured EvidenceEvent", fill=AMBER_LIGHT, title=True))
    for i in range(8):
        row, col = divmod(i, 4)
        shapes.append(Arrow(270 + col * 345, 288 + row * 118, 775, 560))
    shapes.append(Arrow(775, 650, 775, 760))
    diagrams.append(Diagram("3.6", "Multimodal Evidence Acquisition Architecture", "architecture", (1550, 950), shapes, "flowchart TB\n  Face --> Std[Evidence Standardisation]\n  Gaze --> Std\n  HeadPose --> Std\n  Audio --> Std\n  Browser --> Std\n  Objects --> Std\n  Room --> Std\n  Health --> Std\n  Std --> EvidenceEvent"))

    # 3.7 hero CIE
    shapes = [
        Box(120, 250, 300, 85, "EvidenceEvent", fill=AMBER_LIGHT, title=True),
        Box(520, 250, 360, 85, "Event Fusion Module", fill=TEAL_LIGHT, title=True),
        Box(980, 250, 360, 85, "Temporal Behaviour Memory", fill=WHITE, title=True),
        Box(520, 480, 360, 85, "Contextual Reasoning Module", fill=TEAL_LIGHT, title=True),
        Box(150, 690, 360, 85, "Risk Scoring Engine", fill=WHITE, title=True),
        Box(610, 690, 360, 85, "Explainability Interface", fill=WHITE, title=True),
        Box(1070, 690, 360, 85, "Contextual Assessment", fill=AMBER_LIGHT, title=True),
    ]
    shapes.extend([Arrow(420, 292, 520, 292), Arrow(880, 292, 980, 292), Arrow(1160, 335, 720, 480), Arrow(700, 335, 700, 480), Arrow(700, 565, 330, 690), Arrow(700, 565, 790, 690), Arrow(970, 732, 1070, 732), Arrow(510, 732, 610, 732)])
    diagrams.append(Diagram("3.7", "Internal Architecture of the Contextual Intelligence Engine", "architecture", (1550, 900), shapes, "flowchart LR\n  EvidenceEvent --> Fusion[Event Fusion Module]\n  Fusion --> Memory[Temporal Behaviour Memory]\n  Memory --> Reasoning[Contextual Reasoning Module]\n  Reasoning --> Risk[Risk Scoring Engine]\n  Reasoning --> Explain[Explainability Interface]\n  Risk <--> Explain\n  Explain --> Assessment[Contextual Assessment]\n  Risk --> Assessment"))

    # 3.8
    shapes = [Box(560, 190, 440, 80, "Contextual Assessment", fill=AMBER_LIGHT, title=True), Box(560, 360, 440, 80, "Agentic Reasoning", fill=TEAL_LIGHT, title=True)]
    rec = ["Continue Monitoring", "Request Re-authentication", "Notify Reviewer", "Escalate Incident"]
    shapes.extend(grid_boxes(rec, 150, 570, 4, 290, 85, 45, 20, WHITE))
    shapes.append(Box(560, 780, 440, 80, "Advisory Recommendation\nNot a final decision", fill=AMBER_LIGHT, title=True))
    shapes.extend([Arrow(780, 270, 780, 360), Arrow(780, 440, 780, 570)])
    for i in range(4):
        shapes.append(Arrow(295 + i * 335, 655, 780, 780))
    diagrams.append(Diagram("3.8", "Agentic Decision Support Architecture", "architecture", (1500, 960), shapes, "flowchart TB\n  Assessment --> Agentic[Agentic Reasoning]\n  Agentic --> Continue[Continue Monitoring]\n  Agentic --> Reauth[Request Re-authentication]\n  Agentic --> Notify[Notify Reviewer]\n  Agentic --> Escalate[Escalate Incident]\n  Continue --> Recommendation[Advisory Recommendation]"))

    # 3.9
    shapes = [
        Box(90, 190, 330, 74, "Agentic Recommendation", fill=AMBER_LIGHT, title=True),
        Box(520, 190, 330, 74, "Policy Evaluation", fill=TEAL_LIGHT, title=True),
        Box(950, 190, 330, 74, "Institutional Rules", fill=WHITE, title=True),
        Box(520, 330, 330, 74, "Policy Action Selection", fill=TEAL_LIGHT, title=True),
    ]
    actions = ["Warning", "Pause Examination", "Screen Shield", "Candidate Acknowledgement", "Reviewer Notification", "Escalation"]
    shapes.extend(grid_boxes(actions, 90, 495, 3, 390, 74, 60, 48, WHITE))
    shapes.extend(
        [
            Box(190, 760, 310, 78, "Incident Record", fill=AMBER_LIGHT, title=True),
            Box(620, 760, 310, 78, "Audit Log", fill=AMBER_LIGHT, title=True),
            Box(1050, 760, 310, 78, "Reviewer Workflow", fill=AMBER_LIGHT, title=True),
        ]
    )
    shapes.extend([Arrow(420, 227, 520, 227), Arrow(850, 227, 950, 227), Arrow(685, 264, 685, 330), Arrow(1115, 264, 850, 367)])
    for i in range(6):
        row, col = divmod(i, 3)
        sx = 285 + col * 450
        sy = 569 + row * 122
        shapes.extend([Arrow(sx, sy, 345, 760), Arrow(sx, sy, 775, 760), Arrow(sx, sy, 1205, 760)])
    diagrams.append(Diagram("3.9", "Institutional Policy and Incident Management Engine", "architecture", (1480, 940), shapes, "flowchart TB\n  Recommendation --> Evaluation[Policy Evaluation]\n  Rules[Institutional Rules] --> Evaluation\n  Evaluation --> Selection[Policy Action Selection]\n  Selection --> Warning\n  Selection --> Pause[Pause Examination]\n  Selection --> Shield[Screen Shield]\n  Selection --> Ack[Candidate Acknowledgement]\n  Selection --> Notify[Reviewer Notification]\n  Selection --> Escalation\n  Warning --> Incident[Incident Record]\n  Pause --> Incident\n  Shield --> Incident\n  Ack --> Incident\n  Notify --> Audit[Audit Log]\n  Escalation --> Reviewer[Reviewer Workflow]\n  Incident --> Reviewer\n  Audit --> Reviewer"))

    # 3.10
    pipeline = ["Detection", "Structured EvidenceEvent", "Contextual Intelligence Engine", "Agentic Recommendation", "Institutional Policy", "Candidate Acknowledgement\n(where required)", "Human Reviewer", "Final Institutional Decision", "Audit"]
    shapes = pipeline_shapes(pipeline, 515, 180, 520, 70, 20)
    shapes.append(Box(1075, 680, 330, 150, "Human governance boundary:\nSERPS supports review, but does not issue automatic misconduct decisions.", fill=AMBER_LIGHT))
    shapes.append(Arrow(1035, 715, 1075, 735, dashed=True))
    diagrams.append(Diagram("3.10", "Governance-aware Decision Pipeline", "flowcharts", (1500, 1100), shapes, mmd_flow("3.10", pipeline)))

    # 3.11
    shapes = [
        Box(100, 250, 400, 430, "Mode A\nSingle-camera CBT mode\n\nPrimary camera required\nSecondary not required\nCBT-centre limitation note", fill=TEAL_LIGHT, title=True),
        Box(575, 250, 400, 430, "Mode B\nDual-camera full mode\n\nPrimary required\nSecondary required\nFull remote-proctoring coverage", fill=WHITE, title=True),
        Box(1050, 250, 400, 430, "Mode C\nMirror-assisted low-resource mode\n\nPrimary required\nMirror required\nSecondary not required", fill=TEAL_LIGHT, title=True),
    ]
    diagrams.append(Diagram("3.11", "Deployment Modes Supported by SERPS", "architecture", (1550, 820), shapes, "flowchart LR\n  A[Mode A: Primary Camera] --- B[Mode B: Primary + Secondary]\n  B --- C[Mode C: Primary + Mirror]"))

    # 3.12
    shapes = [Box(100, 220, 280, 75, "Camera / Audio / Browser", fill=WHITE), Box(470, 220, 280, 75, "Detection Modules", fill=WHITE), Box(840, 220, 280, 75, "EvidenceEvent", fill=AMBER_LIGHT, title=True), Box(1220, 120, 280, 75, "Contextual Intelligence", fill=TEAL_LIGHT), Box(1220, 330, 280, 75, "PostgreSQL\nPersistence", fill=GREY), Box(840, 550, 280, 75, "Reports and Audit", fill=WHITE), Box(1220, 550, 280, 75, "Reviewer Console", fill=WHITE)]
    shapes.extend([Arrow(380, 257, 470, 257), Arrow(750, 257, 840, 257), Arrow(1120, 245, 1220, 165), Arrow(1120, 270, 1220, 365), Arrow(1360, 405, 980, 550, "read", dashed=True), Arrow(1120, 590, 1220, 590)])
    diagrams.append(Diagram("3.12", "High-Level Data Flow within SERPS", "flowcharts", (1600, 780), shapes, "flowchart LR\n  Sources --> Detection --> EvidenceEvent\n  EvidenceEvent --> CIE\n  EvidenceEvent -. persists .-> DB[(PostgreSQL)]\n  DB -. read .-> Reports\n  Reports --> Reviewer"))

    # 3.13 use case
    shapes = [
        Actor(120, 210, "Candidate"),
        Actor(120, 665, "Administrator"),
        Actor(1430, 210, "Reviewer/\nProctor"),
        Actor(1430, 665, "System\nAdministrator"),
        Box(310, 175, 930, 860, "SERPS System Boundary", fill="#F8FBFC", stroke=LINE, dashed=True),
    ]
    usecase_cols = {
        "candidate": [("Register", 420, 250), ("Give Consent", 650, 250), ("Enrol Biometrics", 880, 250), ("Authenticate", 1110, 250), ("Perform Device Check", 530, 390), ("Take Examination", 820, 390), ("Receive Warning", 1085, 390), ("Submit Acknowledgement", 790, 525)],
        "reviewer": [("Monitor Assigned Sessions", 870, 640), ("View Evidence", 1110, 640), ("Review Incident", 870, 760), ("Record Decision", 1110, 760), ("Request Re-authentication", 990, 880)],
        "admin": [("Manage Candidates", 420, 695), ("Manage Examinations", 620, 815), ("Assign Candidates", 420, 935), ("Configure Policies", 620, 575), ("Generate Reports", 620, 695)],
        "sys": [("Manage Institutions", 990, 995), ("Manage Users and Roles", 790, 995), ("Inspect Audit Logs", 1110, 525), ("Monitor System Health", 1110, 935)],
    }
    all_cases: dict[str, tuple[float, float]] = {}
    for group in usecase_cols.values():
        for label, x, y in group:
            all_cases[label] = (x, y)
            shapes.append(Ellipse(x, y, 195, 68, label, fill=TEAL_LIGHT if label in {"Take Examination", "Review Incident"} else WHITE))
    for label in ["Register", "Give Consent", "Enrol Biometrics", "Authenticate", "Perform Device Check", "Take Examination", "Receive Warning", "Submit Acknowledgement"]:
        x, y = all_cases[label]
        shapes.append(Arrow(225, 300, x, y + 34))
    for label in ["Manage Candidates", "Manage Examinations", "Assign Candidates", "Configure Policies", "Generate Reports"]:
        x, y = all_cases[label]
        shapes.append(Arrow(225, 755, x, y + 34))
    for label in ["Monitor Assigned Sessions", "View Evidence", "Review Incident", "Record Decision", "Request Re-authentication"]:
        x, y = all_cases[label]
        shapes.append(Arrow(1430, 300, x + 195, y + 34))
    for label in ["Manage Institutions", "Manage Users and Roles", "Inspect Audit Logs", "Monitor System Health"]:
        x, y = all_cases[label]
        shapes.append(Arrow(1430, 755, x + 195, y + 34))
    diagrams.append(Diagram("3.13", "Use Case Diagram of SERPS", "uml", (1600, 1120), shapes, "flowchart LR\n  Candidate((Candidate)) --- Register((Register))\n  Candidate --- Consent((Give Consent))\n  Candidate --- Biometrics((Enrol Biometrics))\n  Candidate --- Auth((Authenticate))\n  Candidate --- Exam((Take Examination))\n  Reviewer((Reviewer/Proctor)) --- Monitor((Monitor Assigned Sessions))\n  Reviewer --- Review((Review Incident))\n  Reviewer --- Decision((Record Decision))\n  Admin((Administrator)) --- ManageCandidates((Manage Candidates))\n  Admin --- Policies((Configure Policies))\n  SysAdmin((System Administrator)) --- Users((Manage Users and Roles))\n  SysAdmin --- Audit((Inspect Audit Logs))"))

    # 3.14 activity
    shapes = [
        Ellipse(685, 180, 190, 60, "Start", fill=DEEP_NAVY, stroke=DEEP_NAVY, color=WHITE),
        Box(535, 275, 490, 64, "Register / Authenticate Candidate", fill=WHITE),
        Box(535, 370, 490, 64, "Select Monitoring Mode and Run Device Checks", fill=WHITE),
        Box(535, 465, 490, 64, "Start Examination Session", fill=TEAL_LIGHT),
        Box(535, 560, 490, 64, "Generate Structured Evidence Events", fill=WHITE),
        Box(535, 655, 490, 64, "CIE Contextual Assessment", fill=TEAL_LIGHT),
        Box(535, 750, 490, 64, "Agentic Recommendation", fill=WHITE),
        Box(535, 845, 490, 64, "IPIME Policy Evaluation", fill=TEAL_LIGHT),
        Diamond(620, 955, 320, 130, "Acknowledgement Required?"),
        Box(125, 990, 380, 70, "No: Continue Monitoring / Examination Flow", fill=TEAL_LIGHT),
        Box(1065, 990, 380, 70, "Yes: Candidate Incident Acknowledgement", fill=AMBER_LIGHT),
        Box(1065, 1110, 380, 70, "Human Reviewer Inspects Evidence", fill=WHITE),
        Box(535, 1230, 490, 64, "Final Institutional Decision and Audit Report", fill=AMBER_LIGHT),
        Ellipse(685, 1335, 190, 60, "End", fill=DEEP_NAVY, stroke=DEEP_NAVY, color=WHITE),
    ]
    for y1, y2 in [(240, 275), (339, 370), (434, 465), (529, 560), (624, 655), (719, 750), (814, 845), (909, 955)]:
        shapes.append(Arrow(780, y1, 780, y2))
    shapes.extend(
        [
            Arrow(620, 1020, 505, 1025, "No"),
            Arrow(940, 1020, 1065, 1025, "Yes"),
            Arrow(1255, 1060, 1255, 1110),
            Arrow(1255, 1180, 780, 1230),
            Arrow(315, 1060, 780, 1230),
            Arrow(780, 1294, 780, 1335),
        ]
    )
    diagrams.append(Diagram("3.14", "Activity Diagram of SERPS", "uml", (1560, 1440), shapes, "flowchart TD\n  Start((Start)) --> Auth[Register / Authenticate Candidate]\n  Auth --> Device[Select Monitoring Mode and Run Device Checks]\n  Device --> Exam[Start Examination Session]\n  Exam --> Evidence[Generate Structured Evidence Events]\n  Evidence --> CIE[CIE Contextual Assessment]\n  CIE --> Agentic[Agentic Recommendation]\n  Agentic --> IPIME[IPIME Policy Evaluation]\n  IPIME --> Decision{Acknowledgement Required?}\n  Decision -- No --> Continue[Continue Monitoring / Examination Flow]\n  Decision -- Yes --> Ack[Candidate Incident Acknowledgement]\n  Ack --> Review[Human Reviewer Inspects Evidence]\n  Continue --> Final[Final Institutional Decision and Audit Report]\n  Review --> Final\n  Final --> End((End))"))

    # 3.15 sequence
    participants = ["Candidate", "React Frontend", "FastAPI", "Authentication", "Camera Manager", "Evidence Services", "CIE", "Agentic", "IPIME", "Reviewer", "PostgreSQL"]
    x_positions = [90 + i * 135 for i in range(len(participants))]
    shapes = []
    for p, x in zip(participants, x_positions, strict=True):
        shapes.append(Box(x, 190, 115, 55, p, fill=TEAL_LIGHT if p in {"CIE", "IPIME"} else WHITE))
        shapes.append(Arrow(x + 57, 245, x + 57, 950, dashed=True))
    messages = [(0, 1, 300, "start"), (1, 2, 350, "request"), (2, 3, 400, "authenticate"), (2, 4, 470, "camera control"), (4, 5, 540, "evidence"), (5, 10, 610, "persist"), (5, 6, 680, "events"), (6, 7, 750, "assessment"), (7, 8, 820, "recommendation"), (8, 9, 890, "policy response")]
    for a, b, y, label in messages:
        shapes.append(Arrow(x_positions[a] + 115, y, x_positions[b], y, label))
    diagrams.append(Diagram("3.15", "Sequence Diagram of SERPS", "uml", (1650, 1020), shapes, "sequenceDiagram\n  participant Candidate\n  participant React\n  participant FastAPI\n  participant Auth\n  participant Camera\n  participant Evidence\n  participant CIE\n  participant Agentic\n  participant IPIME\n  participant Reviewer\n  participant PostgreSQL\n  Candidate->>React: Start exam\n  React->>FastAPI: Request session\n  FastAPI->>Auth: Verify identity\n  Camera->>Evidence: Emit EvidenceEvent\n  Evidence->>PostgreSQL: Persist raw event\n  Evidence->>CIE: Submit event\n  CIE->>Agentic: Contextual assessment\n  Agentic->>IPIME: Recommendation\n  IPIME->>Reviewer: Policy workflow"))

    # 3.16 class
    class_items = [
        "Institution\ninstitution_id\nname",
        "User\nuser_id\nemail\nstatus",
        "Role\nrole_id\nname",
        "UserRole\nuser_id\nrole_id",
        "Candidate\ncandidate_id\nstudent/candidate ref",
        "Examination\nexamination_id\ntitle",
        "Assignment\nassignment_id\nstatus",
        "ExaminationSession\nsession_id\nstatus\nmonitoring_mode",
        "EvidenceEvent\nevent_id\nevent_type\nconfidence",
        "ContextualAssessment\nassessment_id\nrisk_score\nrisk_level",
        "Recommendation\nrecommendation_id\naction",
        "PolicyRule\npolicy_id\ncondition\naction",
        "Incident\nincident_id\npolicy_response",
        "Acknowledgement\nack_id\ncandidate_statement",
        "ReviewerAction\naction_id\ndecision\nrationale",
        "AuditLog\naudit_id\naction\ntimestamp",
    ]
    shapes = grid_boxes(class_items, 80, 200, 4, 335, 132, 38, 55, WHITE)
    centers = [(80 + (i % 4) * 373 + 167, 200 + (i // 4) * 187 + 66) for i in range(len(class_items))]
    rels = [(0, 1, "1..*"), (1, 3, "1..*"), (2, 3, "1..*"), (0, 4, "1..*"), (0, 5, "1..*"), (4, 6, "1..*"), (5, 6, "1..*"), (6, 7, "0..*"), (7, 8, "0..*"), (8, 9, "0..*"), (9, 10, "0..*"), (10, 12, "0..*"), (11, 12, "0..*"), (12, 13, "0..1"), (12, 14, "0..*"), (14, 15, "1..*")]
    for a, b, label in rels:
        shapes.append(Arrow(*centers[a], *centers[b], label=label, dashed=True))
    diagrams.append(Diagram("3.16", "Class Diagram of SERPS", "uml", (1600, 1020), shapes, "classDiagram\n  class Institution {+institution_id +name}\n  class User {+user_id +email +status}\n  class Role {+role_id +name}\n  class UserRole {+user_id +role_id}\n  class Candidate {+candidate_id +institution_reference}\n  class Examination {+examination_id +title}\n  class CandidateExaminationAssignment {+assignment_id +status}\n  class ExaminationSession {+session_id +status +monitoring_mode}\n  class EvidenceEvent {+event_id +event_type +confidence}\n  class ContextualAssessment {+assessment_id +risk_score +risk_level}\n  class Recommendation {+recommendation_id +action}\n  class PolicyRule {+policy_id +condition +action}\n  class Incident {+incident_id +policy_response}\n  class Acknowledgement {+ack_id +candidate_statement}\n  class ReviewerAction {+action_id +decision +rationale}\n  class AuditLog {+audit_id +action +timestamp}\n  Institution \"1\" --> \"many\" User\n  User \"1\" --> \"many\" UserRole\n  Role \"1\" --> \"many\" UserRole\n  Institution \"1\" --> \"many\" Candidate\n  Institution \"1\" --> \"many\" Examination\n  CandidateExaminationAssignment --> Candidate\n  CandidateExaminationAssignment --> Examination\n  ExaminationSession --> CandidateExaminationAssignment\n  ExaminationSession --> EvidenceEvent\n  EvidenceEvent --> ContextualAssessment\n  ContextualAssessment --> Recommendation\n  Recommendation --> Incident\n  PolicyRule --> Incident\n  Incident --> Acknowledgement\n  Incident --> ReviewerAction\n  ReviewerAction --> AuditLog"))

    # 3.17 component
    layer_y = [190, 310, 450, 590, 730, 870]
    shapes = [
        Box(570, layer_y[0], 420, 70, "Next.js Frontend", fill=TEAL_LIGHT, title=True),
        Box(570, layer_y[1], 420, 70, "FastAPI API Boundary", fill=AMBER_LIGHT, title=True),
    ]
    shapes.extend(grid_boxes(["Authentication", "Candidate", "Examination", "Session", "Camera"], 105, layer_y[2], 5, 250, 68, 34, 20, WHITE))
    shapes.extend(grid_boxes(["Vision", "Audio", "Evidence Services"], 270, layer_y[3], 3, 300, 68, 65, 20, WHITE))
    shapes.extend(grid_boxes(["CIE", "Agentic Decision Support", "IPIME"], 270, layer_y[4], 3, 300, 68, 65, 20, TEAL_LIGHT))
    shapes.extend(grid_boxes(["Reporting", "Audit", "PostgreSQL", "Evidence Storage"], 105, layer_y[5], 4, 300, 68, 45, 20, GREY))
    shapes.extend([Arrow(780, 260, 780, 310), Arrow(780, 380, 780, 450), Arrow(780, 518, 780, 590), Arrow(780, 658, 780, 730), Arrow(780, 798, 780, 870)])
    diagrams.append(Diagram("3.17", "Component Diagram of SERPS", "uml", (1500, 1040), shapes, "flowchart TB\n  Web[Next.js Frontend] --> API[FastAPI API]\n  API --> Auth[Authentication]\n  API --> Candidate\n  API --> Examination\n  API --> Session\n  API --> Camera\n  Camera --> Vision\n  Camera --> Audio\n  Vision --> Evidence[Evidence Services]\n  Audio --> Evidence\n  Evidence --> CIE\n  CIE --> Agentic[Agentic Decision Support]\n  Agentic --> IPIME\n  IPIME --> Reporting\n  IPIME --> Audit\n  Evidence --> PostgreSQL\n  Evidence --> Storage[Evidence Storage]"))

    # 3.18 deployment
    shapes = [
        Box(470, 185, 910, 610, "Docker Network / Optional Edge or Cloud Boundary", fill="#F8FBFC", stroke=LINE, dashed=True),
        Box(90, 210, 300, 90, "Candidate Device\nBrowser + camera/mic", fill=WHITE, title=True),
        Box(90, 360, 300, 90, "Reviewer Device\nBrowser console", fill=WHITE, title=True),
        Box(90, 510, 300, 90, "Administrator Device\nBrowser dashboard", fill=WHITE, title=True),
        Box(520, 250, 340, 110, "Web Application Container\nNext.js", fill=TEAL_LIGHT, title=True),
        Box(980, 250, 340, 110, "API Container\nFastAPI", fill=AMBER_LIGHT, title=True),
        Box(980, 430, 340, 110, "AI / Monitoring Services\nOpenCV, MediaPipe, YOLO adapters", fill=WHITE, title=True),
        Box(520, 640, 340, 100, "PostgreSQL Container\nSQL persistence", fill=GREY, title=True),
        Box(980, 640, 340, 100, "Evidence Storage\nsnapshots and artefacts", fill=GREY, title=True),
    ]
    shapes.extend(
        [
            Arrow(390, 255, 520, 305, "HTTPS"),
            Arrow(390, 405, 520, 305, "HTTPS"),
            Arrow(390, 555, 520, 305, "HTTPS"),
            Arrow(860, 305, 980, 305, "REST"),
            Arrow(390, 255, 980, 485, "WebRTC", dashed=True),
            Arrow(1150, 360, 1150, 430, "SSE/WebSocket"),
            Arrow(1100, 360, 690, 640, "SQL"),
            Arrow(1150, 540, 1150, 640, "evidence"),
        ]
    )
    diagrams.append(Diagram("3.18", "Deployment Diagram of SERPS", "uml", (1450, 860), shapes, "flowchart LR\n  CandidateDevice -->|HTTPS| Web[Web Application Container]\n  ReviewerDevice -->|HTTPS| Web\n  AdminDevice -->|HTTPS| Web\n  Web -->|REST| API[API Container]\n  CandidateDevice -. WebRTC .-> AI[AI / Monitoring Services]\n  API <--> |SSE / WebSocket| AI\n  API -->|SQL| DB[(PostgreSQL Container)]\n  AI -->|Evidence storage protocol| Storage[Evidence Storage]\n  subgraph DockerNetwork[Docker Network / Optional Edge or Cloud Boundary]\n    Web\n    API\n    AI\n    DB\n    Storage\n  end"))

    # 3.19 from SQLAlchemy metadata
    shapes = []
    tables = list(Base.metadata.sorted_tables)
    if not tables:
        shapes.append(Box(450, 300, 600, 120, "No SQLAlchemy tables detected", fill=AMBER_LIGHT))
    else:
        for i, table in enumerate(tables):
            cols = []
            for col in table.columns:
                if col.primary_key or col.foreign_keys or col.name in {"email", "name", "title", "status", "role_name", "event_type", "confidence", "monitoring_mode", "created_at"}:
                    markers = []
                    if col.primary_key:
                        markers.append("PK")
                    if col.foreign_keys:
                        markers.append("FK")
                    marker = f" ({'/'.join(markers)})" if markers else ""
                    cols.append(f"{col.name}{marker}")
            text = wrap_identifier(table.name, 24) + "\n" + "\n".join(cols[:10])
            row, col_idx = divmod(i, 4)
            shapes.append(Box(55 + col_idx * 440, 190 + row * 300, 400, 260, text, fill=TEAL_LIGHT if i == 0 else WHITE, title=True))
    rows = max(1, math.ceil(max(len(tables), 1) / 4))
    diagrams.append(
        Diagram(
            "3.19",
            "Entity Relationship Diagram of SERPS Database",
            "architecture",
            (1840, max(920, 250 + rows * 300)),
            shapes,
            erd_mermaid_from_metadata(full=False),
            notes=[
                "Dissertation ERD generated from implemented SQLAlchemy metadata using primary keys, key foreign keys and selected major attributes. Full technical schema is exported separately.",
            ],
        )
    )

    # 3.20 API hub
    shapes = [Box(575, 180, 400, 80, "React / Next.js", fill=TEAL_LIGHT, title=True), Box(575, 330, 400, 80, "REST API / WebSocket", fill=AMBER_LIGHT), Box(575, 480, 400, 80, "FastAPI Hub", fill=TEAL_LIGHT, title=True)]
    services = ["Authentication", "Candidates", "Examinations", "Camera", "Identity", "Evidence", "CIE", "Agentic", "IPIME", "Reporting", "Audit"]
    shapes.extend(grid_boxes(services, 80, 680, 4, 315, 70, 45, 40, WHITE))
    shapes.extend([Box(1120, 470, 320, 90, "PostgreSQL", fill=GREY), Box(1120, 580, 320, 90, "Evidence Storage", fill=GREY)])
    shapes.extend([Arrow(775, 260, 775, 330), Arrow(775, 410, 775, 480), Arrow(975, 520, 1120, 515), Arrow(975, 540, 1120, 625)])
    for i in range(len(services)):
        row, col = divmod(i, 4)
        shapes.append(Arrow(775, 560, 237 + col * 360, 680 + row * 110))
    diagrams.append(Diagram("3.20", "API Interaction Diagram of SERPS", "api", (1550, 1050), shapes, "flowchart TB\n  React --> Boundary[REST API / WebSocket]\n  Boundary --> FastAPI[FastAPI Hub]\n  FastAPI --> Authentication\n  FastAPI --> Candidates\n  FastAPI --> Examinations\n  FastAPI --> Camera\n  FastAPI --> Identity\n  FastAPI --> Evidence\n  FastAPI --> CIE\n  FastAPI --> Agentic\n  FastAPI --> IPIME\n  FastAPI --> Reporting\n  FastAPI --> Audit\n  FastAPI -.-> PostgreSQL\n  FastAPI -.-> Storage[Evidence Storage]"))

    # 3.21 technology stack
    layers = [
        "Presentation\nNext.js / React / TypeScript\nImplemented foundation",
        "API / Application\nFastAPI, Pydantic\nImplemented foundation",
        "Real-time Communication\nWebSocket / SSE / WebRTC\nPlanned interfaces",
        "AI / ML\nOpenCV, MediaPipe, YOLO\nPlanned POP migration",
        "Intelligence / Governance\nCIE, Agentic, IPIME\nPOC implemented; POP migration pending",
        "Persistence\nSQLAlchemy, Alembic, PostgreSQL\nConfigured and migration-verified",
        "Infrastructure / DevOps\nDocker Compose, GitHub Actions\nImplemented foundation",
    ]
    diagrams.append(Diagram("3.21", "Technology Stack of SERPS", "technology", (1500, 1050), pipeline_shapes(layers, 440, 185, 620, 95, 25), mmd_flow("3.21", layers)))

    return diagrams


def checksum(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()[:16]


def rel(path: Path) -> str:
    return str(path.relative_to(ROOT)).replace("\\", "/")


def git_commit_hash() -> str:
    result = subprocess.run(
        ["git", "rev-parse", "HEAD"],
        cwd=ROOT,
        capture_output=True,
        text=True,
        check=False,
    )
    return result.stdout.strip() if result.returncode == 0 else "unknown"


def tool_version(command: list[str]) -> str:
    result = subprocess.run(command, cwd=ROOT, capture_output=True, text=True, check=False)
    if result.returncode != 0:
        return "unavailable"
    return (result.stdout or result.stderr).strip().splitlines()[0]


def figure_orientation(diagram: Diagram) -> str:
    width, height = diagram.canvas
    if width / max(height, 1) >= 1.35:
        return "Landscape"
    if height / max(width, 1) >= 1.2:
        return "Portrait"
    return "Square / flexible"


def visual_status(diagram: Diagram) -> str:
    if diagram.number in {"3.16", "3.19"}:
        return "PASS WITH MINOR LIMITATION"
    return "PASS"


def wrap_identifier(value: str, width: int = 22) -> str:
    if len(value) <= width:
        return value
    parts = value.split("_")
    lines: list[str] = []
    current = ""
    for part in parts:
        candidate = part if not current else f"{current}_{part}"
        if len(candidate) <= width:
            current = candidate
        else:
            if current:
                lines.append(current)
            current = part
    if current:
        lines.append(current)
    return "\n".join(lines)


def validate_mono_png(path: Path) -> tuple[bool, str]:
    with Image.open(path) as image:
        rgba = image.convert("RGBA")
        has_transparency = False
        coloured_pixels = 0
        sampled_pixels = 0
        for r, g, b, a in rgba.getdata():
            if a == 0:
                has_transparency = True
                continue
            if a < 255:
                has_transparency = True
            sampled_pixels += 1
            if max(r, g, b) - min(r, g, b) > 8:
                coloured_pixels += 1
        if not has_transparency:
            return False, "No transparent pixels detected"
        if sampled_pixels and coloured_pixels / sampled_pixels > 0.002:
            return False, "Detected non-monochrome coloured pixels"
    return True, "Transparent monochrome PNG"


def write_full_schema_technical_erd() -> dict[str, str]:
    safe_name = "Figure3_19_full_schema_technical"
    mmd_path = OUT / "source" / "authoritative" / f"{safe_name}.mmd"
    svg_path = OUT / "svg" / f"{safe_name}.svg"
    mmd_path.write_text(erd_mermaid_from_metadata(full=True), encoding="utf-8")

    tables = list(Base.metadata.sorted_tables)
    columns = 3
    box_w = 520
    row_h = 320
    width = columns * box_w + 120
    rows = max(1, math.ceil(max(len(tables), 1) / columns))
    height = 180 + rows * row_h
    svg = [
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{height}" viewBox="0 0 {width} {height}">',
        '<style>text{font-family:Arial, sans-serif;fill:#042A3A}.title{font-weight:bold;font-size:26px}.table{font-weight:bold;font-size:18px}.col{font-size:13px}.box{fill:#FFFFFF;stroke:#0F8B8D;stroke-width:2}.header{fill:#DDF7F5;stroke:#0F8B8D;stroke-width:2}</style>',
        f'<text x="60" y="55" class="title">Figure 3.19A: Full Technical Schema ERD</text>',
        '<text x="60" y="88" class="col">Generated from SQLAlchemy metadata. This technical artefact preserves all columns for implementation traceability.</text>',
    ]
    if not tables:
        svg.append('<rect x="60" y="130" width="700" height="100" rx="14" class="box"/>')
        svg.append('<text x="90" y="185" class="table">No SQLAlchemy tables detected</text>')
    for i, table in enumerate(tables):
        row, col_idx = divmod(i, columns)
        x = 60 + col_idx * box_w
        y = 130 + row * row_h
        svg.append(f'<rect x="{x}" y="{y}" width="470" height="285" rx="12" class="box"/>')
        svg.append(f'<rect x="{x}" y="{y}" width="470" height="42" rx="12" class="header"/>')
        for line_no, table_name_line in enumerate(wrap_identifier(table.name, 32).splitlines()):
            svg.append(f'<text x="{x + 18}" y="{y + 25 + line_no * 18}" class="table">{escape(table_name_line)}</text>')
        for j, column in enumerate(table.columns):
            markers = []
            if column.primary_key:
                markers.append("PK")
            if column.foreign_keys:
                markers.append("FK")
            suffix = f" ({'/'.join(markers)})" if markers else ""
            label = f"{column.name}: {column.type}{suffix}"
            if len(label) > 56:
                label = label[:53] + "..."
            svg.append(f'<text x="{x + 18}" y="{y + 70 + j * 17}" class="col">{escape(label)}</text>')
            if j >= 11 and len(table.columns) > 13:
                svg.append(f'<text x="{x + 18}" y="{y + 70 + (j + 1) * 17}" class="col">... {len(table.columns) - j - 1} more columns</text>')
                break
    svg.append("</svg>")
    svg_path.write_text("\n".join(svg), encoding="utf-8")
    return {
        "source": rel(mmd_path),
        "svg": rel(svg_path),
        "source_sha256": checksum(mmd_path),
        "svg_sha256": checksum(svg_path),
        "purpose": "Full schema technical reference; not the primary dissertation figure.",
    }


def write_visual_review(diagrams: list[Diagram], artefacts: dict[str, dict[str, str]]) -> None:
    lines = [
        "# Chapter Three Diagram Visual Review",
        "",
        f"Generated at: {datetime.now(timezone.utc).isoformat()}",
        "",
        "This review records the visual-readiness status of the official Chapter Three figure variants. Colour and monochrome-transparent variants are generated from the same authoritative source for dissertation traceability.",
        "",
        "## Review Summary",
        "",
        "- Official colour SVG/PNG variants are generated for all 21 figures.",
        "- Official monochrome transparent SVG/PNG variants are generated for all 21 figures.",
        "- Existing legacy outputs remain available in the original `png/`, `svg/` and `source/` folders.",
        "- Figure 3.19 has a readable dissertation ERD plus a separate full technical schema artefact.",
        "",
        "## Figure Status",
        "",
    ]
    for d in diagrams:
        status = visual_status(d)
        orientation = figure_orientation(d)
        mono_ok = artefacts[d.number].get("mono_png_valid", "unknown")
        lines.append(f"- Figure {d.number}: **{status}**")
        lines.append(f"  - Title: {d.title}")
        lines.append(f"  - Recommended Word orientation: {orientation}")
        lines.append(f"  - Monochrome transparency check: {mono_ok}")
        if d.notes:
            for note in d.notes:
                lines.append(f"  - Note: {note}")
        if status == "PASS WITH MINOR LIMITATION":
            lines.append("  - Limitation: The figure is technically dense; use landscape placement or appendix zoom if the dissertation template constrains width.")
    lines.extend(
        [
            "",
            "## Sprint 2 Hardening Tasks",
            "",
            "- Keep the Sprint 2 authentication/session milestone untagged until the user explicitly approves the milestone.",
            "- Maintain generated dissertation figures as implementation-derived artefacts rather than manually edited images.",
            "- Re-run this generator after schema or architecture changes before using Chapter Three figures in Word.",
        ]
    )
    (OUT / "diagram_visual_review.md").write_text("\n".join(lines) + "\n", encoding="utf-8")


def write_index(diagrams: list[Diagram], artefacts: dict[str, dict[str, str]]) -> None:
    lines = ["# Chapter Three Figure Index", ""]
    for d in diagrams:
        files = artefacts[d.number]
        lines.append(f"- Figure {d.number}: {d.title}")
        lines.append(f"  - Source: `source/{d.safe_name}.mmd`")
        lines.append(f"  - SVG: `svg/{d.safe_name}.svg`")
        lines.append(f"  - PNG: `png/{d.safe_name}.png`")
        lines.append(f"  - Authoritative source: `{files['authoritative_source']}`")
        lines.append(f"  - Official colour SVG: `{files['colour_svg']}`")
        lines.append(f"  - Official colour PNG: `{files['colour_png']}`")
        lines.append(f"  - Official monochrome transparent SVG: `{files['mono_svg']}`")
        lines.append(f"  - Official monochrome transparent PNG: `{files['mono_png']}`")
        lines.append(f"  - Recommended Word orientation: {files['recommended_orientation']}")
    (OUT / "figure_index.md").write_text("\n".join(lines) + "\n", encoding="utf-8")

    captions = ["# Chapter Three Captions", ""]
    for d in diagrams:
        captions.append(f"**Figure {d.number}: {d.title}.**")
        captions.append(f"Source: {d.source}.")
        captions.append("")
    (OUT / "captions.md").write_text("\n".join(captions), encoding="utf-8")

    manifest = {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "generator": "scripts/docs/generate_chapter3_diagrams.py",
        "serps_version": "chapter-three-diagram-remediation",
        "git_commit": git_commit_hash(),
        "tool_versions": {
            "python": tool_version(["python", "--version"]),
            "pillow": Image.__version__,
        },
        "figures": artefacts,
    }
    (OUT / "manifest.json").write_text(json.dumps(manifest, indent=2), encoding="utf-8")


def validate(diagrams: list[Diagram], artefacts: dict[str, dict[str, str]]) -> None:
    colour_png_count = len(list((OUT / "png" / "colour").glob("Figure3_*_colour.png")))
    colour_svg_count = len(list((OUT / "svg" / "colour").glob("Figure3_*_colour.svg")))
    mono_png_count = len(list((OUT / "png" / "mono_transparent").glob("Figure3_*_mono_transparent.png")))
    mono_svg_count = len(list((OUT / "svg" / "mono_transparent").glob("Figure3_*_mono_transparent.svg")))
    lines = [
        "# Chapter Three Diagram Validation Report",
        "",
        f"Generated at: {datetime.now(timezone.utc).isoformat()}",
        "",
        "## Summary",
        "",
        f"- Figures requested: 21",
        f"- Figures generated: {len(diagrams)}",
        "- Editable Mermaid sources generated for every figure.",
        "- SVG exports generated for every figure.",
        "- High-resolution PNG exports generated for every figure with 300 DPI metadata.",
        f"- Official colour PNG variants: {colour_png_count}",
        f"- Official colour SVG variants: {colour_svg_count}",
        f"- Official monochrome transparent PNG variants: {mono_png_count}",
        f"- Official monochrome transparent SVG variants: {mono_svg_count}",
        "- Draw.io exports were not generated in this urgent sprint; Mermaid sources remain editable and SVG is the publication authority.",
        "",
        "## Validation Results",
        "",
    ]
    for d in diagrams:
        files = artefacts[d.number]
        ok = all((ROOT / files[key]).exists() for key in ("source", "category_source", "svg", "png", "authoritative_source", "colour_svg", "colour_png", "mono_svg", "mono_png"))
        lines.append(f"- Figure {d.number}: {'PASS' if ok else 'NEEDS REVIEW'} - {d.title}")
        lines.append(f"  - Visual status: {files['visual_review_status']}")
        lines.append(f"  - Recommended Word orientation: {files['recommended_orientation']}")
        lines.append(f"  - Monochrome check: {files['mono_png_valid']}")
        for note in d.notes:
            lines.append(f"  - Note: {note}")
    lines.extend(
        [
            "",
            "## Figure 3.19 Schema Status",
            "",
            "Figure 3.19 was generated from the current SQLAlchemy metadata. The present POP schema includes EvidenceEvent persistence plus Sprint 2 institution, user, role, candidate, examination, assignment, session, authentication, refresh-token and audit-log tables.",
            "",
            "## Architecture Consistency Checks",
            "",
            "- Detection modules are shown as evidence producers only.",
            "- CIE is shown as the central reasoning layer.",
            "- Agentic Decision Support is shown as advisory only.",
            "- IPIME is shown as institutional workflow/policy handling, not final decision-making.",
            "- Human Reviewer and final institutional decision boundaries are explicit.",
            "- PostgreSQL is represented as shared persistence, not a reasoning component.",
            "- React/Next.js is represented as presentation/control surface, not as CIE or AI business logic.",
            "",
            "## Sprint 2 Tagging Note",
            "",
            "- The `v0.2.0-auth-session-foundation` tag was intentionally not created in this remediation sprint.",
        ]
    )
    (OUT / "diagram_validation_report.md").write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    for subdir in SUBDIRS:
        (OUT / subdir).mkdir(parents=True, exist_ok=True)
    diagrams = build_diagrams()
    artefacts: dict[str, dict[str, str]] = {}
    for d in diagrams:
        mmd_path = OUT / "source" / f"{d.safe_name}.mmd"
        svg_path = OUT / "svg" / f"{d.safe_name}.svg"
        png_path = OUT / "png" / f"{d.safe_name}.png"
        legacy_mmd = OUT / "source" / "legacy" / f"{d.safe_name}.mmd"
        authoritative_mmd = OUT / "source" / "authoritative" / f"{d.safe_name}.mmd"
        colour_svg = OUT / "svg" / "colour" / f"{d.safe_name}_colour.svg"
        colour_png = OUT / "png" / "colour" / f"{d.safe_name}_colour.png"
        mono_svg = OUT / "svg" / "mono_transparent" / f"{d.safe_name}_mono_transparent.svg"
        mono_png = OUT / "png" / "mono_transparent" / f"{d.safe_name}_mono_transparent.png"
        category_mmd = OUT / d.category / f"{d.safe_name}.mmd"
        if mmd_path.exists() and not legacy_mmd.exists():
            shutil.copyfile(mmd_path, legacy_mmd)
        write_mmd(d, mmd_path)
        write_mmd(d, category_mmd)
        write_mmd(d, authoritative_mmd)
        render_svg(d, svg_path)
        render_png(d, png_path)
        render_svg(d, colour_svg, COLOUR_THEME)
        render_png(d, colour_png, COLOUR_THEME)
        render_svg(d, mono_svg, MONO_THEME)
        render_png(d, mono_png, MONO_THEME)
        mono_ok, mono_message = validate_mono_png(mono_png)
        artefacts[d.number] = {
            "source": rel(mmd_path),
            "legacy_source": rel(legacy_mmd) if legacy_mmd.exists() else "",
            "category_source": rel(category_mmd),
            "authoritative_source": rel(authoritative_mmd),
            "svg": rel(svg_path),
            "png": rel(png_path),
            "colour_svg": rel(colour_svg),
            "colour_png": rel(colour_png),
            "mono_svg": rel(mono_svg),
            "mono_png": rel(mono_png),
            "source_sha256": checksum(mmd_path),
            "authoritative_source_sha256": checksum(authoritative_mmd),
            "svg_sha256": checksum(svg_path),
            "png_sha256": checksum(png_path),
            "colour_svg_sha256": checksum(colour_svg),
            "colour_png_sha256": checksum(colour_png),
            "mono_svg_sha256": checksum(mono_svg),
            "mono_png_sha256": checksum(mono_png),
            "mono_png_valid": "PASS" if mono_ok else f"NEEDS REVIEW - {mono_message}",
            "recommended_orientation": figure_orientation(d),
            "visual_review_status": visual_status(d),
        }
    artefacts["3.19A"] = write_full_schema_technical_erd()
    write_index(diagrams, artefacts)
    write_visual_review(diagrams, artefacts)
    validate(diagrams, artefacts)
    print(f"Generated {len(diagrams)} Chapter Three figures in {OUT}")


if __name__ == "__main__":
    main()
