"""Generate Chapter Three dissertation diagrams for SERPS POP.

The generator intentionally uses implementation-owned definitions and the
current SQLAlchemy metadata for Figure 3.19. Mermaid source files are retained
as editable diagram sources, while SVG/PNG exports are generated by a small
deterministic renderer so the sprint does not depend on a local Mermaid CLI.
"""

from __future__ import annotations

import hashlib
import json
import math
import os
import re
import textwrap
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Iterable
from xml.sax.saxutils import escape

from PIL import Image, ImageDraw, ImageFont

from serps_pop.evidence import models as _evidence_models  # noqa: F401
from serps_pop.identity import models as _identity_models  # noqa: F401
from serps_pop.infrastructure.database import Base


ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / "docs" / "dissertation" / "chapter3"
SUBDIRS = [
    "architecture",
    "uml",
    "flowcharts",
    "api",
    "technology",
    "png",
    "svg",
    "source",
]

NAVY = "#073B4C"
DEEP_NAVY = "#042A3A"
TEAL = "#0F8B8D"
TEAL_LIGHT = "#DDF7F5"
WHITE = "#FFFFFF"
GREY = "#EEF3F6"
MUTED = "#60717C"
LINE = "#7FA9B5"
AMBER = "#F2B84B"
AMBER_LIGHT = "#FFF4D6"
GREEN = "#2EAD6B"
RED = "#C94C4C"


@dataclass(frozen=True)
class Box:
    x: float
    y: float
    w: float
    h: float
    text: str
    fill: str = WHITE
    stroke: str = TEAL
    color: str = DEEP_NAVY
    title: bool = False
    dashed: bool = False
    radius: float = 18


@dataclass(frozen=True)
class Ellipse:
    x: float
    y: float
    w: float
    h: float
    text: str
    fill: str = WHITE
    stroke: str = TEAL
    color: str = DEEP_NAVY


@dataclass(frozen=True)
class Actor:
    x: float
    y: float
    text: str


@dataclass(frozen=True)
class Arrow:
    x1: float
    y1: float
    x2: float
    y2: float
    label: str = ""
    color: str = LINE
    dashed: bool = False


@dataclass(frozen=True)
class Note:
    x: float
    y: float
    text: str
    color: str = MUTED
    size: int = 22


Shape = Box | Ellipse | Actor | Arrow | Note


@dataclass
class Diagram:
    number: str
    title: str
    category: str
    canvas: tuple[int, int]
    shapes: list[Shape]
    mmd: str
    source: str = "Author's Architecture (2026)"
    notes: list[str] = field(default_factory=list)

    @property
    def safe_name(self) -> str:
        safe_title = re.sub(r"[^A-Za-z0-9]+", "_", self.title).strip("_")
        return f"Figure{self.number.replace('.', '_')}_{safe_title}"


def font(size: int, bold: bool = False) -> ImageFont.FreeTypeFont:
    candidates = [
        "C:/Windows/Fonts/arialbd.ttf" if bold else "C:/Windows/Fonts/arial.ttf",
        "C:/Windows/Fonts/segoeuib.ttf" if bold else "C:/Windows/Fonts/segoeui.ttf",
    ]
    for candidate in candidates:
        if Path(candidate).exists():
            return ImageFont.truetype(candidate, size)
    return ImageFont.load_default()


def wrap_text(text: str, max_chars: int) -> list[str]:
    lines: list[str] = []
    for paragraph in text.split("\n"):
        if not paragraph:
            lines.append("")
        else:
            lines.extend(textwrap.wrap(paragraph, width=max_chars, break_long_words=False))
    return lines


def draw_wrapped(
    draw: ImageDraw.ImageDraw,
    xy: tuple[float, float],
    text: str,
    fill: str,
    fnt: ImageFont.FreeTypeFont,
    max_width: float,
    align: str = "center",
) -> None:
    avg = max(fnt.getlength("ABCDEFGHIJKLMNOPQRSTUVWXYZ") / 26, 8)
    lines = wrap_text(text, max(8, int(max_width / avg)))
    line_h = fnt.size + 7
    x, y = xy
    for line in lines:
        bbox = draw.textbbox((0, 0), line, font=fnt)
        width = bbox[2] - bbox[0]
        tx = x
        if align == "center":
            tx = x - width / 2
        elif align == "right":
            tx = x - width
        draw.text((tx, y), line, fill=fill, font=fnt)
        y += line_h


def arrow_head(x1: float, y1: float, x2: float, y2: float, size: float = 16) -> list[tuple[float, float]]:
    angle = math.atan2(y2 - y1, x2 - x1)
    left = angle + math.pi * 0.82
    right = angle - math.pi * 0.82
    return [
        (x2, y2),
        (x2 + size * math.cos(left), y2 + size * math.sin(left)),
        (x2 + size * math.cos(right), y2 + size * math.sin(right)),
    ]


def draw_arrow(draw: ImageDraw.ImageDraw, arrow: Arrow, scale: int = 1) -> None:
    x1, y1, x2, y2 = [v * scale for v in (arrow.x1, arrow.y1, arrow.x2, arrow.y2)]
    color = arrow.color
    width = 4 * scale
    if arrow.dashed:
        steps = max(8, int(math.hypot(x2 - x1, y2 - y1) / (18 * scale)))
        for i in range(steps):
            if i % 2 == 0:
                sx = x1 + (x2 - x1) * i / steps
                sy = y1 + (y2 - y1) * i / steps
                ex = x1 + (x2 - x1) * (i + 1) / steps
                ey = y1 + (y2 - y1) * (i + 1) / steps
                draw.line((sx, sy, ex, ey), fill=color, width=width)
    else:
        draw.line((x1, y1, x2, y2), fill=color, width=width)
    draw.polygon([(x * scale, y * scale) for x, y in arrow_head(arrow.x1, arrow.y1, arrow.x2, arrow.y2)], fill=color)
    if arrow.label:
        mid = ((x1 + x2) / 2, (y1 + y2) / 2 - 18 * scale)
        draw.text(mid, arrow.label, fill=DEEP_NAVY, font=font(18 * scale), anchor="mm")


def mermaid_type(column_type: object) -> str:
    raw = column_type.__class__.__name__.lower()
    if "integer" in raw:
        return "int"
    if "float" in raw or "numeric" in raw:
        return "float"
    if "boolean" in raw:
        return "boolean"
    if "date" in raw or "time" in raw:
        return "datetime"
    return "string"


def erd_mermaid_from_metadata() -> str:
    lines = ["erDiagram"]
    for table in Base.metadata.sorted_tables:
        lines.append(f"  {table.name} {{")
        for column in table.columns:
            markers = []
            if column.primary_key:
                markers.append("PK")
            if column.foreign_keys:
                markers.append("FK")
            marker_text = f" {' '.join(markers)}" if markers else ""
            lines.append(f"    {mermaid_type(column.type)} {column.name}{marker_text}")
        lines.append("  }")
    for table in Base.metadata.sorted_tables:
        for foreign_key in table.foreign_keys:
            referred = foreign_key.column.table.name
            lines.append(f"  {referred} ||--o{{ {table.name} : references")
    return "\n".join(lines)


def render_png(diagram: Diagram, path: Path) -> None:
    w, h = diagram.canvas
    scale = 2
    img = Image.new("RGB", (w * scale, h * scale), GREY)
    draw = ImageDraw.Draw(img)
    draw.rounded_rectangle((50 * scale, 45 * scale, (w - 50) * scale, 145 * scale), radius=26 * scale, fill=NAVY)
    draw.text((75 * scale, 72 * scale), f"Figure {diagram.number}", fill=TEAL_LIGHT, font=font(28 * scale, True))
    draw.text((75 * scale, 105 * scale), diagram.title, fill=WHITE, font=font(25 * scale, True))

    for shape in diagram.shapes:
        if isinstance(shape, Box):
            rect = tuple(v * scale for v in (shape.x, shape.y, shape.x + shape.w, shape.y + shape.h))
            shadow = (rect[0] + 5 * scale, rect[1] + 6 * scale, rect[2] + 5 * scale, rect[3] + 6 * scale)
            draw.rounded_rectangle(shadow, radius=shape.radius * scale, fill="#D9E4EA")
            dash = None
            draw.rounded_rectangle(rect, radius=shape.radius * scale, fill=shape.fill, outline=shape.stroke, width=3 * scale)
            fnt = font((24 if shape.title else 21) * scale, shape.title)
            lines = wrap_text(shape.text, max(10, int(shape.w / 14)))
            text_h = len(lines) * (fnt.size + 7)
            draw_wrapped(
                draw,
                ((shape.x + shape.w / 2) * scale, (shape.y + shape.h / 2 - text_h / (2 * scale)) * scale),
                shape.text,
                shape.color,
                fnt,
                shape.w * scale - 35 * scale,
            )
        elif isinstance(shape, Ellipse):
            rect = tuple(v * scale for v in (shape.x, shape.y, shape.x + shape.w, shape.y + shape.h))
            draw.ellipse(rect, fill=shape.fill, outline=shape.stroke, width=3 * scale)
            draw_wrapped(
                draw,
                ((shape.x + shape.w / 2) * scale, (shape.y + shape.h / 2 - 22) * scale),
                shape.text,
                shape.color,
                font(20 * scale, True),
                shape.w * scale - 25 * scale,
            )
        elif isinstance(shape, Actor):
            x, y = shape.x * scale, shape.y * scale
            draw.ellipse((x - 18 * scale, y, x + 18 * scale, y + 36 * scale), outline=DEEP_NAVY, width=4 * scale)
            draw.line((x, y + 36 * scale, x, y + 95 * scale), fill=DEEP_NAVY, width=4 * scale)
            draw.line((x - 42 * scale, y + 60 * scale, x + 42 * scale, y + 60 * scale), fill=DEEP_NAVY, width=4 * scale)
            draw.line((x, y + 95 * scale, x - 38 * scale, y + 145 * scale), fill=DEEP_NAVY, width=4 * scale)
            draw.line((x, y + 95 * scale, x + 38 * scale, y + 145 * scale), fill=DEEP_NAVY, width=4 * scale)
            draw_wrapped(draw, (x, y + 155 * scale), shape.text, DEEP_NAVY, font(20 * scale, True), 150 * scale)
        elif isinstance(shape, Arrow):
            draw_arrow(draw, shape, scale)
        elif isinstance(shape, Note):
            draw_wrapped(draw, (shape.x * scale, shape.y * scale), shape.text, shape.color, font(shape.size * scale), 420 * scale)

    draw.text((w * scale - 70 * scale, h * scale - 45 * scale), "SERPS Architecture", fill=MUTED, font=font(18 * scale), anchor="ra")
    img.save(path, dpi=(300, 300))


def svg_text(x: float, y: float, text: str, size: int, color: str, weight: str = "400", anchor: str = "middle") -> str:
    spans = []
    for i, line in enumerate(wrap_text(text, 32)):
        spans.append(
            f'<text x="{x:.1f}" y="{y + i * (size + 7):.1f}" text-anchor="{anchor}" '
            f'font-family="Segoe UI, Arial, sans-serif" font-size="{size}" font-weight="{weight}" fill="{color}">{escape(line)}</text>'
        )
    return "\n".join(spans)


def render_svg(diagram: Diagram, path: Path) -> None:
    w, h = diagram.canvas
    out = [
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{w}" height="{h}" viewBox="0 0 {w} {h}">',
        "<defs>",
        '<marker id="arrow" markerWidth="12" markerHeight="12" refX="10" refY="6" orient="auto" markerUnits="strokeWidth"><path d="M2,2 L10,6 L2,10 z" fill="#7FA9B5"/></marker>',
        '<filter id="shadow" x="-20%" y="-20%" width="140%" height="140%"><feDropShadow dx="3" dy="5" stdDeviation="4" flood-color="#9AB2BD" flood-opacity="0.45"/></filter>',
        "</defs>",
        f'<rect width="{w}" height="{h}" fill="{GREY}"/>',
        f'<rect x="50" y="45" width="{w-100}" height="100" rx="26" fill="{NAVY}"/>',
        svg_text(75, 84, f"Figure {diagram.number}", 28, TEAL_LIGHT, "700", "start"),
        svg_text(75, 118, diagram.title, 25, WHITE, "700", "start"),
    ]
    for shape in diagram.shapes:
        if isinstance(shape, Box):
            dash = ' stroke-dasharray="8 7"' if shape.dashed else ""
            out.append(
                f'<rect x="{shape.x}" y="{shape.y}" width="{shape.w}" height="{shape.h}" rx="{shape.radius}" '
                f'fill="{shape.fill}" stroke="{shape.stroke}" stroke-width="3"{dash} filter="url(#shadow)"/>'
            )
            lines = wrap_text(shape.text, max(10, int(shape.w / 12)))
            size = 24 if shape.title else 21
            out.append(svg_text(shape.x + shape.w / 2, shape.y + shape.h / 2 - (len(lines) * (size + 7)) / 2 + size, shape.text, size, shape.color, "700" if shape.title else "500"))
        elif isinstance(shape, Ellipse):
            out.append(
                f'<ellipse cx="{shape.x + shape.w/2}" cy="{shape.y + shape.h/2}" rx="{shape.w/2}" ry="{shape.h/2}" fill="{shape.fill}" stroke="{shape.stroke}" stroke-width="3"/>'
            )
            out.append(svg_text(shape.x + shape.w / 2, shape.y + shape.h / 2, shape.text, 20, shape.color, "700"))
        elif isinstance(shape, Actor):
            x, y = shape.x, shape.y
            out.append(f'<circle cx="{x}" cy="{y+18}" r="18" fill="none" stroke="{DEEP_NAVY}" stroke-width="4"/>')
            out.append(f'<path d="M{x},{y+36} L{x},{y+95} M{x-42},{y+60} L{x+42},{y+60} M{x},{y+95} L{x-38},{y+145} M{x},{y+95} L{x+38},{y+145}" stroke="{DEEP_NAVY}" stroke-width="4" fill="none"/>')
            out.append(svg_text(x, y + 170, shape.text, 20, DEEP_NAVY, "700"))
        elif isinstance(shape, Arrow):
            dash = ' stroke-dasharray="8 7"' if shape.dashed else ""
            out.append(
                f'<line x1="{shape.x1}" y1="{shape.y1}" x2="{shape.x2}" y2="{shape.y2}" stroke="{shape.color}" stroke-width="4"{dash} marker-end="url(#arrow)"/>'
            )
            if shape.label:
                out.append(svg_text((shape.x1 + shape.x2) / 2, (shape.y1 + shape.y2) / 2 - 14, shape.label, 18, DEEP_NAVY, "600"))
        elif isinstance(shape, Note):
            out.append(svg_text(shape.x, shape.y, shape.text, shape.size, shape.color, "500"))
    out.append(svg_text(w - 70, h - 45, "SERPS Architecture", 18, MUTED, "500", "end"))
    out.append("</svg>")
    path.write_text("\n".join(out), encoding="utf-8")


def write_mmd(diagram: Diagram, path: Path) -> None:
    init = "%%{init: {'theme': 'base', 'themeVariables': {'primaryColor': '#DDF7F5', 'primaryBorderColor': '#0F8B8D', 'lineColor': '#7FA9B5', 'fontFamily': 'Segoe UI, Arial'}}}%%\n"
    path.write_text(init + diagram.mmd.strip() + "\n", encoding="utf-8")


def pipeline_shapes(items: list[str], x: int = 650, y: int = 190, w: int = 500, h: int = 70, gap: int = 25) -> list[Shape]:
    shapes: list[Shape] = []
    for i, item in enumerate(items):
        yy = y + i * (h + gap)
        fill = TEAL_LIGHT if i in {0, len(items) - 1} else WHITE
        shapes.append(Box(x, yy, w, h, item, fill=fill, title=i == 0))
        if i:
            shapes.append(Arrow(x + w / 2, yy - gap + 3, x + w / 2, yy - 4))
    return shapes


def grid_boxes(items: list[str], x: int, y: int, cols: int, box_w: int, box_h: int, gap_x: int, gap_y: int, fill: str = WHITE) -> list[Shape]:
    shapes: list[Shape] = []
    for i, item in enumerate(items):
        row, col = divmod(i, cols)
        shapes.append(Box(x + col * (box_w + gap_x), y + row * (box_h + gap_y), box_w, box_h, item, fill=fill))
    return shapes


def mmd_flow(title: str, items: Iterable[str]) -> str:
    nodes = list(items)
    lines = ["flowchart TD"]
    for i, item in enumerate(nodes):
        lines.append(f'  N{i}["{item}"]')
        if i:
            lines.append(f"  N{i-1} --> N{i}")
    return "\n".join(lines)


def build_diagrams() -> list[Diagram]:
    diagrams: list[Diagram] = []

    # 3.1
    items = ["Problem Identification", "Literature Review", "Requirements Analysis", "System Architecture", "Prototype Design", "Final Evaluation", "Documentation & Dissertation"]
    shapes = pipeline_shapes(items[:5], 120, 190, 390, 68, 20)
    agile = ["Sprint Planning", "Implementation", "Sprint Review", "Testing", "Refinement"]
    center_x, center_y = 1120, 470
    positions = [(930, 265), (1280, 345), (1250, 620), (930, 700), (780, 485)]
    for label, (x, y) in zip(agile, positions, strict=True):
        shapes.append(Box(x, y, 250, 75, label, fill=TEAL_LIGHT if label == "Sprint Planning" else WHITE))
    for i in range(len(positions)):
        x1, y1 = positions[i]
        x2, y2 = positions[(i + 1) % len(positions)]
        shapes.append(Arrow(x1 + 125, y1 + 38, x2 + 125, y2 + 38))
    shapes.extend([Arrow(510, 560, 780, 522, "Agile loop"), Arrow(1040, 775, 1040, 875), Box(790, 875, 500, 70, "Final Evaluation", fill=AMBER_LIGHT), Arrow(1040, 945, 1040, 1030), Box(790, 1030, 500, 70, "Documentation & Dissertation", fill=TEAL_LIGHT)])
    diagrams.append(Diagram("3.1", "Hybrid Design Science Research and Agile Development Process Adopted for SERPS", "flowcharts", (1700, 1180), shapes, mmd_flow("3.1", items[:5] + agile + items[5:])))

    # 3.2
    trace = ["Stakeholder Requirements", "Functional Requirements", "Non-functional Requirements", "System Modules", "Implementation", "Testing", "Objective Verification"]
    diagrams.append(Diagram("3.2", "Requirements Traceability Model for SERPS", "architecture", (1500, 980), pipeline_shapes(trace, 500, 190, 500, 72, 28), mmd_flow("3.2", trace)))

    # 3.3 layered system architecture
    shapes = [
        Box(120, 190, 1260, 80, "Candidate, Reviewer/Proctor and Administrator Browsers", fill=TEAL_LIGHT, title=True),
        Box(120, 300, 1260, 80, "React / Next.js Frontend: candidate exam UI, reviewer console and admin dashboard", fill=WHITE),
        Box(120, 410, 390, 80, "REST API", fill=AMBER_LIGHT), Box(555, 410, 390, 80, "WebSocket / SSE", fill=AMBER_LIGHT), Box(990, 410, 390, 80, "WebRTC Boundary", fill=AMBER_LIGHT),
        Box(120, 530, 1260, 80, "FastAPI Application and Service Boundary", fill=TEAL_LIGHT, title=True),
    ]
    svc = ["Authentication", "Examination Engine", "Camera Manager", "Identity Assurance", "Monitoring Services", "EvidenceEvent Generation"]
    shapes.extend(grid_boxes(svc, 120, 650, 3, 390, 75, 45, 35))
    intel = ["Contextual Intelligence Engine", "Agentic Decision Support", "IPIME", "Human Reviewer", "Final Institutional Decision"]
    shapes.extend(grid_boxes(intel, 120, 890, 5, 235, 75, 22, 20, TEAL_LIGHT))
    shapes.extend([Box(1210, 650, 250, 180, "PostgreSQL\nShared Persistence", fill=GREY), Box(1210, 850, 250, 140, "Evidence Storage", fill=GREY)])
    for x in [315, 750, 1185]:
        shapes.append(Arrow(x, 380, x, 410))
    shapes.append(Arrow(750, 490, 750, 530))
    shapes.append(Arrow(750, 610, 750, 650))
    shapes.append(Arrow(705, 845, 705, 890))
    shapes.append(Arrow(1335, 830, 1335, 850, "shared", dashed=True))
    diagrams.append(Diagram("3.3", "Overall System Architecture of SERPS", "architecture", (1550, 1080), shapes, "flowchart TB\n  Users --> Frontend[React / Next.js]\n  Frontend --> API[FastAPI]\n  API --> Evidence[EvidenceEvent Generation]\n  Evidence --> CIE[Contextual Intelligence Engine]\n  CIE --> Agentic[Agentic Decision Support]\n  Agentic --> IPIME\n  IPIME --> Reviewer[Human Reviewer]\n  API -. shared persistence .-> DB[(PostgreSQL)]"))

    # 3.4
    stages = ["Registration", "Consent", "Device Check", "Camera Permission", "Guided Multi-angle Capture", "Image Quality Assessment", "Liveness Detection", "Embedding Generation", "Biometric Profile", "Continuous Identity Assurance"]
    shapes = pipeline_shapes(stages, 170, 180, 430, 65, 18)
    poses = ["Front", "Left", "Right", "Slight Up", "Slight Down", "Centre"]
    shapes.extend(grid_boxes(poses, 760, 420, 3, 210, 75, 30, 30, TEAL_LIGHT))
    shapes.append(Arrow(600, 470, 760, 465, "pose targets"))
    shapes.append(Box(720, 755, 790, 120, "Continuous verification compares live identity evidence with enrolled biometric profile and emits structured identity events.", fill=AMBER_LIGHT))
    diagrams.append(Diagram("3.4", "Candidate Registration, Guided Multi-angle Facial Enrolment and Continuous Identity Assurance Architecture", "architecture", (1600, 1030), shapes, mmd_flow("3.4", stages)))

    # 3.5
    shapes = [Box(575, 190, 450, 80, "Camera Manager", fill=TEAL_LIGHT, title=True)]
    controls = ["Permissions", "Discovery", "Mode Selection", "Health Monitoring", "Device Status", "EvidenceEvent Generation"]
    shapes.extend(grid_boxes(controls, 120, 330, 3, 390, 75, 45, 35))
    shapes.extend([Box(270, 620, 350, 90, "Primary Camera\nCandidate View", fill=WHITE), Box(980, 620, 350, 90, "Secondary Camera\nEnvironment View", fill=WHITE), Box(270, 790, 350, 80, "Face / Identity / Gaze", fill=TEAL_LIGHT), Box(980, 790, 350, 80, "Room / Object Context", fill=TEAL_LIGHT), Box(575, 900, 450, 80, "Structured EvidenceEvent", fill=AMBER_LIGHT)])
    for x in [315, 750, 1185]:
        shapes.append(Arrow(800, 270, x, 330))
    shapes.extend([Arrow(445, 710, 445, 790), Arrow(1155, 710, 1155, 790), Arrow(445, 870, 710, 900), Arrow(1155, 870, 890, 900)])
    diagrams.append(Diagram("3.5", "Camera and Sensor Management Architecture", "architecture", (1550, 1060), shapes, "flowchart TB\n  Manager[Camera Manager] --> Permissions\n  Manager --> Discovery\n  Manager --> Modes[Mode Selection]\n  Manager --> Health[Health Monitoring]\n  Manager --> Primary[Primary Camera]\n  Manager --> Secondary[Secondary Camera]\n  Primary --> Evidence[EvidenceEvent]\n  Secondary --> Evidence"))

    # 3.6
    sources = ["Face", "Gaze", "Head Pose", "Audio", "Browser", "Object Detection", "Room Monitoring", "System Health"]
    shapes = grid_boxes(sources, 120, 210, 4, 300, 78, 45, 40, WHITE)
    shapes.append(Box(475, 560, 600, 90, "Evidence Standardisation", fill=TEAL_LIGHT, title=True))
    shapes.append(Box(540, 760, 470, 85, "Structured EvidenceEvent", fill=AMBER_LIGHT, title=True))
    for i in range(8):
        row, col = divmod(i, 4)
        shapes.append(Arrow(270 + col * 345, 288 + row * 118, 775, 560))
    shapes.append(Arrow(775, 650, 775, 760))
    diagrams.append(Diagram("3.6", "Multimodal Evidence Acquisition Architecture", "architecture", (1550, 950), shapes, "flowchart TB\n  Face --> Std[Evidence Standardisation]\n  Gaze --> Std\n  HeadPose --> Std\n  Audio --> Std\n  Browser --> Std\n  Objects --> Std\n  Room --> Std\n  Health --> Std\n  Std --> EvidenceEvent"))

    # 3.7 hero CIE
    shapes = [
        Box(120, 250, 300, 85, "EvidenceEvent", fill=AMBER_LIGHT, title=True),
        Box(520, 250, 360, 85, "Event Fusion Module", fill=TEAL_LIGHT, title=True),
        Box(980, 250, 360, 85, "Temporal Behaviour Memory", fill=WHITE, title=True),
        Box(520, 480, 360, 85, "Contextual Reasoning Module", fill=TEAL_LIGHT, title=True),
        Box(150, 690, 360, 85, "Risk Scoring Engine", fill=WHITE, title=True),
        Box(610, 690, 360, 85, "Explainability Interface", fill=WHITE, title=True),
        Box(1070, 690, 360, 85, "Contextual Assessment", fill=AMBER_LIGHT, title=True),
    ]
    shapes.extend([Arrow(420, 292, 520, 292), Arrow(880, 292, 980, 292), Arrow(1160, 335, 720, 480), Arrow(700, 335, 700, 480), Arrow(700, 565, 330, 690), Arrow(700, 565, 790, 690), Arrow(970, 732, 1070, 732), Arrow(510, 732, 610, 732)])
    diagrams.append(Diagram("3.7", "Internal Architecture of the Contextual Intelligence Engine", "architecture", (1550, 900), shapes, "flowchart LR\n  EvidenceEvent --> Fusion[Event Fusion Module]\n  Fusion --> Memory[Temporal Behaviour Memory]\n  Memory --> Reasoning[Contextual Reasoning Module]\n  Reasoning --> Risk[Risk Scoring Engine]\n  Reasoning --> Explain[Explainability Interface]\n  Risk <--> Explain\n  Explain --> Assessment[Contextual Assessment]\n  Risk --> Assessment"))

    # 3.8
    shapes = [Box(560, 190, 440, 80, "Contextual Assessment", fill=AMBER_LIGHT, title=True), Box(560, 360, 440, 80, "Agentic Reasoning", fill=TEAL_LIGHT, title=True)]
    rec = ["Continue Monitoring", "Request Re-authentication", "Notify Reviewer", "Escalate Incident"]
    shapes.extend(grid_boxes(rec, 150, 570, 4, 290, 85, 45, 20, WHITE))
    shapes.append(Box(560, 780, 440, 80, "Advisory Recommendation\nNot a final decision", fill=AMBER_LIGHT, title=True))
    shapes.extend([Arrow(780, 270, 780, 360), Arrow(780, 440, 780, 570)])
    for i in range(4):
        shapes.append(Arrow(295 + i * 335, 655, 780, 780))
    diagrams.append(Diagram("3.8", "Agentic Decision Support Architecture", "architecture", (1500, 960), shapes, "flowchart TB\n  Assessment --> Agentic[Agentic Reasoning]\n  Agentic --> Continue[Continue Monitoring]\n  Agentic --> Reauth[Request Re-authentication]\n  Agentic --> Notify[Notify Reviewer]\n  Agentic --> Escalate[Escalate Incident]\n  Continue --> Recommendation[Advisory Recommendation]"))

    # 3.9
    shapes = [Box(100, 190, 350, 80, "Agentic Recommendation", fill=AMBER_LIGHT), Box(575, 190, 400, 80, "Policy-as-Code Rules", fill=TEAL_LIGHT, title=True), Box(1100, 190, 350, 80, "Institutional Policy", fill=WHITE)]
    actions = ["Warning", "Pause Exam", "Screen Shield", "Acknowledgement", "Escalation", "Reviewer Workflow"]
    shapes.extend(grid_boxes(actions, 165, 420, 3, 360, 80, 55, 50, WHITE))
    shapes.append(Box(575, 800, 400, 80, "Audit Log and Incident Package", fill=AMBER_LIGHT, title=True))
    shapes.extend([Arrow(450, 230, 575, 230), Arrow(975, 230, 1100, 230), Arrow(775, 270, 775, 420)])
    for i in range(6):
        row, col = divmod(i, 3)
        shapes.append(Arrow(775, 500 + row * 130, 745, 800))
    diagrams.append(Diagram("3.9", "Institutional Policy and Incident Management Engine", "architecture", (1550, 980), shapes, "flowchart TB\n  Recommendation --> Policy[Policy-as-Code Rules]\n  InstitutionalPolicy --> Policy\n  Policy --> Warning\n  Policy --> Pause[Pause Exam]\n  Policy --> Shield[Screen Shield]\n  Policy --> Ack[Acknowledgement]\n  Policy --> Escalation\n  Policy --> Reviewer[Reviewer Workflow]\n  Reviewer --> Audit[Audit Log]"))

    # 3.10
    pipeline = ["Detection", "Structured EvidenceEvent", "Contextual Intelligence Engine", "Agentic Recommendation", "Institutional Policy", "Candidate Acknowledgement\n(where required)", "Human Reviewer", "Final Institutional Decision", "Audit"]
    shapes = pipeline_shapes(pipeline, 515, 180, 520, 70, 20)
    shapes.append(Box(1075, 680, 330, 150, "Human governance boundary:\nSERPS supports review, but does not issue automatic misconduct decisions.", fill=AMBER_LIGHT))
    shapes.append(Arrow(1035, 715, 1075, 735, dashed=True))
    diagrams.append(Diagram("3.10", "Governance-aware Decision Pipeline", "flowcharts", (1500, 1100), shapes, mmd_flow("3.10", pipeline)))

    # 3.11
    shapes = [
        Box(100, 250, 400, 430, "Mode A\nSingle-camera CBT mode\n\nPrimary camera required\nSecondary not required\nCBT-centre limitation note", fill=TEAL_LIGHT, title=True),
        Box(575, 250, 400, 430, "Mode B\nDual-camera full mode\n\nPrimary required\nSecondary required\nFull remote-proctoring coverage", fill=WHITE, title=True),
        Box(1050, 250, 400, 430, "Mode C\nMirror-assisted low-resource mode\n\nPrimary required\nMirror required\nSecondary not required", fill=TEAL_LIGHT, title=True),
    ]
    diagrams.append(Diagram("3.11", "Deployment Modes Supported by SERPS", "architecture", (1550, 820), shapes, "flowchart LR\n  A[Mode A: Primary Camera] --- B[Mode B: Primary + Secondary]\n  B --- C[Mode C: Primary + Mirror]"))

    # 3.12
    shapes = [Box(100, 220, 280, 75, "Camera / Audio / Browser", fill=WHITE), Box(470, 220, 280, 75, "Detection Modules", fill=WHITE), Box(840, 220, 280, 75, "EvidenceEvent", fill=AMBER_LIGHT, title=True), Box(1220, 120, 280, 75, "Contextual Intelligence", fill=TEAL_LIGHT), Box(1220, 330, 280, 75, "PostgreSQL\nPersistence", fill=GREY), Box(840, 550, 280, 75, "Reports and Audit", fill=WHITE), Box(1220, 550, 280, 75, "Reviewer Console", fill=WHITE)]
    shapes.extend([Arrow(380, 257, 470, 257), Arrow(750, 257, 840, 257), Arrow(1120, 245, 1220, 165), Arrow(1120, 270, 1220, 365), Arrow(1360, 405, 980, 550, "read", dashed=True), Arrow(1120, 590, 1220, 590)])
    diagrams.append(Diagram("3.12", "High-Level Data Flow within SERPS", "flowcharts", (1600, 780), shapes, "flowchart LR\n  Sources --> Detection --> EvidenceEvent\n  EvidenceEvent --> CIE\n  EvidenceEvent -. persists .-> DB[(PostgreSQL)]\n  DB -. read .-> Reports\n  Reports --> Reviewer"))

    # 3.13 use case
    shapes = [Actor(120, 240, "Candidate"), Actor(1390, 220, "Reviewer/\nProctor"), Actor(120, 690, "Administrator"), Actor(1390, 690, "System\nAdministrator"), Box(330, 195, 850, 760, "SERPS System Boundary", fill="#F8FBFC", stroke=LINE, dashed=True)]
    usecases = ["Register", "Enrol Face", "Authenticate", "Take Examination", "Receive Warning", "Review Evidence", "Manage Policies", "Generate Reports", "Manage Users"]
    coords = [(440, 270), (700, 270), (960, 270), (555, 465), (860, 465), (555, 660), (860, 660), (555, 835), (860, 835)]
    for label, (x, y) in zip(usecases, coords, strict=True):
        shapes.append(Ellipse(x, y, 220, 80, label, fill=TEAL_LIGHT if label in {"Register", "Review Evidence"} else WHITE))
    for (x, y) in coords:
        shapes.append(Arrow(230, 315, x, y + 40, dashed=True))
    shapes.extend([Arrow(1390, 330, 1160, 700, dashed=True), Arrow(1390, 330, 1160, 505, dashed=True), Arrow(230, 780, 860, 700, dashed=True), Arrow(1390, 800, 1080, 875, dashed=True)])
    diagrams.append(Diagram("3.13", "Use Case Diagram of SERPS", "uml", (1550, 1050), shapes, "flowchart LR\n  Candidate((Candidate)) --> Register((Register))\n  Candidate --> Enrol((Enrol Face))\n  Candidate --> Exam((Take Examination))\n  Reviewer((Reviewer/Proctor)) --> Review((Review Evidence))\n  Admin((Administrator)) --> Policies((Manage Policies))\n  SysAdmin((System Administrator)) --> Users((Manage Users))"))

    # 3.14 activity
    activity = ["Start", "Register / Authenticate", "Select Monitoring Mode", "Run Device Checks", "Start Examination", "Generate Evidence Events", "CIE Contextual Assessment", "Agentic Recommendation", "IPIME Policy Evaluation", "Acknowledgement Required?", "Human Review", "Final Outcome", "Audit Report"]
    shapes = pipeline_shapes(activity, 500, 175, 550, 58, 14)
    shapes.append(Box(1120, 735, 300, 100, "No: Continue Monitoring", fill=TEAL_LIGHT))
    shapes.append(Arrow(1050, 735, 1120, 775, "no"))
    diagrams.append(Diagram("3.14", "Activity Diagram of SERPS", "uml", (1550, 1120), shapes, mmd_flow("3.14", activity)))

    # 3.15 sequence
    participants = ["Candidate", "React Frontend", "FastAPI", "Authentication", "Camera Manager", "Evidence Services", "CIE", "Agentic", "IPIME", "Reviewer", "PostgreSQL"]
    x_positions = [90 + i * 135 for i in range(len(participants))]
    shapes = []
    for p, x in zip(participants, x_positions, strict=True):
        shapes.append(Box(x, 190, 115, 55, p, fill=TEAL_LIGHT if p in {"CIE", "IPIME"} else WHITE))
        shapes.append(Arrow(x + 57, 245, x + 57, 950, dashed=True))
    messages = [(0, 1, 300, "start"), (1, 2, 350, "request"), (2, 3, 400, "authenticate"), (2, 4, 470, "camera control"), (4, 5, 540, "evidence"), (5, 10, 610, "persist"), (5, 6, 680, "events"), (6, 7, 750, "assessment"), (7, 8, 820, "recommendation"), (8, 9, 890, "policy response")]
    for a, b, y, label in messages:
        shapes.append(Arrow(x_positions[a] + 115, y, x_positions[b], y, label))
    diagrams.append(Diagram("3.15", "Sequence Diagram of SERPS", "uml", (1650, 1020), shapes, "sequenceDiagram\n  participant Candidate\n  participant React\n  participant FastAPI\n  participant Auth\n  participant Camera\n  participant Evidence\n  participant CIE\n  participant Agentic\n  participant IPIME\n  participant Reviewer\n  participant PostgreSQL\n  Candidate->>React: Start exam\n  React->>FastAPI: Request session\n  FastAPI->>Auth: Verify identity\n  Camera->>Evidence: Emit EvidenceEvent\n  Evidence->>PostgreSQL: Persist raw event\n  Evidence->>CIE: Submit event\n  CIE->>Agentic: Contextual assessment\n  Agentic->>IPIME: Recommendation\n  IPIME->>Reviewer: Policy workflow"))

    # 3.16 class
    class_items = ["User", "Candidate", "Reviewer", "Administrator", "Institution", "Examination", "ExaminationSession", "EvidenceEvent", "ContextualAssessment", "Recommendation", "PolicyRule", "Incident", "Acknowledgement", "ReviewerAction", "AuditLog"]
    shapes = grid_boxes(class_items, 110, 200, 5, 255, 70, 35, 45, WHITE)
    rels = [(0, 1), (0, 2), (0, 3), (4, 5), (5, 6), (6, 7), (7, 8), (8, 9), (9, 11), (10, 11), (11, 12), (11, 13), (13, 14)]
    centers = [(110 + (i % 5) * 290 + 127, 200 + (i // 5) * 115 + 35) for i in range(len(class_items))]
    for a, b in rels:
        shapes.append(Arrow(*centers[a], *centers[b], dashed=True))
    diagrams.append(Diagram("3.16", "Class Diagram of SERPS", "uml", (1550, 760), shapes, "classDiagram\n  User <|-- Candidate\n  User <|-- Reviewer\n  User <|-- Administrator\n  Institution --> Examination\n  Examination --> ExaminationSession\n  ExaminationSession --> EvidenceEvent\n  EvidenceEvent --> ContextualAssessment\n  ContextualAssessment --> Recommendation\n  Recommendation --> Incident\n  PolicyRule --> Incident\n  Incident --> Acknowledgement\n  Incident --> ReviewerAction\n  ReviewerAction --> AuditLog"))

    # 3.17 component
    comps = ["Next.js Frontend", "FastAPI API", "Authentication Service", "Camera Service", "Vision Services", "Audio Services", "Evidence Service", "CIE", "Agentic Support", "IPIME", "Reporting", "Audit", "PostgreSQL", "Evidence Storage"]
    shapes = grid_boxes(comps, 90, 195, 4, 315, 75, 45, 45, WHITE)
    for a, b in [(0, 1), (1, 2), (1, 3), (3, 4), (3, 5), (4, 6), (5, 6), (6, 7), (7, 8), (8, 9), (9, 10), (10, 11), (6, 12), (6, 13)]:
        centers = [(90 + (i % 4) * 360 + 157, 195 + (i // 4) * 120 + 37) for i in range(len(comps))]
        shapes.append(Arrow(*centers[a], *centers[b]))
    diagrams.append(Diagram("3.17", "Component Diagram of SERPS", "uml", (1550, 710), shapes, "flowchart LR\n  Web[Next.js Frontend] --> API[FastAPI API]\n  API --> Auth\n  API --> Camera\n  Camera --> Vision\n  Camera --> Audio\n  Vision --> Evidence\n  Audio --> Evidence\n  Evidence --> CIE\n  CIE --> Agentic\n  Agentic --> IPIME\n  IPIME --> Reporting\n  Evidence -.-> DB[(PostgreSQL)]"))

    # 3.18 deployment
    nodes = ["Candidate Browser", "Reviewer Browser", "Administrator Browser", "Next.js Web Application", "FastAPI API Container", "AI / Monitoring Services", "PostgreSQL Container", "Evidence Storage", "Docker Network", "Optional Cloud / Edge Boundary"]
    shapes = grid_boxes(nodes, 100, 195, 3, 390, 95, 55, 55, WHITE)
    centers = [(100 + (i % 3) * 445 + 195, 195 + (i // 3) * 150 + 47) for i in range(len(nodes))]
    for a, b, label in [(0, 3, "HTTPS"), (1, 3, "HTTPS"), (2, 3, "HTTPS"), (3, 4, "REST"), (0, 5, "WebRTC"), (4, 5, "SSE/WebSocket"), (4, 6, "SQL"), (5, 7, "evidence"), (4, 8, ""), (9, 8, "optional")]:
        shapes.append(Arrow(*centers[a], *centers[b], label))
    diagrams.append(Diagram("3.18", "Deployment Diagram of SERPS", "uml", (1550, 790), shapes, "flowchart TB\n  CandidateBrowser --> Web[Next.js Web Application]\n  ReviewerBrowser --> Web\n  AdminBrowser --> Web\n  Web --> API[FastAPI API Container]\n  CandidateBrowser -. WebRTC .-> AI[AI / Monitoring Services]\n  API --> DB[(PostgreSQL Container)]\n  API --> Storage[Evidence Storage]\n  API <--> AI"))

    # 3.19 from SQLAlchemy metadata
    shapes = []
    tables = list(Base.metadata.sorted_tables)
    if not tables:
        shapes.append(Box(450, 300, 600, 120, "No SQLAlchemy tables detected", fill=AMBER_LIGHT))
    else:
        for i, table in enumerate(tables):
            cols = [f"{col.name}: {col.type}" for col in table.columns]
            text = table.name + "\n" + "\n".join(cols[:12])
            row, col = divmod(i, 3)
            shapes.append(Box(70 + col * 500, 190 + row * 270, 455, 230, text, fill=TEAL_LIGHT if i == 0 else WHITE, title=True))
    rows = max(1, math.ceil(max(len(tables), 1) / 3))
    diagrams.append(
        Diagram(
            "3.19",
            "Entity Relationship Diagram of SERPS Database",
            "architecture",
            (1600, max(820, 230 + rows * 270)),
            shapes,
            erd_mermaid_from_metadata(),
            notes=[
                "ERD generated from implemented SQLAlchemy metadata. Sprint 2 adds identity, RBAC, candidate, examination, assignment, session, token and audit tables.",
            ],
        )
    )

    # 3.20 API hub
    shapes = [Box(575, 180, 400, 80, "React / Next.js", fill=TEAL_LIGHT, title=True), Box(575, 330, 400, 80, "REST API / WebSocket", fill=AMBER_LIGHT), Box(575, 480, 400, 80, "FastAPI Hub", fill=TEAL_LIGHT, title=True)]
    services = ["Authentication", "Candidates", "Examinations", "Camera", "Identity", "Evidence", "CIE", "Agentic", "IPIME", "Reporting", "Audit"]
    shapes.extend(grid_boxes(services, 80, 680, 4, 315, 70, 45, 40, WHITE))
    shapes.extend([Box(1120, 470, 320, 90, "PostgreSQL", fill=GREY), Box(1120, 580, 320, 90, "Evidence Storage", fill=GREY)])
    shapes.extend([Arrow(775, 260, 775, 330), Arrow(775, 410, 775, 480), Arrow(975, 520, 1120, 515), Arrow(975, 540, 1120, 625)])
    for i in range(len(services)):
        row, col = divmod(i, 4)
        shapes.append(Arrow(775, 560, 237 + col * 360, 680 + row * 110))
    diagrams.append(Diagram("3.20", "API Interaction Diagram of SERPS", "api", (1550, 1050), shapes, "flowchart TB\n  React --> Boundary[REST API / WebSocket]\n  Boundary --> FastAPI[FastAPI Hub]\n  FastAPI --> Authentication\n  FastAPI --> Candidates\n  FastAPI --> Examinations\n  FastAPI --> Camera\n  FastAPI --> Identity\n  FastAPI --> Evidence\n  FastAPI --> CIE\n  FastAPI --> Agentic\n  FastAPI --> IPIME\n  FastAPI --> Reporting\n  FastAPI --> Audit\n  FastAPI -.-> PostgreSQL\n  FastAPI -.-> Storage[Evidence Storage]"))

    # 3.21 technology stack
    layers = [
        "Presentation\nNext.js / React / TypeScript\nImplemented foundation",
        "API / Application\nFastAPI, Pydantic\nImplemented foundation",
        "Real-time Communication\nWebSocket / SSE / WebRTC\nPlanned interfaces",
        "AI / ML\nOpenCV, MediaPipe, YOLO\nPlanned POP migration",
        "Intelligence / Governance\nCIE, Agentic, IPIME\nPOC implemented; POP migration pending",
        "Persistence\nSQLAlchemy, Alembic, PostgreSQL\nConfigured and migration-verified",
        "Infrastructure / DevOps\nDocker Compose, GitHub Actions\nImplemented foundation",
    ]
    diagrams.append(Diagram("3.21", "Technology Stack of SERPS", "technology", (1500, 1050), pipeline_shapes(layers, 440, 185, 620, 95, 25), mmd_flow("3.21", layers)))

    return diagrams


def checksum(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()[:16]


def write_index(diagrams: list[Diagram], artefacts: dict[str, dict[str, str]]) -> None:
    lines = ["# Chapter Three Figure Index", ""]
    for d in diagrams:
        lines.append(f"- Figure {d.number}: {d.title}")
        lines.append(f"  - Source: `source/{d.safe_name}.mmd`")
        lines.append(f"  - SVG: `svg/{d.safe_name}.svg`")
        lines.append(f"  - PNG: `png/{d.safe_name}.png`")
    (OUT / "figure_index.md").write_text("\n".join(lines) + "\n", encoding="utf-8")

    captions = ["# Chapter Three Captions", ""]
    for d in diagrams:
        captions.append(f"**Figure {d.number}: {d.title}.**")
        captions.append(f"Source: {d.source}.")
        captions.append("")
    (OUT / "captions.md").write_text("\n".join(captions), encoding="utf-8")

    manifest = {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "generator": "scripts/docs/generate_chapter3_diagrams.py",
        "figures": artefacts,
    }
    (OUT / "manifest.json").write_text(json.dumps(manifest, indent=2), encoding="utf-8")


def validate(diagrams: list[Diagram], artefacts: dict[str, dict[str, str]]) -> None:
    lines = [
        "# Chapter Three Diagram Validation Report",
        "",
        f"Generated at: {datetime.now(timezone.utc).isoformat()}",
        "",
        "## Summary",
        "",
        f"- Figures requested: 21",
        f"- Figures generated: {len(diagrams)}",
        "- Editable Mermaid sources generated for every figure.",
        "- SVG exports generated for every figure.",
        "- High-resolution PNG exports generated for every figure with 300 DPI metadata.",
        "- Draw.io exports were not generated in this urgent sprint; Mermaid sources remain editable and SVG is the publication authority.",
        "",
        "## Validation Results",
        "",
    ]
    for d in diagrams:
        files = artefacts[d.number]
        ok = all((ROOT / files[key]).exists() for key in ("source", "category_source", "svg", "png"))
        lines.append(f"- Figure {d.number}: {'PASS' if ok else 'NEEDS REVIEW'} - {d.title}")
        for note in d.notes:
            lines.append(f"  - Note: {note}")
    lines.extend(
        [
            "",
            "## Figure 3.19 Schema Status",
            "",
            "Figure 3.19 was generated from the current SQLAlchemy metadata. The present POP schema includes EvidenceEvent persistence plus Sprint 2 institution, user, role, candidate, examination, assignment, session, authentication, refresh-token and audit-log tables.",
            "",
            "## Architecture Consistency Checks",
            "",
            "- Detection modules are shown as evidence producers only.",
            "- CIE is shown as the central reasoning layer.",
            "- Agentic Decision Support is shown as advisory only.",
            "- IPIME is shown as institutional workflow/policy handling, not final decision-making.",
            "- Human Reviewer and final institutional decision boundaries are explicit.",
            "- PostgreSQL is represented as shared persistence, not a reasoning component.",
            "- React/Next.js is represented as presentation/control surface, not as CIE or AI business logic.",
        ]
    )
    (OUT / "diagram_validation_report.md").write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    for subdir in SUBDIRS:
        (OUT / subdir).mkdir(parents=True, exist_ok=True)
    diagrams = build_diagrams()
    artefacts: dict[str, dict[str, str]] = {}
    for d in diagrams:
        mmd_path = OUT / "source" / f"{d.safe_name}.mmd"
        svg_path = OUT / "svg" / f"{d.safe_name}.svg"
        png_path = OUT / "png" / f"{d.safe_name}.png"
        category_mmd = OUT / d.category / f"{d.safe_name}.mmd"
        write_mmd(d, mmd_path)
        write_mmd(d, category_mmd)
        render_svg(d, svg_path)
        render_png(d, png_path)
        artefacts[d.number] = {
            "source": str(mmd_path.relative_to(ROOT)),
            "category_source": str(category_mmd.relative_to(ROOT)),
            "svg": str(svg_path.relative_to(ROOT)),
            "png": str(png_path.relative_to(ROOT)),
            "source_sha256": checksum(mmd_path),
            "svg_sha256": checksum(svg_path),
            "png_sha256": checksum(png_path),
        }
    write_index(diagrams, artefacts)
    validate(diagrams, artefacts)
    print(f"Generated {len(diagrams)} Chapter Three figures in {OUT}")


if __name__ == "__main__":
    main()
